### ISSUE TITLE
2023-03-14T07:47:33.095Z

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dart#1008]
We have `shouldCompactOnLaunch` exposed on local config, but it's a valid callback for sync configs as well. We should expose it to all persisted configs (i.e. all without in-memory).

**Comment by desistefanova** [comment]
We have already implemented [shouldCompactOnLaunch ](https://github.com/realm/realm-dart/blob/e93716f0b9bb0ba8949e08b85ad17c420787fa49/lib/src/configuration.dart#L43).
Is this issue about something different?

**Comment by nirinchev** [comment]
Ah, I see - I was looking for it on the flexible sync config and I thought we didn't have it. We should move it to the base config and expose it on the sync configs as well.
