### ISSUE TITLE
Invalid argument(s): Failed to lookup symbol 'realm_dart_library_version': undefined symbol: realm_dart_library_version

### ISSUE THREAD

**Issue by SPSpisoft** [realm/realm-dart#1014]
### What happened?

Hi.. I upgrade to RC version :) encountered this error :(
Invalid argument(s): Failed to lookup symbol 'realm_dart_library_version': undefined symbol: realm_dart_library_version

### Repro steps

The relevant error-causing widget was: 
  GetMaterialApp GetMaterialApp:file:///D:/___FlutterProjects/mypackage/lib/main.dart:145:16
When the exception was thrown, this was the stack: 
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:34:70)
#1      RealmLibrary._realm_dart_library_versionPtr (package:realm/src/native/realm_bindings.dart:3156:68)
#2      RealmLibrary._realm_dart_library_versionPtr (package:realm/src/native/realm_bindings.dart)
#3      RealmLibrary._realm_dart_library_version (package:realm/src/native/realm_bindings.dart:3158:44)
#4      RealmLibrary._realm_dart_library_version (package:realm/src/native/realm_bindings.dart)
#5      RealmLibrary.realm_dart_library_version (package:realm/src/native/realm_bindings.dart:3152:12)
#6      _RealmCore.nativeLibraryVersion (package:realm/src/native/realm_core.dart:86:48)
#7      _RealmCore.nativeLibraryVersion (package:realm/src/native/realm_core.dart)
#8      new _RealmCore._ (package:realm/src/native/realm_core.dart:74:27)
#9      new _RealmCore (package:realm/src/native/realm_core.dart:81:37)
#10     realmCore (package:realm/src/native/realm_core.dart:51:30)
#11     realmCore (package:realm/src/native/realm_core.dart)
#12     Configuration.defaultStoragePath (package:realm/src/configuration.dart:100:14)
#13     Configuration.defaultRealmPath (package:realm/src/configuration.dart:110:47)
#14     Configuration.defaultRealmPath (package:realm/src/configuration.dart)
#15     Configuration._defaultPath (package:realm/src/configuration.dart:123:44)
#16     new Configuration._ (package:realm/src/configuration.dart:119:50)
#17     new LocalConfiguration._ (package:realm/src/configuration.dart:249:14)
#18     Configuration.local (package:realm/src/configuration.dart:160:26)
#19     _EmployerPageState.initState (package:mypackag/pages/employer_page.dart:49:47)
#20     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5015:57)
#21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
...     Normal element mounting (275 frames)
#296    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#297    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#298    Element.updateChild (package:flutter/src/widgets/framework.dart:3592:18)
#299    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5964:32)
#300    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#301    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#302    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#303    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)

### Version

realm: ^0.7.0+rc

### What Realm SDK flavor are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

windows 10

**Comment by blagoev** [comment]
Hi, 
which version of the realm package did you previously. It seems your app is not rebuilt with the new version of the realm package after it has been updated and uses an old library version. 
Can you do a `flutter clean` and then try building and running your app again.
if it does not help please report back so we can assist you with debugging the issue

cheers

**Comment by SPSpisoft** [comment]
@blagoev Thank you, This worked for me :)
