### ISSUE TITLE
[Bug]: [LINUX] Failed to load dynamic library 'librealm_dart.so': librealm_dart.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by c0c4i** [realm/realm-dart#1017]
### What happened?

Hello, I'm using realm 0.7.0+rc on linux arm64 for Flutter.
In this initial code
```
var config = Configuration.local(
      [
        RealmBoard.schema,
        // other schema
      ],
      schemaVersion: 12,
    );
    realm = Realm(config);
```
I have this exception
```
"Failed to load dynamic library 'librealm_dart.so': librealm_dart.so: cannot open shared object file: No such file or directory"
```
I don't know what to do.
Thank you for help.

### Repro steps

1. Run the app
2. Crash on line `realm = Realm(config);`

### Version

Flutter 3.5.0-12.0.pre.145 • channel master • https://github.com/flutter/flutter.git Framework • revision a1289a4135 (5 hours ago) • 2022-11-07 06:46:25 -0500 Engine • revision 891d4a3577 Tools • Dart 2.19.0 (build 2.19.0-374.0.dev) • DevTools 2.19.0

### What Realm SDK flavor are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

Linux Ubuntu 20.04 LTS

### Code snippets

```
var config = Configuration.local(
      [
        RealmBoard.schema,
        // other schema
      ],
      schemaVersion: 12,
    );
    realm = Realm(config);
```

### Stacktrace of the exception/crash you're getting

```shell
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      _open (package:realm/src/init.dart:84:52)
#3      _openRealmLib.<anonymous closure> (package:realm/src/init.dart:70:11)
#4      _openRealmLib (package:realm/src/init.dart:76:18)
#5      initRealm (package:realm/src/init.dart:105:24)
#6      new _RealmCore._ (package:realm/src/native/realm_core.dart:72:17)
#7      new _RealmCore (package:realm/src/native/realm_core.dart:81:37)
#8      realmCore (package:realm/src/native/realm_core.dart:51:30)
#9      realmCore (package:realm/src/native/realm_core.dart)
#10     Realm._openRealm (package:realm/src/realm_class.dart:180:12)
#11     new Realm._ (package:realm/src/realm_class.dart:135:98)
#12     new Realm (package:realm/src/realm_class.dart:133:38)
#13     ControlRepository.initControl (package:control_repository/src/control_repository.dart:69:13)
```

**Comment by c0c4i** [comment]
Hi, I also tried this on AMD64 running documentation example but doesn’t work so I think this problem it’s not ralated to architecture.

**Comment by desistefanova** [comment]
It looks like the realm library is not installed. 
If you are running a dart project you should use `realm_dart` package and to run `dart run realm_dart install` command.
But for Flutter projects the package name is `realm` and the library is installed automatically when you run the app.
Can you share your repository or the project?

**Comment by NotZoeyDev** [comment]
I'm having the same issue trying to use realm_dart, it works perfectly fine on my Windows machine but it fails to load the native library when loaded onto my Linux VPS.

I've ran `dart run realm_dart install` and I can confirm that the file is there, it just doesn't try to load it from that path it seems, any clue what could be causing this?

**Comment by desistefanova** [comment]
Hi @NotZoeyDev,
Thanks for the report.
We managed to reproduce this issue on Linux environment.
We will investigate it.
You can follow https://github.com/realm/realm-dart/issues/1141
