### ISSUE TITLE
[Bug]: syncErrorHandler doesn't occur because of mapping error codes exception

### ISSUE THREAD

**Issue by desistefanova** [realm/realm-dart#1024]
### What happened?

Missing value 231 in `SyncSessionErrorCode` enum.
An error happen while mapping the error codes  `RealmError("Unknown SyncSessionErrorCode")`.
Then syncErrorHandler doesn't occur for the end user.
An error is printed as INFO:
`flutter: [INFO] Realm: Connection[1]: Session[1]: Received: ERROR "Client attempted a write that is outside of permissions or query filters; it has been reverted" (error_code=231, try_again=true, error_action=Warning)`

### Repro steps

Open a synced Realm and add subscription with query filtering all the dogs with breed "puddel". Then add a new dog with breed "bulldog". See the code snippet.

### Version

0.7.0+rc

### What Realm SDK flavor are you using?

MongoDB Atlas (i.e. Sync, auth, functions)

### What type of application is this?

Flutter Application

### Client OS and version

Windows 11

### Code snippets

```dart
  App app = App(AppConfiguration(".........."));
  final user = await app.logIn(Credentials.anonymous());
  final config = Configuration.flexibleSync(
    user,
    [Dog.schema],
    syncErrorHandler: (p0) {
      print(p0);
    },
  );
  realm = Realm(config);

  final RealmResults<Dog> query = realm.query<Dog>(r'breed LIKE[c] $0', ['puddel']);
  if (realm.subscriptions.find(query) == null) {
    realm.subscriptions.update((mutableSubscriptions) {
      mutableSubscriptions.add(query);
    });

    realm.subscriptions.waitForSynchronization();
  }

  realm.write(() {
     realm.add(Dog(ObjectId(), name: "Foxi", breed: "bulldog"));
  });
```

### Stacktrace of the exception/crash you're getting

```shell
static SyncSessionErrorCode fromInt(int code) {
    final mappedCode = SyncSessionErrorCode._valuesMap[code];
    if (mappedCode == null) {
      throw RealmError("Unknown SyncSessionErrorCode");
    }
.....
```

**Comment by nirinchev** [comment]
We should probably handle this more robustly. It's not unlikely that there may be a session error code added that doesn't exist in the enum. We should not be silently ignoring these errors or even worse - throwing uncatchable errors. My suggestion would be to have a fallback and default to `unknown` error code.
