### ISSUE TITLE
[Bug]:  AppException: non-zero custom status code considered fatal, link to server logs: null

### ISSUE THREAD

**Issue by geosebas** [realm/realm-dart#1028]
### What happened?

Hello ! 

I tried to run my app on old android devices, a samung tablet running on Android 7.0 but I was unable to connect. 
I then tried to reproduce on the android emulator (api level 24, android 7.0 nougat) and it still didn't work.

I only got the error mentioned on the bug title. 
I tried with an older version of realm (0.3.1) and got nearly the same error : RealmException: non-zero custom status code considered fatal. (Not sure for error text on 0.3.1, but it should be that)

My app is still in development, but it currently work well on Tiramisu (api level 33) on emulator and on my samsung phone (android 12.0)
I didn't manage to find if you only support specific android version, so I created a bug here. 

### Repro steps

https://github.com/geosebas/flutter_realm_auth

Just add your realm app id on main.dart, run and try to login (on my app, I already have an user so didn't try to register on this repo)

### Version

0.7.0rc

### What Realm SDK flavor are you using?

MongoDB Atlas (i.e. Sync, auth, functions)

### What type of application is this?

Flutter Application

### Client OS and version

Android 7.0

**Comment by desistefanova** [comment]
Hi @geosebas,
This error is usually returned if your device has no connection to Atlas services.
Are you sure you have an internet connection on the devices you are testing with?

**Comment by geosebas** [comment]
Hi @desistefanova, 
That's one of the first I checked but I'm connected to internet on the device and the permissions have been added to android manifest so it should be ok. 
The only thing that seems to have changed is the android version, otherwise it's the same code, same permissions.

**Comment by nirinchev** [comment]
The issue may be related to the fact older android versions don't trust the LetsEncrypt certificate being used on cloud. If that's the case, you may need to provide a custom http client when constructing the `AppConfiguration` and configure it to trust the certificate used on Cloud.

**Comment by geosebas** [comment]
Hi @nirinchev, 

Thanks it's resolved now ! 
With this clue I found this : https://stackoverflow.com/questions/69511057/flutter-on-android-7-certificate-verify-failed-with-letsencrypt-ssl-cert-after-s
IMHO, it should either be added in your documentation or directly implemented in your code. Or at least provide a better explanation when throwing the error. 
Again, thanks a lot !

**Comment by blagoev** [comment]
Glad we were able to help. Closing this now.
