### ISSUE TITLE
Support environments for Realm

### ISSUE THREAD

**Issue by Navil** [realm/realm-dart#1031]
### Description

Maybe this feature already exists and I just did not find it.

I am using a Development and Production environment (two different Realm+Atlas project).
However, I did not find a way to define the AppId in Realm code, so I can choose what Realm I want to sync with.

How does the library know, where it should connect anyways?

### How important is this improvement for you?

Would be a major improvement

**Comment by Navil** [comment]
I am sorry, I found it myself. It is in the AppConfiguration.

**Comment by nirinchev** [comment]
When you create an `AppConfiguration` instance, you need to give it an app Id: https://github.com/realm/realm-dart/blob/eac42b6f29acec0b2125734a65b14ab1ebe8ab0c/lib/src/app.dart#L90-L91. So you can do something like:

```dart
late AppConfiguration config;
if (Environment.isProduction) {
  config = AppConfiguration(Environment.productionAppId);
} else {
  config = AppConfiguration(Environment.developmentAppId);
}
```
