### ISSUE TITLE
[Bug]: Accessing object of type T which has been invalidated or deleted

### ISSUE THREAD

**Issue by geosebas** [realm/realm-dart#1034]
### What happened?

Hi, 

Just got something that look like a bug but that may be a misuse of the sdk on my side. 

So to give some context, sometimes, during the dev process, I just got this error without any warning. I'm not doing anything, and then suddenly the app crash. It didn't happen many times, something like 4 or 5 times on the last two weeks, but the app should go in production by the end of the month and if I can avoid app crashed I will be happy. 

The only thing that I can think of is that I keep a 'Player' object alive for too long. 
Currently when my user login or when the app start, I will request realm to get this object and will keep it inside a singleton created with the locator package. 

Unfortunately, I didn't manage to find any information about the lifecycle of realm's objects, so I'm not even sure that the problem is on my side, and so that why I created this bug here. 

If the problem came from me, how can I know when a realm object will be invalidated ?  

### Repro steps

I cannot reproduce with certitude

### Version

3.8.8

### What Realm SDK flavor are you using?

MongoDB Atlas (i.e. Sync, auth, functions)

### What type of application is this?

Flutter Application

### Client OS and version

0.8.0RC

### Stacktrace of the exception/crash you're getting

```shell
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following RealmException was thrown building StreamBuilder<RealmResultsChanges<Match>>(dirty,
state: _StreamBuilderBaseState<RealmResultsChanges<Match>,
AsyncSnapshot<RealmResultsChanges<Match>>>#c6208):
Error getting property Player._id Error: RealmException: Error code: 7 . Message: Accessing object
of type Player which has been invalidated or deleted

The relevant error-causing widget was:
  StreamBuilder<RealmResultsChanges<Match>>
  StreamBuilder:file:///C:/Users/Geoffrey/Documents/Projects/GLD/Padel/padel_app/lib/ui/views/client/reservation/client_reservation_view.dart:107:18

When the exception was thrown, this was the stack:
#0      RealmCoreAccessor.get (package:realm/src/realm_object.dart:188:7)
#1      RealmObjectBase.get (package:realm/src/realm_object.dart:272:29)
#2      Player.id (package:padel_app/core/realms/player.g.dart:108:36)
#3      ClientReservationViewState.build.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:padel_app/ui/views/client/reservation/client_reservation_view.dart:129:116)
#4      ListMixin.any (dart:collection/list.dart:149:15)
#5      ClientReservationViewState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:padel_app/ui/views/client/reservation/client_reservation_view.dart:129:60)
#6      WhereIterator.moveNext (dart:_internal/iterable.dart:439:13)
#7      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#8      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#9      new List.of (dart:core-patch/array_patch.dart:51:28)
#10     Iterable.toList (dart:core/iterable.dart:470:12)
#11     ClientReservationViewState.build.<anonymous closure>.<anonymous closure> (package:padel_app/ui/views/client/reservation/client_reservation_view.dart:160:24)
#12     StreamBuilder.build (package:flutter/src/widgets/async.dart:444:81)
#13     _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:124:48)
#14     StatefulElement.build (package:flutter/src/widgets/framework.dart:4992:27)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878:15)
#16     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#18     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#19     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#20     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#21     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#22     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#23     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#24     _invoke (dart:ui/hooks.dart:148:13)
#25     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#26     _drawFrame (dart:ui/hooks.dart:115:31)
```

**Comment by blagoev** [comment]
Hi, 

this error means that the object might have been deleted already and is not present in the Realm any more. Or the `Realm` instance  this object was created from got closed. You should check your app code if the object is not being deleted somewhere or if the Realm instance is kept alive while the app is running or at least until you are done working with the `Player` instance.

cheers.

**Comment by geosebas** [comment]
Hi @blagoev, 

My `Player` is still up in my database on atlas, so I it should not have been removed from the local realm I think. 
The realm is currently closed only when my user logout, so I don't think it should come from there too. 

Can a RealmObject be invalidated for any other reasons ?

**Comment by blagoev** [comment]
No these are the cases where an object can become invalidated. 

Hot reload might be playing a role here. I would suggest you check if you are not releasing the `Realm` instance and recreating a new one while keeping the `Player` object alive from the first instance.
Hot restart shouldn't be causing this as it restarts the application.

I can't think of any other reason why it would be invalidated. So I suggest you do some debugging looking for one of the cases mentioned above.

**Comment by nirinchev** [comment]
Is it possible that you don't have an active subscription that covers the object? In that case, the server would send an ERASE instruction telling the local database to delete the object, even though it exists in Atlas.

**Comment by geosebas** [comment]
It's weird, because the last time I got this error, I was doing nothing. I mean I just got an update from the stream, StreamBuilder rebuild a view, and then got error during rebuild.

When trying to access my realm, I got this check. 
```
  Future<Realm> get realm async {
    if (_realm != null && _app.currentUser != null && _realm!.syncSession.user.id != _app.currentUser!.id) {
      _realm!.close();
    }
    if (_realm == null || _realm!.isClosed) {
      return initRealm();
    }
    return _realm!;
  }
```
But without a logout, the user id should be same and not cause the realm to close I think ? 
I currently only call `realm.close()` in the code before and when my user logout. 

> Is it possible that you don't have an active subscription that covers the object? In that case, the server would send an ERASE instruction telling the local database to delete the object, even though it exists in Atlas.

It could be but I only change the subscriptions set when I create/open the realm, and that would mean the realm has been closed in this case. (the subscriptions are updated inside the `initRealm()` function call from the code before)

**Comment by nirinchev** [comment]
When you get that error though, is the object available locally in the Realm file? You can check that by opening the `.realm` file using [Realm Studio](https://github.com/realm/realm-studio/releases/tag/v12.0.0). If you're not sure where the file is located, you can find it by printing `_realm.config.path`. If the player object is not there anymore, that would indeed point to something causing it to be deleted - either a change coming in from the server or something that happens locally.

**Comment by geosebas** [comment]
I will check next time I get the error. But I don't know when it will happen ^^

**Comment by geosebas** [comment]
Ok I just got this error again, but from another view. 

I checked the realm file and I got my object inside.

I was thinking, will a client reset after an error invalidate the realm's object ? 
I left the default handler, didn't have time to work on this so far... And sometimes I get this error when I use hot reload but it may not be related 
```
I/flutter (19897): [ERROR] Realm: Reading failed: End of input
I/flutter (19897): [INFO] Realm: Connection[1]: Connection closed due to error
I/flutter (19897): [ERROR] Realm: GeneralSyncError message: End of input category: SyncErrorCategory.unknown code: 1
I/flutter (19897): [INFO] Realm: Connected to endpoint '52.16.113.157:443' (from '10.0.2.16:45958')
I/flutter (19897): [INFO] Realm: Verifying server SSL certificate using 155 root certificates
I/flutter (19897): [ERROR] Realm: Websocket: Expected HTTP response 101 Switching Protocols, but received:
I/flutter (19897): HTTP/1.1 401 Unauthorized
I/flutter (19897): cache-control: no-cache, no-store, must-revalidate
I/flutter (19897): connection: close
I/flutter (19897): content-length: 212
I/flutter (19897): content-type: application/json
I/flutter (19897): date: Mon, 14 Nov 2022 19:48:29 GMT
I/flutter (19897): server: envoy
I/flutter (19897): strict-transport-security: max-age=86400; includeSubdomains;
I/flutter (19897): vary: Origin
I/flutter (19897): x-appservices-request-id: 63729b8de1344ec1ab9dc21e
I/flutter (19897): x-envoy-max-retries: 0
I/flutter (19897): x-frame-options: DENY
I/flutter (19897):
I/flutter (19897): [INFO] Realm: Connection[1]: Connection closed due to error
I/flutter (19897): [INFO] Realm: Connected to endpoint '52.16.113.157:443' (from '10.0.2.16:45962')
I/flutter (19897): [INFO] Realm: Verifying server SSL certificate using 155 root certificates
I/flutter (19897): [ERROR] Realm: Reading failed: End of input
I/flutter (19897): [INFO] Realm: Connection[1]: Connection closed due to error
I/flutter (19897): [ERROR] Realm: GeneralSyncError message: End of input category: SyncErrorCategory.unknown code: 1
I/flutter (19897): [INFO] Realm: Connected to endpoint '52.16.113.157:443' (from '10.0.2.16:45964')
I/flutter (19897): [INFO] Realm: Verifying server SSL certificate using 155 root certificates
I/flutter (19897): [ERROR] Realm: Websocket: Expected HTTP response 101 Switching Protocols, but received:
I/flutter (19897): HTTP/1.1 401 Unauthorized
I/flutter (19897): cache-control: no-cache, no-store, must-revalidate
I/flutter (19897): connection: close
I/flutter (19897): content-length: 212
I/flutter (19897): content-type: application/json
I/flutter (19897): date: Mon, 14 Nov 2022 22:05:10 GMT
I/flutter (19897): server: envoy
I/flutter (19897): strict-transport-security: max-age=86400; includeSubdomains;
I/flutter (19897): vary: Origin
I/flutter (19897): x-appservices-request-id: 6372bb96fe350762837d727c
I/flutter (19897): x-envoy-max-retries: 0
I/flutter (19897): x-frame-options: DENY
I/flutter (19897):
I/flutter (19897): [INFO] Realm: Connection[1]: Connection closed due to error
I/flutter (19897): [INFO] Realm: Connected to endpoint '52.16.113.157:443' (from '10.0.2.16:45968')
I/flutter (19897): [INFO] Realm: Verifying server SSL certificate using 155 root certificates

Performing hot reload...       
```

**Comment by nirinchev** [comment]
These seem to be transient errors and not indicating a client reset. Are you by any chance editing this object outside of Realm? For example via Compass/web UI?

**Comment by geosebas** [comment]
> These seem to be transient errors and not indicating a client reset. Are you by any chance editing this object outside of Realm? For example via Compass/web UI?

I didn't. 

It may be related to some problem caused by the hot reload function, so I installed the app on my phone yesterday and no crash so far. 

I have no other idea ^^

**Comment by bmunkholm** [comment]
We will then close this and if you see it again please ask us to reopen.

**Comment by mkbsugita** [comment]
It closed but I have question.

@geosebas

I happened
Did you access static variable?
Some times it happened to me.

```
Error: Cannot access realm that has been closed
```

**Comment by geosebas** [comment]
Hello @mkbsugita , 

Your error is a bit different from mine. You're trying to access a closed realm, where I tried to access to realmobject from a closed realm.

I don't know if it's the best, but to access my realm, I use an async getter inside a singleton. 

Here a bit of my code : 
```
class RealmService {
  late final String _appId;
  late final AppConfiguration _appConfig;
  late final App _app;
  late final String _accountId;
  Realm? _realm;
  String? path;

  App get app => _app;
  String get accountId => _accountId;

  Future<Realm> get realm async {
    if (_realm == null || _realm!.isClosed) {
      debugPrint('Init realm');
      return initRealm();
    }
    if (_realm != null && _app.currentUser != null && _realm!.syncSession.user.id != _app.currentUser!.id) {
      debugPrint('Bad realm/app user');
      _realm!.close();
    }
    if (_realm != null && _app.currentUser == null) {
      debugPrint('App user null');
      _realm!.close();
      throw Exception('Trying to open realm without logged user');
    }
    return _realm?.isClosed ?? true ? await initRealm() : _realm!;
  }
}
```

The `initRealm()` method open a realm and update subscriptions.

Hope it helps you :)

**Comment by mkbsugita** [comment]
@geosebas

Thank you for replying.

I assigned static variable, and I access 

```
static Use? loginedUser;
```

And crashed.

I create instance like this. 
```
final config = realm.Configuration.local(
  [
    Profile.schema,
  ],
  schemaVersion: 14,
);

realm.Realm(config);
```

And assign static variable `shareRealm` 

```
static late realm.Realm? shareRealm;
```

Your great class reopen realm like this? right?

```
RealmService().realm;
```

I guess Realm closes when Page moving.
I will try like this before `Navigator.pushNamed`

```
shareRealm = RealmService().realm;
```

But the way, I found my realm plugin version is

```
`realm: ^0.4.0+beta`
```

**Comment by mkbsugita** [comment]
```
Error getting property [SchemeName.oropartyname] Error: RealmException: Error code: 7 . Message: Accessing object of type [SchemeName] which has been invalidated or deleted
```

**Comment by geosebas** [comment]
Hello @mkbsugita,

First of all, I think you should update to the last version, 1.0.2 if I remember well. 
Doc from here is up to date with the latest version : https://www.mongodb.com/docs/realm/sdk/flutter/
It will help you on how to manage the realm. 

Realm will not close by itself if you're navigating in your app. You're doing something wrong somewhere I think. But without a code sample I cannot help you. 

Why do you need static method/variable for your case ? 
Do you know about state management  in Flutter ? 
They have great doc here : https://docs.flutter.dev/development/data-and-backend/state-mgmt/intro
Myself, I love DI (I came from a C# background), so I use GetIt.
https://docs.flutter.dev/development/data-and-backend/state-mgmt/options#getit

If you're still having your bug, you should create another issue here, with a code sample to reproduce if you can :)
And if you have other questions about how to design, or need some help, mongodb got a great forum, and we still have Stackoverflow. 
I don't think a closed github issue is the good place to discuss, if other got the same problem, the information may be lost ! 
If you do create a post on the forum or stackoverflow, send me a link and I will help you there if I can :)
