### ISSUE TITLE
[Bug]: Embedded object in root model

### ISSUE THREAD

**Issue by RedFox64** [realm/realm-dart#1038]
### What happened?

It is not possible to use an Embedded object in a model.

### Repro steps

1) Create model with embedded objects.
2) Create configuration with schema of root model.
3) Run code.

### Version

Flutter 3.3.8, Realm 0.8.0+rc

### What Realm SDK flavor are you using?

MongoDB Atlas (i.e. Sync, auth, functions)

### What type of application is this?

Flutter Application

### Client OS and version

Android 11

### Code snippets

![Screenshot 2022-11-15 at 11 54 17](https://user-images.githubusercontent.com/22937093/201902597-35b1b3e3-8695-42da-85e3-5b2486e48d14.png)

Configuration:
`final flxConfig = Configuration.flexibleSync(user,[Topic.schema]));`

### Stacktrace of the exception/crash you're getting

```shell
Exception has occurred.
RealmException (RealmException: Error opening realm at path /data/user/0/com.app.test/app_flutter/mongodb/db_topics.realm. Error code: 18 . Message: Schema validation failed due to the following errors:
- Property 'Topic.logo' of type 'object' has unknown object type 'TopicLogo'
- Property 'Topic.attachment' of type 'array' has unknown object type 'Attachment')
```

**Comment by nielsenko** [comment]
Did you remember to add `TopicLogo.schema` and `Attachment.schema` when creating your configuration?

**Comment by RedFox64** [comment]
> Did you remember to add `TopicLogo.schema` and `Attachment.schema` when creating your configuration?

When I to add `TopicLogo.schema` and `Attachment.schema` in configuration. 
I am getting an error on the Mongo DB Atlas side. You can see below.

`missing properties in object schema (ProtocolErrorCode=225)

Logs:

[
  "Received client-originated schema change instruction to apply in Development Mode",
  "Adding a new primitive field to table in application schema",
  "Existing Table Name: TopicLogo",
  "New Field Name: id",
  "New Field Type: string",
  "New Field Collection Type: None/Single",
  "New Field Is Required: true"
]`

My topic schema looks like this:
`{
  "title": "topic",
  "required": [
    "_id",
    "name",
    "timestampCreated",
    "timestampLastUpdated",
    "ownerIds",
    "userIdCreated"
  ],
  "properties": {
    "_id": {
      "bsonType": "objectId"
    },
    "activityTypes": {
      "bsonType": "array",
      "items": {
        "bsonType": "objectId"
      }
    },
    "attachment": {
      "bsonType": "array",
      "items": {
        "bsonType": "object",
        "properties": {
          "authorId": {
            "bsonType": "string"
          },
          "fileExtension": {
            "bsonType": "string"
          },
          "id": {
            "bsonType": "string"
          },
          "link": {
            "bsonType": "string"
          },
          "name": {
            "bsonType": "string"
          }
        }
      }
    },
    "description": {
      "bsonType": "string"
    },
    "logo": {
      "bsonType": "object",
      "properties": {
        "id": {
          "bsonType": "string"
        },
        "link": {
          "bsonType": "string"
        }
      }
    },
    "name": {
      "bsonType": "string"
    },
    "ownerIds": {
      "bsonType": "array",
      "items": {
        "bsonType": "string"
      }
    },
    "priorities": {
      "bsonType": "array",
      "items": {
        "bsonType": "objectId"
      }
    },
    "statuses": {
      "bsonType": "array",
      "items": {
        "bsonType": "objectId"
      }
    },
    "timestampCreated": {
      "bsonType": "timestamp"
    },
    "timestampLastUpdated": {
      "bsonType": "timestamp"
    }
  }
}`

Topic schema has fields:
1) logo (Object)
2) attachment (Array Object)

What am I doing wrong?
Do I need to create separate collections for TopicLogo and Attachment?

**Comment by RedFox64** [comment]
Sorry, I accidentally closed it. It is not solved.

**Comment by nielsenko** [comment]
@RedFox64 Sorry, this fell between two chairs.

The issue is that your server side schema doesn't match your client side models. Fx. `Attachment.id` is a non-nullable `String` hence the server side schema would need to make it `required`. Same goes for all the other properties on `Attachment`
