### ISSUE TITLE
[Bug]: Plain insert doesn't work properly with created object reference

### ISSUE THREAD

**Issue by ebelevics** [realm/realm-dart#1045]
### What happened?

So I have to reference a user to my task object. The user is predefined locally and stored in DB. The task table is empty. But when I convert those objects from app to realm objects and do insert I received error on _add(update:false)._

For some reason I didn't encounter this problem before in Unity by using Realm .NET implementation. I did create local object with uuid, and `Realm.GetInstance(config).Add(local)`, but in Flutter that not the case. 

And I have noticed in Flutter that the difference between **realm** created object and **manually** created object, is that realm created object has `_realm` and `_handle` values set while manual created object has `_realm` and `_handle` values as null.
So maybe this might be indication.

I would not sound alarm if .NET had same behaviour but it did.

As a workaround it just seem I have to get realm created object and insert in local object. update:true I don't want to do because I'm creating new task object that will be inserted in DB, but has user ref that is present in DB.

### Repro steps

```dart
var local1 = Local("0");
var local2 = Local("1");

var ref1 = realm.all<Ref>().first;
var ref2 = Ref("0", "value");

local1.ref = ref1;
realm.write(() => realm.add(local1)); //ALL WORKS FINE

local2.ref = ref2;
realm.write(() => realm.add(local2)); //ERROR 
//Unhandled Exception: RealmException: Error setting property Local.ref Error: RealmException: Error code: 33 . 
//Message: Object with this primary key already exists
```

### Version

Flutter 3.3.7  Dart 2.18.4

### What Realm SDK flavor are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

Android 11

**Comment by nielsenko** [comment]
Could you share the definition of `_Local` and `_Ref` (or `$Local` and `$Ref` depending on how you named the realm models)?

It looks as if the primary key of `Local` is duplicated.

**Comment by nielsenko** [comment]
In your example `ref2` is not added to the realm until:
```dart
realm.write(() => realm.add(local2)); //ERROR 
```
I cannot tell what the primary key of `Ref` is from your snippet, but apparently there already exists a `Ref` with the same PK in the realm (it may or may not be `ref1`). You can use `update: true` flag on the `add` call, which will update that object, but I suspect you might have a bug.

**Comment by nielsenko** [comment]
Unmanaged object do not have a realm (`_realm`), or a native handle (`_handle`), that is as expected.
Wrt. .NET I would expect the exact same behaviour here, but again I need a bit more info, especially regarding the schema.

**Comment by nielsenko** [comment]
Are you sure you didn't mean:
```dart
final ref2 = realm.find<Ref>("0");
```
instead of
```dart
var ref2 = Ref("0", "value");
```
The former will find any existing `Ref` with PK `"0"` (assuming the PK is `String` in your model), while the latter will create a new `Ref` with PK `"0"` that may later conflict with an already existing object.

**Comment by ebelevics** [comment]
I'll later this day provide full .Net and Dart example side by side

**Comment by nielsenko** [comment]
@ebelevics Good - but the realm model for `Ref` would go a long way.

**Comment by ebelevics** [comment]
```cs
public class Local : RealmObject
{
    [PrimaryKey]
    public String Id { get; set; }
    public Ref Reference { get; set; }
}


public class Ref : RealmObject
{
    [PrimaryKey]
    public String Id { get; set; }
    public String Value { get; set; }
}


var realm = Realm.GetInstance();

var reference = new Ref { Id = "0", Value = "value" };

realm.Write(() => realm.Add(reference, true));

var ref1 = realm.All<Ref>().ToList().First();
var ref2 = new Ref { Id = "0", Value = "value" };

var local1 = new Local { Id = "0", Reference = ref1 };
var local2 = new Local { Id = "1", Reference = ref2 };

realm.Write(() => realm.Add(local1)); // Works
realm.Write(() => realm.Add(local2)); // RealmDuplicatePrimaryKeyValueException: A Ref object already exists with primary key property Id == '"0"'
```

Yeah, it seems that .NET Realm behaviour was exactly the same as dart with same error. It appeared that I used first approach where I took Ref RealmObject from DB and then put it in new Local RealmObject, that's why realm.Add() did work without update:true. 

Thank you anyway!
