### ISSUE TITLE
Renaming a class during a migration

### ISSUE THREAD

**Issue by tanukijs** [realm/realm-dart#1053]
### Description

Hello 👋 

I was upgrading a project and i need to create a migration while our models names changed but as i see there is no "easy-way" to handle this changement without losing the data.

In this PR https://github.com/realm/realm-java/pull/1239 from Realm Java, we see that they have a `renameClass` method that i think would do what i want: renaming the old table name to the new table name without losing the data inside.

There is a way to do it currently ? If not, features listed in the above PR would be useful.

**Comment by blagoev** [comment]
Hi,
 You can use [MapTo](https://github.com/realm/realm-dart/blob/master/common/lib/src/realm_common_base.dart#L66) attribute on the class to map the new class name to an old class name. 
Something like this model
```dart
//Old model
@RealmModel()
class _Student {
  late String name;
}

//New model
@RealmModel()
@MapTo('Student')
class _StudentV1 {
  late String name;
}
```
cheers.

**Comment by tanukijs** [comment]
It's my fault, I didn't look further. Impressed again, thank you.
