### ISSUE TITLE
[Bug]: No items in the document field that are linked via relationship.

### ISSUE THREAD

**Issue by RedFox64** [realm/realm-dart#1056]
### What happened?

No items in the document field that are in another collection and are linked via relationship.

I linked the collections through  the relationships:
```json
{
  "noteIds": {
    "ref": "#/relationship/mongodb-atlas/todo/Note",
    "foreignKey": "_id",
    "isList": true
  },
  "ownerIds": {
    "ref": "#/relationship/mongodb-atlas/todo/UserProfile",
    "foreignKey": "_id",
    "isList": true
  }
}
```
Before that, I was getting a list of ObjectId. 
Now I get an empty list in the fields:
noteIds
ownerIds
![Screenshot 2022-12-06 at 16 22 09](https://user-images.githubusercontent.com/22937093/205952252-66c48b6f-f9f3-4d2f-900f-07b969fc76f1.png)

Items of collections:
![Screenshot 2022-12-06 at 16 19 45](https://user-images.githubusercontent.com/22937093/205951813-64a308e5-c986-41ce-9e1c-d56d3c3cde28.png)
![Screenshot 2022-12-06 at 16 19 38](https://user-images.githubusercontent.com/22937093/205951828-e6a85883-5976-461a-9623-8ef73c89ea10.png)
![Screenshot 2022-12-06 at 16 19 24](https://user-images.githubusercontent.com/22937093/205951831-18811e81-76c4-4270-a02b-2d52a057f645.png)

### Repro steps

Add relationship

### Version

Flutter 3.3.9, Realm 0.8.0+rc

### What Realm SDK flavor are you using?

MongoDB Atlas (i.e. Sync, auth, functions)

### What type of application is this?

Flutter Application

### Client OS and version

Android 11

### Code snippets

```dart
@RealmModel()
class _Topic {
  @PrimaryKey()
  @MapTo('_id')
  late ObjectId id;
  @MapTo('name')
  late String name;
  @MapTo('userIdCreated')
  late ObjectId userIDCreated;
  @MapTo('description')
  late String? description;
  @MapTo('logo')
  late _TopicLogo? logo;
  @MapTo('attachment')
  late List<$Attachment> attachments;
  @MapTo('ownerIds')
  late List<$UserProfile> ownerIDs;
  @MapTo('priorities')
  late List<ObjectId> priorities;
  @MapTo('statuses')
  late List<ObjectId> statuses;
  @MapTo('activityTypes')
  late List<ObjectId> activityTypes;
  @MapTo('timestampCreated')
  late int timestampCreated;
  @MapTo('timestampLastUpdated')
  late int timestampLastUpdated;
  @MapTo('noteIds')
  late List<$Note> noteIDs;
}
```

**Comment by nielsenko** [comment]
How does your subscriptions look?

**Comment by RedFox64** [comment]
> How does your subscriptions look?

What do you mean? Subscriptions for changes?

**Comment by nielsenko** [comment]
When you setup your flexible sync subscriptions, ie. something like:
```dart
final realm = await Realm.open(config);
realm.subscriptions.update((mutableSubscriptions) {
   mutableSubscriptions.add(realm.all<Thingy>());
});
```
How does that code look?

**Comment by RedFox64** [comment]
> When you setup your flexible sync subscriptions, ie. something like:
> 
> ```dart
> final realm = await Realm.open(config);
> realm.subscriptions.update((mutableSubscriptions) {
>    mutableSubscriptions.add(realm.all<Thingy>()); // <-- this block, how does it look in your code?
> });
> ```
> 
> How does that code look?

`    realm = Realm(flxConfig);

    RealmResults<dynamic> queryRes = _generateQuery(query: _buildQuery(query, sort), queryValues: queryValues);

    realm.subscriptions.update((mutableSubscriptions) {
      mutableSubscriptions.add(
        queryRes as RealmResults<RealmObject>, /*update: true*/
      );
    });`

You can see I use subscriptions.

**Comment by RedFox64** [comment]
> Also, could you share the two realm models `$Note` and `$UserProfile`?

`@RealmModel()
class $Note {
  @PrimaryKey()
  @MapTo('_id')
  late ObjectId id;
  @MapTo('name')
  late String name;
  @MapTo('userIdCreated')
  late ObjectId userIDCreated;
  @MapTo('userIdAssigned')
  late ObjectId userIDAssigned;
  @MapTo('description')
  late String? description;
  @MapTo('attachment')
  late List<$Attachment> attachments;
  @MapTo('statusId')
  late ObjectId? statusID;
  @MapTo('priorityId')
  late ObjectId? priorityID;
  @MapTo('activityTypeId')
  late ObjectId? activityTypeID;
  @MapTo('timestampCreated')
  late int timestampCreated;
  @MapTo('timestampLastUpdated')
  late int timestampLastUpdated;
  @MapTo('topicId')
  late ObjectId topicID;
  @Ignored()
  bool isOpenPreview = false;
}

@RealmModel()
class $UserProfile {
  @PrimaryKey()
  @MapTo('_id')
  late ObjectId id;
  @MapTo('userId')
  late String userId;
  @MapTo('firstName')
  late String firstName;
  @MapTo('lastName')
  late String? lastName;
  @MapTo('imageProfile')
  late $ImageProfile? imageProfile;
  @MapTo('email')
  late String? email;
  @MapTo('contactList')
  late List<ObjectId> contactList;
  @MapTo('authParam')
  late $AuthParams? authParam;
  @MapTo('nickname')
  late String? nickname;
  @MapTo('timestampCreated')
  late int timestampCreated;
  @MapTo('timestampLastUpdated')
  late int timestampLastUpdated;
}`

**Comment by nielsenko** [comment]
@RedFox64 You need to ensure that you add subscriptions for `Note` and `UserProfile` as well as `Topic` otherwise the objects will not be pulled from the server, nor will they be allowed stay in the client-side realm for long, if created client side.

I cannot see from the provided code snippets what is going on in `_generateQuery`, but I know any query will only return one type of realm object, so I suspect that your are missing some subscriptions for the types it depends on.

Fx. Given models:
```dart
@RealmModel()
class _Parent {
  @PrimaryKey()
  @MapTo('_id')
  late Uuid id;
  late List<_Child> children;
}

@RealmModel()
class _Child {
  @PrimaryKey()
  @MapTo('_id')
  late Uuid id;
}
```
Subscribing for:
```dart
final realm = await Realm.open(config);
  realm.subscriptions.update((mutableSubscriptions) {
    mutableSubscriptions.add(realm.all<Parent>());
  });
```
will not pull in the `Child` objects that `children` contains. You need to add a subscription that covers the children as well.

**Comment by nielsenko** [comment]
Have you considered if `$Note` could be marked as embedded? Embedded objects are automatically pulled from the server together with whatever aggregate object they belong to.

**Comment by RedFox64** [comment]
> @RedFox64 You need to ensure that you add subscriptions for `Note` and `UserProfile` as well as `Topic` otherwise the objects will not be pulled from the server, nor will they be allowed stay in the client-side realm for long, if created client side.
> 
> I cannot see from the provided code snippets what is going on in `_generateQuery`, but I know any query will only return one type of realm object, so I suspect that your are missing some subscriptions for the types it depends on.
> 
> Fx. Given models:
> 
> ```dart
> @RealmModel()
> class _Parent {
>   @PrimaryKey()
>   @MapTo('_id')
>   late Uuid id;
>   late List<_Child> children;
> }
> 
> @RealmModel()
> class _Child {
>   @PrimaryKey()
>   @MapTo('_id')
>   late Uuid id;
> }
> ```
> 
> Subscribing for:
> 
> ```dart
> final realm = await Realm.open(config);
>   realm.subscriptions.update((mutableSubscriptions) {
>     mutableSubscriptions.add(realm.all<Parent>());
>   });
> ```
> 
> will not pull in the `Child` objects that `children` contains. You need to add a subscription that covers the children as well.

I have changed code. You can see below:
`    realm.subscriptions.update((mutableSubscriptions) {
      // mutableSubscriptions.add(
      //   queryRes as RealmResults<RealmObject>, /*update: true*/
      // );

      for (var i = 0; i < schema.length; i++) {
        switch (schema[i].type) {
          case Topic:
            mutableSubscriptions.add(
              realm.all<Topic>(),
            );
            break;
          case Note:
            mutableSubscriptions.add(
              realm.all<Note>(),
            );
            break;
          case NoteActivityType:
            mutableSubscriptions.add(
              realm.all<NoteActivityType>(),
            );
            break;
          case NotePriority:
            mutableSubscriptions.add(
              realm.all<NotePriority>(),
            );
            break;
          case NoteStatus:
            mutableSubscriptions.add(
              realm.all<NoteStatus>(),
            );

            break;
          case UserProfile:
            mutableSubscriptions.add(
              realm.all<UserProfile>(),
            );

            break;
          default:
            break;
        }
      }
    });`

Now it is work =)
Thank you!

**Comment by RedFox64** [comment]
How do I add a child element to a parent element? 
In the database, the parent has a list of ObjectId.
In the scheme in the application, we have a list of items from another collection. You can see below.
`@MapTo('noteIds')
  late List<$Note> noteIDs;`

**Comment by nielsenko** [comment]
If I understand your question correctly, and assuming `topic` is the `Topic` you want to add a `Note` to, then simply do:
```dart
realm.write(() {
  final note = Note(...);
  topic.noteIDs.add(note); 
});
```

**Comment by nielsenko** [comment]
BTW, be a bit careful with those
```dart
mutableSubscriptions.add(
  realm.all<X>(),
);
```
Remember that they will pull in all objects of type `X` that you are allowed to see, not just those that you _need_. Depending on how roles and permissions are setup on the backend, that may be a lot of data.

If possible restrict the query passed. Also consider if embedded objects are an option as these don't require explicit subscriptions, since they are embedded in the parent.

In general two things decide what objects are (/will be) available client side:

1. The backend decides what objects a given user is allowed to see. Let's call this the _permissible view_
2. The client subscriptions decide what the user wants to see. Let's call this the _requested view_

The _target view_ of objects are the intersection of these two sets.

Depending  on network connectivity, latency etc. the actual objects in the client side realm may differ from the _target view_ at any given time, but the database will work to align them.

It can be a bit surprising that this pertains to locally created objects as well, ie. that Realm will remove locally created objects that are outside the _target view_  as well. They may even be destroyed, if outside the _permissible view_, by compensating writes.

You cannot tell, if an object is missing from a list, or an object reference is null, due to the fact that the object is outside the target view, or don't exits at all.

**Comment by nielsenko** [comment]
You should not use the realm model classes directly in your own code. Instead you should use the generated classes, ie use `UserProfile` not `$UserProfile`.

**Comment by RedFox64** [comment]
> You should not use the realm model classes directly in your own code. Instead you should use the generated classes, ie use `UserProfile` not `$UserProfile`.
If I use UserProfile. I also get the same error

**Comment by nielsenko** [comment]
I need to see more code to understand why it is you are adding an object of the wrong type to the list. Could you grant me access to your project?

**Comment by RedFox64** [comment]
> I need to see more code to understand why it is you are adding an object of the wrong type to the list. Could you grant me access to your project?
> 
> Or even better, if you can make a sample that reproduces this problem..

I have prepared a test project. This project has the same error.
Project: [https://github.com/RedFox64/bug-1056](url)

**Comment by nielsenko** [comment]
I'll stop debugging this, since you are updating the schema on the backend. But in general I would suggest to create just one config, and use it to open all realm instances. And consider just sharing a single realm instance.
