### ISSUE TITLE
[Bug]: Crash while m1 run simulator with "realm-dart-main/flutter/realm_flutter/example" example

### ISSUE THREAD

**Issue by felix0324324** [realm/realm-dart#1075]
I have no changes on coding just compile with the latest code version.
But it got an Exception and I have no idea why

`ArgumentError (Invalid argument(s): Failed to load dynamic library 'realm_dart': dlopen(realm_dart, 0x0001): tried: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRootrealm_dart' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/realm_dart' (errno=2), '/usr/lib/swift/realm_dart' (errno=2, not in dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/realm_dart' (errno=2), '/usr/lib/swift/realm_dart' (errno=2, not in dyld cache), '/Users/alvis/Library/Developer/CoreSimulator/Devices/3C0D9DC7-4C58-444F-B50D-662A3C4E3462/data/Containers/Bundle/Application/B2A1468C-B5B9-48B7-86C2-A4C4B7A5D47E/Runner.app/Frameworks/realm_dart' (errno=2), '/Users/alvis/Library/Developer/CoreSimulator/Devices/3C0D9DC7-4C58-444F-B50D-662A3C4E3462/data/Containers/Bundle/Application/B2A1468C-B5B9-48B7-86C2-A4C4B7A5D47E/Runner.app/Frameworks/realm_dart' (errno=2), '/Users/alvis/Library/Developer/CoreSimulator/Devices/3C0D9DC7-4C58-444F-B50D-662A3C4E3462/data/Containers/Bundle/Application/B2A1468C-B5B9-48B7-86C2-A4C4B7A5D47E/Runner.app/Frameworks/realm_dart' (errno=2), '/usr/lib/realm_dart' (errno=2, not in dyld cache), 'realm_dart' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/realm_dart' (errno=2))`

<img width="1602" alt="螢幕截圖 2022-12-20 上午10 20 41" src="https://user-images.githubusercontent.com/16462532/208567523-5a0a9ad3-2971-4cf7-abf8-c0a389cddd4a.png">
<img width="697" alt="螢幕截圖 2022-12-20 上午10 21 47" src="https://user-images.githubusercontent.com/16462532/208567543-e1524211-1783-4542-84b3-b170149d707f.png">
<img width="697" alt="螢幕截圖 2022-12-20 上午10 22 11" src="https://user-images.githubusercontent.com/16462532/208567548-c252fb99-ee60-452e-a81d-27a3a81c22d7.png">

**Simulator Version iPhone 14 Pro, ios 16.2**

### Repro steps

Just compile and do nothing 

### Version

Channel stable, 3.3.9

### What Realm SDK flavor are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

macOS 13.2

**Comment by nielsenko** [comment]
I assume this worked with an earlier version of realm than `0.8.0-rc`? Could you try running `flutter clean` and then `flutter pub cache repair` before you run again?

**Comment by felix0324324** [comment]
> I assume this worked with an earlier version of realm than `0.8.0-rc`? Could you try running `flutter clean` and then `flutter pub cache repair` before you run again?

I had try 0.7.0-rc, Not work
"flutter pub" and "cache repair", Not work
