### ISSUE TITLE
[Bug]: Using schemas that have float data is impossible?

### ISSUE THREAD

**Issue by Quoteme** [realm/realm-dart#1081]
### What happened?

I try to load a realm database into my flutter app on android. I use this code to do achive that:

```
var config = Configuration.local([MyDataType.schema],
      path: "/path/to/my/realm.realm",
      schemaVersion: 4,
    );
```
```
@RealmModel()
class _MyDataType {
  @PrimaryKey()
  late int timestamp;
  late double? temp1;
}
```

But when I load my database i get the following error:

```
RealmException: Error opening realm at path /path/to/my/realm.realm. Error code: 18 . Message: Migration is required due to the following errors
- Property 'MyDataType.temp1' has been changed from 'float' to 'double'.
```

I cannot modify the database. Is there some way to use this float-value in my flutter app? It would also be ok, if I can only read these values. I do not need to write to my database.

### Repro steps

1. Generate a realm database which stores floats
2. try to load it using realm-dart
3. dart does not have a float data type, only int and double
4. realm-dart crashes

### Version

0.8.0+rc

### What Realm SDK flavor are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

Android 11

### Code snippets

```
var config = Configuration.local([MyDataType.schema],
      path: "/path/to/my/realm.realm",
      schemaVersion: 4,
    );
var realm = Realm(config);
```

### Relevant log output

```shell
RealmException: Error opening realm at path /path/to/my/realm.realm. Error code: 18 . Message: Migration is required due to the following errors
- Property 'MyDataType.temp1' has been changed from 'float' to 'double'.
```

**Comment by dotjon0** [comment]
@Quoteme when a `Realm` database schema is changed on a `local only` Realm database you need to usually either:

1. **For simple schema changes;** increment the version number https://www.mongodb.com/docs/realm/sdk/flutter/model-data/update-realm-object-schema/#automatically-update-schema
2. **For more complex schema changes;** a manual migration may be required https://www.mongodb.com/docs/realm/sdk/flutter/model-data/update-realm-object-schema/#manually-migrate-schema

From what you have mentioned, it sounds like option 2 above is probably the path you need to take. Further general information on this topic can also be found at https://www.mongodb.com/docs/realm/sdk/flutter/model-data/update-realm-object-schema/#update-a-realm-object-schema---flutter-sdk

FYI if you ever choose to have a 'synced Realm' (MongoDB Atlas Device Sync https://www.mongodb.com/docs/realm/sdk/flutter/sync/) then the above steps are not needed as the migrations are automatically dealt with https://www.mongodb.com/docs/realm/sdk/flutter/model-data/update-realm-object-schema/#updating-the-schema-of-a-synced-realm

**Comment by hacnguyen1412** [comment]
obviously, realm is very annoying in editing RealmModel. so bad

**Comment by hacnguyen1412** [comment]
before:

@RealmModel()
class _TaskDao {
  String? id;
  String? name;
  String? avatar;
  String? createdAt;
}

after:
@RealmModel()
class _TaskDao {
  @PrimaryKey()
  String? id;
  String? name;
  String? avatar;
  String? createdAt;
}


Although I have increased the schema version or deleted the old table, all I see is error

**Comment by Quoteme** [comment]
if anyone is wondering, the fix to use floats in flutter in realm databases is to use `dart:ffi `and `Float`
