### ISSUE TITLE
[Bug]: Query method with IN predicate returns empty results

### ISSUE THREAD

**Issue by M4UTR0NI1C** [realm/realm-dart#1084]
### What happened?

I try build query with IN predicate but return empty results.

### Repro steps

Build a List String with the values to be filtered.
Pass a List with join(",") to get concatenated values as a single string.
Build a predicate with IN using query method and pass as parameter list

### Version

realm 0.8.0+rc -> flutter  3.3.10

### What Realm SDK flavor are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

Windows 11

### Code snippets

Model:
![image](https://user-images.githubusercontent.com/93393881/209752362-e930f31f-d29b-49d2-b730-b1abab7ba06d.png)
Implementation:
![image](https://user-images.githubusercontent.com/93393881/209752313-fb169dbd-c178-4c32-a833-7ec38408e8f4.png)

Alternative (that works):
![image](https://user-images.githubusercontent.com/93393881/209752509-565eb8d8-f959-43d7-a6c3-dab5c5f90627.png)

**Comment by dotjon0** [comment]
Hi @M4UTR0NI1C , I would try building the query string outside of the realm.query in the implementation example that does not work.

**Comment by nielsenko** [comment]
@M4UTR0NI1C This is related to: https://github.com/realm/realm-dart/issues/755. As you noticed it works if you flatten all arguments into the query.

Actually you only need to flatten the first list argument, so:
```dart
final fullPredicate = 'estatus IN {$inPredicate} AND producto.rol == $0 AND cuenta.historica == $1 SORT(fechaCreacion DESC)';
realm.query(fullPredicate, [userRole, false]);
```
should work as well.

This is a [bug/missing feature](https://github.com/realm/realm-dart/issues/755) in the SDK and will be fixed, it **should** be possbile to write:
```dart
final fullPredicate = 'estatus IN $0 AND producto.rol == $1 AND cuenta.historica == $2 SORT(fechaCreacion DESC)';
realm.query(fullPredicate, [estatus, userRole, false]);
```
but alas we are not quite there yet

**Comment by M4UTR0NI1C** [comment]
@nielsenko thank you for your answer, I proceed to close this issue. Regards.

**Comment by nielsenko** [comment]
I'll keep this open until it is fixed

**Comment by desistefanova** [comment]
Query list arguments and IN-operator are now supported in [Realm SDK 1.4.0](https://pub.dev/packages/realm)
