### ISSUE TITLE
Circle CI Build Error

### ISSUE THREAD

**Issue by hawk0530-mintsoft** [realm/realm-dart#1091]
### What happened?

Circle CI Build Error

HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: certificate has expired(handshake.cc:393))
#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99:46)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142:25)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:911:54)
#3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1040:19)
<asynchronous suspension>
pub finished with exit code 255

FAILURE: Build failed with an exception.

### Repro steps

.

### Version

flutter 3.3.10, dart 2.18.6, devtools 2.15.0

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

mac

**Comment by nirinchev** [comment]
We've discovered that the static.realm.io certificate where the native binaries are being hosted has expired. The team is on it and we hope to have a resolution by the end of the day.

**Comment by geragray** [comment]
Downloading of binaries from static.realm.io has been fixed. Please accept our apologies for the inconvenience.
