### ISSUE TITLE
Upgrade ffi dependency

### ISSUE THREAD

**Issue by brookman** [realm/realm-dart#1095]
### Problem

realm 0.8.0+rc depends on ffi 2.0.1 which makes it incompatible to packages depending on a newer version of ffi.

### Solution

Upgrade the ffi dependency to 1.2.1.

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by nielsenko** [comment]
2.0.1 is the newest version of ffi. 1.2.1 is 8 month old?

**Comment by brookman** [comment]
Oops! I just realized the same. I was somehow reading it as "2.2.1". The issue can be closed.
Sorry about that.
