### ISSUE TITLE
Save an integer value as Int32

### ISSUE THREAD

**Issue by ffeliciodeveloper** [realm/realm-dart#1109]
Good morning / Good afternoon / Good evening everyone.

I'm working with my backend team and we're facing some issues regarding int types.

When registering a value in MongoDB through the backend, the type of the number sent is being done as Int32, but when performing the same flow through our application, the same field is being stored as Int64 (in the schema the field is being configured for the long type).

I've already tried to force the integer type reference as below, but even so the field was registered as Int64, would there be any way to change this reference when saving?

```dart
Rdo toRealm() {
    return Rdo(
      ObjectId.fromHexString(idModel ?? ObjectId().hexString),
      ObjectId.fromHexString(constructionIdModel),
      dateModel,
      statusModel,
      hasWeatherModel,
      hasWorkforceModel,
      hasActivityModel,
      hasOcurrenceModel,
      hasEquipmentModel,
      hasVisitModel,
      hasFileModel,
      code: codeModel != null ? codeModel!.toSigned(32) : null, // <-- line to convert int to Int32
      customerId:
          ObjectId.fromHexString(customerIdModel ?? ObjectId().hexString),
      approvedAt: approvedAtModel?.toRealm(),
      createdAt: createdAtModel?.toRealm(),
      updatedAt: updatedAtModel?.toRealm(),
    );
  }
```

Thank you all and sorry for any errors generated.
It's just that I looked in the documentation, but I didn't find a way to do this operation.

**Comment by nielsenko** [comment]
@ffeliciodeveloper An `int` in the native Dart VM is [64-bit two's complement integer](https://api.flutter.dev/flutter/dart-core/int-class.html). Calling `.toSigned(32)` will still return a 64 bit `int` but only use 32 bit of the width, ie.
```dart
void main() {
  final x = (1 << 32) + (1 << 16);
  print(x.toRadixString(2).padLeft(64, '0'));
  print(x.runtimeType);
  final y = x.toSigned(32);
  print(y.toRadixString(2).padLeft(64, '0'));
  print(y.runtimeType);
  print(x < y);
}
```
outputs:
```
0000000000000000000000000000000100000000000000010000000000000000
int
0000000000000000000000000000000000000000000000010000000000000000
int
false
```
So, no using `.toSigned(32)`, will not change the type of integer, if that is what you are thinking.

Since the schema is already using `long` correctly, I'm not sure I understand your issue?

**Comment by ffeliciodeveloper** [comment]
Good Morning @nielsenko 

Thanks for answering my question!

Sorry for the dumb question, as I'm still new to Flutter development I still get a little lost.

What happens is the following, in the company where I work we are using MongoDb as the main base.
The integration between the frontend and the backend takes place through an api.
When the frontend sends a record to the backend and the object used has an Integer type field, the server registers the information and sets the field type to Int32.

As the application uses MongoDb directly with the Realm lib, when saving or editing the same information, the type is included or changed to Int64 and this is causing problems in the frontend/backend.

Then the doubt arose if I could force it (through the app), so that the information is registered as Int32.

PS.
Forgive me for my English.
I'm still not proficient in the language.

Again, thanks a lot for your help.

**Comment by nirinchev** [comment]
Hey @ffeliciodeveloper, unfortunately, that is not possible. Realm as a database only supports 64-bit integers, so even if you give it a 32-bit value, it'll just store it as a 64-bit and will not persist the original type of the integer. If you know that you'll only ever be storing 32-bit integers, you can update your backend/frontend reading directly from MongoDB to cast down the value it retrieves.

**Comment by ffeliciodeveloper** [comment]
Hi @nirinchev

Thanks for answering my question.

I'll report back to the team that this is Realm's default behavior.

Thanks a lot for the help @nirinchev and @nielsenko
