### ISSUE TITLE
Map model to a different table name

### ISSUE THREAD

**Issue by lhengl** [realm/realm-dart#1115]
### Problem

Currently the models are mapped to a table of the same name on the local Realm as well as on Atlas Device Sync. When working in Domain Driven Design where there are a lot of different models in different layers and different data sources, there is a need to name the models differently to distinguish them. For example, I could have the following models:

- ModelName (this is the domain model)
- ModelNameFirestore
- ModelNameRealm
- ModelNameHive
- ModelNameSql

It would be nice to have an option to map the Realm model to a different table similar to property mapping.

### Solution

Solution: Add a 'mapTo' option to @RealmModel that will map the model to a specific table in the database.

### Alternatives

None

### How important is this improvement for you?

Fairly niche but nice to have anyway

### Feature would mainly be used with

Atlas App Services: Auth or Functions etc

**Comment by desistefanova** [comment]
Hi @lhengl,
As I understand having `MapTo` on class level is the thing that would help you to solve your problem.
You can use the annotation `MapTo`. It is supported on class level and you can use it to specify the table name. You can see the usage [here](https://github.com/realm/realm-dart/blob/a7f13b7409a04012117dad9205503457e8932d7b/test/migration_test.dart#L31).
We have now realized that this is not well described in the API docs. We will fix the documentation.
Thanks!

**Comment by lhengl** [comment]
Thank you @desistefanova, I wasn't aware of this support since the documentation states it is for a member level map. Thanks, tested and working as expected.
