### ISSUE TITLE
Change listeners not triggered after reinstallation in prod

### ISSUE THREAD

**Issue by Navil** [realm/realm-dart#1120]
### What happened?

So I have my application in production already and can sadly not reproduce it locally, but consistently on my production application, so here are my findings:

If I am currently logged in and uninstall the application, the realm is apparently not deleted. Consequently, when I uninstall the application from the Play Store and install it again, I will be logged in to the realm already but will not get any changes. 
This issue can be fixed when I delete the data from the app after reinstalling it. I don't perfectly know what Android does when it uninstalls the application, but my assumption would be, that realm gets removed with it and I need to login again after reinstalling the application.

I left the path undefined (thus default) when creating the realm. Is there a specific location, I should put it to, so that it gets removed with the application? Or in case, this is intended, what do I have to keep in mind to keep using the same realm after initialization?

I sadly have not many logs I can provide as it is on production.  

### Repro steps

- Login into production app from Play Store
- Reinstall the application
- You are logged in, but no callbacks get triggered

### Version

Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19045.2364], locale de-AT

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### What type of application is this?

Flutter Application

### Client OS and version

0.9.0+rc

### Relevant log output

```shell
User is not null
<changeListener not called>
```

**Comment by blagoev** [comment]
Hi, 
We will need to investigate this more. 

As a workaround if you want to delete any existing realm files you could use `Realm.deleteRealm` and pass the default path using the `Configuration.defaultRealmPath`. So it becomes `Realm.deleteRealm(Configuration.defaultRealmPath)`. In general this should not be needed. 

You could also use `Configuration.defaultStoragePath` to change the `defaultRealmPath` to something else. On Android and iOS the `defaultStoragePath` points to the application's data directory.

Cheers

**Comment by Navil** [comment]
Thanks for the information. But how would I detect if the application has been reinstalled?

**Comment by blagoev** [comment]
Could you check the realm file exists on reinstall. It should be removed with the application on uninstall. We are using the `getFilesDir` Android API which points to a directory on the device that should be removed on app uninstall.

**Comment by Navil** [comment]
I can't really find out sadly.

But what I saw and mentioned is, that my app has 5.76MB of application data after reinstalling it. The Cache is 0B, once I click "Delete Data", everything works as it should be.

So are you aware, if Google Play is supposed to delete all Data of an application when I uninstall it? Because this is obviously not happening.

**Comment by blagoev** [comment]
Yes, the data should be removed on app uninstall. Its not Google Play but actually the Android OS that does that. If you are experiencing something not working its definitely not related to realm file being left behind on app uninstall.
Unfortunately if there is no reproduction we can't do much, I am afraid.

**Comment by Navil** [comment]
> There is this discussion about backups, which can explain why you have the old file on reinstall here https://stackoverflow.com/questions/63693499/files-in-internal-storage-getfilesdir-are-not-being-deleted-when-app-is-unin. Could you check if you have `android:allowBackup` enabled?

I can confirm, that this fixed the issue for me. After reinstalling the application now, I am logged out and can log in as normal. Thank you for finding this.  Maybe it is worth looking if it also behaves wrong with a "simple" Realm login (I am using Realm in combination with Firebase and thus maybe having logic that breaks this behaviour).

**Comment by nielsenko** [comment]
I will close this as resolved - doing a bit of issue cleanup. Good luck with your project @Navil
