### ISSUE TITLE
mongodb.com docs falls into infinite loop of redirects

### ISSUE THREAD

**Issue by Shawn-sudo** [realm/realm-dart#1138]
### What happened?

There's a bug on the realm docs on the website. I want to report it on the repository for the website, but I couldn't find it so I'm just opening it here

Try opening this link by clicking on it: https://www.mongodb.com/docs/realm/sdk/flutter/realm-database/read-and-write-data/  The browser would say
> This page isn't working
> **www.mongodb.com** redirected you too many times

If I try to access the url using the side navigation bar, I can open it. However, opening it directly through this url would redirect to https://www.mongodb.com/docs/realm/sdk/flutter/read-and-write-data/ , which redirects back to https://www.mongodb.com/docs/realm/sdk/flutter/realm-database/read-and-write-data/, which redirects back to https://www.mongodb.com/docs/realm/sdk/flutter/read-and-write-data/, which redirects back to https://www.mongodb.com/docs/realm/sdk/flutter/realm-database/read-and-write-data/, which redirects back to
https://www.mongodb.com/docs/realm/sdk/flutter/read-and-write-data/, which redirects back to https://www.mongodb.com/docs/realm/sdk/flutter/realm-database/read-and-write-data/, which redirects back to https://www.mongodb.com/docs/realm/sdk/flutter/read-and-write-data/, which (I'll stop at here lol)

### Repro steps

1. Open this link by clicking on it: https://www.mongodb.com/docs/realm/sdk/flutter/realm-database/read-and-write-data/  
2. It causes infinite redirects

### Version

N/A

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### What type of application is this?

Other

### Client OS and version

Brave Version 1.47.186 Chromium: 109.0.5414.119 (Official Build) (arm64)

### Relevant log output

```shell
This page isn’t working
www.mongodb.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS
```

**Comment by desistefanova** [comment]
Thanks @Shawn-sudo!
We will fix that.

**Comment by mongodben** [comment]
hi @Shawn-sudo, thanks for bringing this to our attention. this has now been fixed and you should be able to successfully navigate to https://www.mongodb.com/docs/realm/sdk/flutter/realm-database/read-and-write-data/

**Comment by Shawn-sudo** [comment]
Oh yay thanks
