### ISSUE TITLE
Flexible Sync support for MongoDB Atlas Sharded Clusters

### ISSUE THREAD

**Issue by dotjon0** [realm/realm-dart#1139]
### Problem

We have noticed at https://www.mongodb.com/docs/realm/sdk/flutter/sync/manage-sync-subscriptions/ there is the comment "Enabling Flexible Sync in your App requires a non-sharded Atlas cluster running".

Larger applications will have no option but to shard MongoDB Atlas clusters when they grow to a certain level - thus why we have made this a 'dealbreaker' in importance.

This feature request is to request if support for sharded MongoDB Atlas clusters could be considered please.

### Solution

see above

### Alternatives

see above

### How important is this improvement for you?

Dealbreaker

### Feature would mainly be used with

Atlas Device Sync

**Comment by ianpward** [comment]
Yes - its on our roadmap and we hope to get to it later this year. There shouldn't be any SDK related work for us to enable this however.

**Comment by dotjon0** [comment]
@ianpward amazing, thank you! Speak soon.
