### ISSUE TITLE
Introduce deprecated flag for fields

### ISSUE THREAD

**Issue by Navil** [realm/realm-dart#1152]
### Problem

With breaking schema changes being basically a no-go for production apps, I am trying to make only additive changes and migrate/deprecate the original fields.

However there is no real way to add a deprecation flag to fields. For not using fields anymore that got deprecated before, it would be a nice addition to allow a @Deprecated annotation on specific fields of a RealmModel.

### Solution

Either take over the existing [Deprecated](https://api.flutter.dev/flutter/dart-core/Deprecated-class.html) annotation from Dart when generating the model, or introduce a realm specific version of it.

### Alternatives

My current solution is to freeze those fields on app start, so errors will be thrown doing testing if thlse fields are still bring used accidently.

This is obviously not an optimal solution. 

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Atlas Device Sync

**Comment by blagoev** [comment]
Hi, 

Deprecated annotation is used for APIs. End user apps shouldn't need such annotations. What type of an app are you building? Can you give more specific example what are you trying to archive?

Cheers

**Comment by Navil** [comment]
Hey, as mentioned, breaking schema changes in production applications are very bad and I basically have to avoid them.

So instead of changing the datatype of a field, for example, I would just add a new field, migrate the code to use this field, and then migrate from the old field to the new field.

Once all users have the new version of my application, the old field becomes basically unused. To prevent my team however to accidently read or write to the old field, I would appreciate some form of deprecation on that old field, so developers see that they should use the new field instead.

I currently do this for all changes that would be breaking.

**Comment by nirinchev** [comment]
Why not just remove the old field from the client schema? Or are you concerned that someone will accidentally re-add it?

**Comment by nirinchev** [comment]
Removing a field from the client side schema is not a breaking change. It's equivalent to an older client that never knew about the field connecting.

**Comment by Navil** [comment]
By client side schema you mean changing it in the model and re-generating it?

**Comment by Navil** [comment]
I feel stupid now. Just removing it from the client schema works fine. Removing it from the server schema however would break the schema. But that's fine so war, just some leftovers that I can deal with for now. Thank you.

**Comment by nirinchev** [comment]
To be clear, changing the field type is a breaking schema change and not supported. But removing it is fine - what will happen under the hood is that you'll still receive data for that field, but because it doesn't exist in the dart models, your team won't be able to accidentally continue using it.
