### ISSUE TITLE
Listen to changes

### ISSUE THREAD

**Issue by orangeswim** [realm/realm-dart#1156]
I've tried to look for a way to listen to realm changes so that data can be synced to an api or another external database (MySQL or postgres, firebase)

I wasn't able to find anything except syncing to mongodb online offering. Am I missing something?

Thank you

**Comment by desistefanova** [comment]
Hi @orangeswim,
We don't provide syncing to external data sources. But we support changes notifications. You can see the [documentation](https://www.mongodb.com/docs/realm/sdk/flutter/realm-database/react-to-changes/#std-label-flutter-realm-list-change-listener). Is this the thing that you need?
