### ISSUE TITLE
RealmException when try to use the to-one relationship feature.

### ISSUE THREAD

**Issue by triplehman3563** [realm/realm-dart#1164]
### What happened?

RealmException: Error opening realm at path /Users/ming.chen/Desktop/workspace/realm_testing/default.realm. Error code: 18 . Message: Schema validation failed due to the following errors:
- Property 'ScooterShop.owner' of type 'object' has unknown object type 'Scooter'
package:realm/src/native/realm_core.dart 119:7    _RealmCore.throwLastError.<fn>
package:ffi/src/arena.dart 124:31                 using
package:realm/src/native/realm_core.dart 113:5    _RealmCore.throwLastError
package:realm/src/native/realm_core.dart 2784:17  _RealmLibraryEx.invokeGetPointer
package:realm/src/native/realm_core.dart 599:32   _RealmCore.openRealm
package:realm/src/realm_class.dart 194:22         Realm._openRealm
package:realm/src/realm_class.dart 149:98         new Realm._
package:realm/src/realm_class.dart 147:38         new Realm
test/testingRealm_test.dart 7:19                  main.<fn>

### Repro steps

1. create new flutter project
2. flutter pub add realm
3. flutter clean
4. flutter pub get
5. flutter pub run realm install
6. add the following file to ./lib/realms/
schemes.dart 
````
import 'package:realm/realm.dart';

part 'schemes.g.dart';

@RealmModel()
class _Scooter {
  @PrimaryKey()
  late ObjectId id;
  late String name;
}

@RealmModel()
class _ScooterShop {
  @PrimaryKey()
  late ObjectId id;
  late String name;
  late _Scooter? owner;
}
````
7. `flutter pub run realm generate`
8. create a test file in ./test
````
import 'package:flutter_test/flutter_test.dart';
import 'package:realm/realm.dart';
import 'package:realm_testing/realms/schemes.dart';

void main() {
  test('realm test', () {
    final realm = Realm(Configuration.inMemory([ScooterShop.schema]));
  });
}
````
9. run the test.

### Version

Flutter 3.7.1  Dart 2.19.1

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

MacOS 13.2

### Stacktrace of the exception/crash you're getting

```shell
RealmException: Error opening realm at path /Users/ming.chen/Desktop/workspace/realm_testing/default.realm. Error code: 18 . Message: Schema validation failed due to the following errors:
- Property 'ScooterShop.owner' of type 'object' has unknown object type 'Scooter'
package:realm/src/native/realm_core.dart 119:7    _RealmCore.throwLastError.<fn>
package:ffi/src/arena.dart 124:31                 using
package:realm/src/native/realm_core.dart 113:5    _RealmCore.throwLastError
package:realm/src/native/realm_core.dart 2784:17  _RealmLibraryEx.invokeGetPointer
package:realm/src/native/realm_core.dart 599:32   _RealmCore.openRealm
package:realm/src/realm_class.dart 194:22         Realm._openRealm
package:realm/src/realm_class.dart 149:98         new Realm._
package:realm/src/realm_class.dart 147:38         new Realm
test/testingRealm_test.dart 7:19                  main.<fn>
```

**Comment by blagoev** [comment]
Hi you need to add all models to the schema so for this case it should be 
`final realm = Realm(Configuration.inMemory([ScooterShop.schema, Scooter.schema]));` # added `Scooter.schema` to the config

**Comment by triplehman3563** [comment]
> Hi, You need to add all models to the config so for this case it should be `final realm = Realm(Configuration.inMemory([ScooterShop.schema, Scooter.schema]));` # added `Scooter.schema` to the config

This was helpful, it solved the problem, thanks a lot.
BTW, it will be great if this was mentioned highlighted in the [Relationship](https://www.mongodb.com/docs/realm/sdk/flutter/realm-database/model-data/relationships/#relationships---flutter-sdk) part or the [Configure & Open a Realm](https://www.mongodb.com/docs/realm/sdk/flutter/realm-database/configure-and-open/#configure---open-a-realm---flutter-sdk) part of the tutorial.
