### ISSUE TITLE
Unable to install on iOS 1.0.1

### ISSUE THREAD

**Issue by modgsan** [realm/realm-dart#1165]
### What happened?

I tried to run pod install on my Flutter project with realm: ^1.0.1, but it failed with an error message:

`[!] Unable to install vendored xcframework `realm_dart` for Pod `realm`, because it contains both static and dynamic frameworks`

Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

just like #1023 

### Repro steps

1. flutter clean
2. flutter pub get
3. flutter pub run realm generate
4. flutter run or pod install

### Version

1.0.1

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

Xcode - develop for iOS and macOS (Xcode 14.2)     • Xcode at /Applications/Xcode.app/Contents/Developer     • Build 14C18     • CocoaPods version 1.11.3

**Comment by maBarabas** [comment]
I managed to fix this by `gem uninstall -aIx` and `gem install cocoapods`. Probably just updating all the gems would have fixed it too. It is a bug in upstream cocoapods: https://github.com/CocoaPods/CocoaPods/issues/10332#issuecomment-1257749952

**Comment by modgsan** [comment]
> I managed to fix this by `gem uninstall -aIx` and `gem install cocoapods`. Probably just updating all the gems would have fixed it too. It is a bug in upstream cocoapods: [CocoaPods/CocoaPods#10332 (comment)](https://github.com/CocoaPods/CocoaPods/issues/10332#issuecomment-1257749952)

Thanks a lot, it works
