### ISSUE TITLE
List comparisons not working with .query 

### ISSUE THREAD

**Issue by geosebas** [realm/realm-dart#1169]
### What happened?

Hello there, 

I just tried to do a simple query with some list as parameter but got the error `RealmException: Property type List<String> not supported`

It was a very simple query, and following the doc it should be ok. 
https://www.mongodb.com/docs/realm/realm-query-language/#list-comparisons

I saw too that in the doc, we have some limitations for flexible sync for query subscription, but it's not relevant for the case here. 
https://www.mongodb.com/docs/realm/realm-query-language/#list-queries

Tried with both 1.0.0 and 1.0.1 versions

Thanks for the help !

### Repro steps

Just execute the code snippets 

### Version

Flutter 3.7.3

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

1.0.1

### Code snippets

    final newIds = ['abc', 'def', 'ghi'];
    final newPlayers = realm.query<Player>(r'stripeId in $0', [newIds.toList()]).toList();
    // Tried theses ones too, but same error
    final newPlayers = realm.query<Player>(r'stripeId in $0', [newIds]).toList();
    final newPlayers = realm.query<Player>(r'stripeId == any $0', [newIds.toList()]).toList();

### Stacktrace of the exception/crash you're getting

```shell
I/flutter (14200): RealmException: Property type List<String> not supported
I/flutter (14200): #0      _intoRealmValue (package:realm/src/native/realm_core.dart:2859:7)
I/flutter (14200): #1      _intoRealmQueryArg (package:realm/src/native/realm_core.dart:2803:3)        
I/flutter (14200): #2      _RealmCore.queryClass.<anonymous closure> (package:realm/src/native/realm_core.dart:985:9)
I/flutter (14200): #3      using (package:ffi/src/arena.dart:124:31)
I/flutter (14200): #4      _RealmCore.queryClass (package:realm/src/native/realm_core.dart:981:12)     
I/flutter (14200): #5      Realm.query (package:realm/src/realm_class.dart:415:30)
I/flutter (14200): #6      _PaymentTableState._updatePlayers (package:padel_app/ui/widgets/payment_table.dart:55:30)
I/flutter (14200): <asynchronous suspension>
I/flutter (14200): #7      _PaymentTableState.initData (package:padel_app/ui/widgets/payment_table.dart:70:5)
I/flutter (14200): <asynchronous suspension>
I/flutter (14200): #8      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:628:33)
I/flutter (14200): <asynchronous suspension>
```

**Comment by desistefanova** [comment]
Hi @geosebas,
Thanks for reporting.
You can make it work if you build the query as a string instead of passing the list as a query parameter. 
We have similar [issue](https://github.com/realm/realm-dart/issues/1084) about that and it is still not fixed. You can find a working sample there. Currently, it throws an error  because the lists are still not supported as query parameters.
I hope this will help.

**Comment by desistefanova** [comment]
I'm closing this issue as duplicated.
@geosebas, you can add your vote to the other [issue](https://github.com/realm/realm-dart/issues/1084).

**Comment by geosebas** [comment]
Thanks for your help !
