### ISSUE TITLE
Why is the realm lib in the release build so big?

### ISSUE THREAD

**Issue by lucas3g** [realm/realm-dart#1172]
### Problem

Why is the realm lib in the release build so big?
![realm](https://user-images.githubusercontent.com/53888064/220178848-6af4ba2d-281a-450d-8728-cee1531ca93a.png)

My project is hitting 123mb after adding the realm
![build](https://user-images.githubusercontent.com/53888064/220179085-56a3c7d7-0c32-4f55-90da-cfd802f70c74.png)

### Solution

Decrease lib size in realm build

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by blagoev** [comment]
@lucas3g Thanks for reporting. We will investigate this with high priority.

**Comment by blagoev** [comment]
@lucas3g We just released a fix for this.
