### ISSUE TITLE
Change listener not being called when new data is inserted

### ISSUE THREAD

**Issue by DominicOrga** [realm/realm-dart#1173]
### What happened?

I have established a listener to identify any modifications within a collection. The listener is activated when updates or deletions occur on existing models, however, it does not respond to the insertion of new data.

### Repro steps

1. Create a model then run `build_runner`
```
@RealmModel()
class _UploadMetadataModel {
  
  @PrimaryKey()
  late ObjectId id;
  late String sourceFilePath;
  late String targetFilePath;
  late String uploadStatus;
}
```
2. Create a Realm instance
```
final realm = Realm(Configuration.local([UploadMetadataModel.schema]))
```
3. Add a change listener for the `UploadMetadata` collection
```
realm.all<UploadMetadataModel>().changes.listen((event) {
   // Expect to receive newly inserted upload metadata model
});
```
4. Insert new `UploadMetadata` in realm
```
 realm.write(() => realm.add(uploadMetadata));
```

Unfortunately, Step 4 does not trigger the change listener

### Version

Dart 2.19.2/Flutter 3.7.3

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

Android 13

**Comment by desistefanova** [comment]
Hi @DominicOrga, thanks for reporting!
Your code looks absolutely correct. Can you try adding some small delay after subscribing to the changes and before the writing? 
You can see how it is written in our [tests ](https://github.com/realm/realm-dart/blob/6aca9f43ac15f2d3d6fa879b40992bb9869c5741/test/results_test.dart#L366)
I hope this will help!

**Comment by DominicOrga** [comment]
Hey @desistefanova , making the Realm setup asynchronous seems to have done the trick. 
Thanks! I'll close this issue now.

**Comment by lekhnath** [comment]
> Hey @desistefanova , making the Realm setup asynchronous seems to have done the trick. Thanks! I'll close this issue now.

@DominicOrga How to setup async?
