### ISSUE TITLE
Ability to update the order of a list of embedded objects

### ISSUE THREAD

**Issue by Taco55** [realm/realm-dart#1179]
### Problem

It would be very useful to have better way to update the order of embedded objects in a managed list.

Unfortunately, Realm seems not to allow to move individual instances (or to remove all before adding new and/or already managed objects). Although it is clear this won't work due the lifecycle of an embedded object, the only solution I have is to make a deep copy or by using normal Realm objects. Both are not ideal when lots of (nested) embedded objects are used.

I wonder if this is something that can be supported out of the box?

### How important is this improvement for you?

I would like to have it but have a workaround

### Feature would mainly be used with

Local Database only

**Comment by desistefanova** [comment]
Hi @Taco55, thanks for reporting!
What is your use case and why do you need to reorder them?
What about `sort` operation on a list of embedded objects? Is it something that could solve your problem?
I mean for example: 
```dart
final sortedList = parent.embeddedObjectsList.query('TRUEPREDICATE SORT(value DESC)');
```

**Comment by nielsenko** [comment]
@Taco55 What is wrong with:
```dart
import 'package:realm_dart/realm.dart';

part 'embedded_list.g.dart';

@RealmModel()
class _Stuff {
  late List<_EmbeddedStuff> moreStuff;
}

@RealmModel(ObjectType.embeddedObject)
class _EmbeddedStuff {
  late int stuff;

  @override
  String toString() => '$stuff';
}

void main(List<String> arguments) {
  final realm = Realm(Configuration.local([
    Stuff.schema,
    EmbeddedStuff.schema,
  ]));

  final x = realm.write(() {
    return realm.add(Stuff(moreStuff: [1, 2, 3].map(EmbeddedStuff.new)));
  });

  realm.write(() => x.moreStuff.move(0, 2));

  print(x.moreStuff);

  Realm.shutdown();
}
```
Outputs:
```sh
❯ dart run bin/embedded_list.dart
[2, 3, 1]
```

**Comment by Taco55** [comment]
@desistefanova Use cases are the same as for lists with normal objects that should be reordered, but where an embedded object is more appropriate (related to one parent only, same life cycle, no key required, etc.).

The method you mentioned would also work. However, when a user reorders the list from the UI for example, a new sort property (numbering, date etc.) would then be required to get the correct sorting, and all objects should be updated with a new value for this property while only one item is moved.

**Comment by Taco55** [comment]
@nielsenko That's a good point. I thought that moving was internally the same as deleting and inserting, which resulted in an error in my case. But I also have a use case with a form builder where items are not only moved, but where items can also be deleted or new items can be added (and moved again), but where all updates are saved at once. This would required to keep track of all updates and became quite cumbersome (RealmResults is not supported for the Widgets that are used). Therefore, just rebuilding the list felt much easier (and which can easily be performed with normal objects).

**Comment by nielsenko** [comment]
@Taco55 For `ManagedRealmList<T>` move is special:
```dart
extension ListExtension<T> on List<T> {
  /// Move the element at index [from] to index [to].
  void move(int from, int to) {
    RangeError.checkValidIndex(from, this, 'from', length);
    RangeError.checkValidIndex(to, this, 'to', length);
    if (to == from) return; // no-op
    final self = this;
    if (self is ManagedRealmList<T>) {
      self.move(from, to);
    } else {
      insert(to, removeAt(from));
    }
  }
}
```
Say two clients moves the same object concurrently to two different indexes, it is important that we don't end up with the object appearing at both indexes. This require us to track moves explicitly.

Regarding your second use-case. I probably misunderstand something, but could this work for you:
```dart
import 'dart:math';

import 'package:realm_dart/realm.dart';

part 'embedded_list.g.dart';

@RealmModel()
class _Stuff {
  late List<_EmbeddedStuff> moreStuff;
}

@RealmModel(ObjectType.embeddedObject)
class _EmbeddedStuff {
  late int stuff;

  @override
  String toString() => '$stuff';
}

void main(List<String> arguments) {
  final realm = Realm(Configuration.local([
    Stuff.schema,
    EmbeddedStuff.schema,
  ]));

  final x = realm.write(() {
    return realm.add(Stuff(moreStuff: [1, 2, 3].map(EmbeddedStuff.new)));
  });

  print('before move   : ${x.moreStuff}');

  realm.write(() => x.moreStuff.move(0, 2));

  print('after move    : ${x.moreStuff}');

  realm.write(() {
    final l = x.moreStuff;
    l.add(EmbeddedStuff(8)); // add new stuff to the end ..

    final newOrder = [for (int i = 0; i < l.length; ++i) i]
      ..shuffle(Random(48));

    int i = 0;
    for (final s in l) {
      l.move(i, newOrder[i]);
      ++i;
    }
  });

  print('after rebuild : ${x.moreStuff}');

  Realm.shutdown();
}
```
Outputs:
```sh
❯ dart run bin/embedded_list.dart
before move   : [1, 2, 3]
after move    : [2, 3, 1]
after rebuild : [2, 8, 3, 1]```

**Comment by nielsenko** [comment]
.. but unless you really need to move stuff around I would recommend @desistefanova approach of just sorting the list in the order needed.

**Comment by Taco55** [comment]
@nielsenko 
Thank you very much for taking the time to think along. I will definitely use `move` from now on.
In your example, moving, adding and moving, however, are executed one after the other. And this is more or less how it is done inside the widgets, but since these widgets do not support RealmResults or RealmLists, the Realm needs to updated at once after the user saves the form. That is certainly possible with modifications to your code, but requires that the indices of moved or deleted items are adjusted when new items are added to the list. To avoid keeping track of all this (this would require to make extensions to several form widgets, but in that case it would even be better to just support RealmLists), my question was therefore whether an embedded list could just be rebuilt at once (but's that's may be the lazy way of working).... Presumably this is not how embedded lists are intended to work and I have to do it the way you indicated and in all other situations as @desistefanova mentioned.

**Comment by nielsenko** [comment]
@Taco55 When you say _these_ widgets do not support `RealmResults` or `RealmList` - what widgets are you referring to, and can you elaborate on the _do not support_ part?

**Comment by Taco55** [comment]
@nielsenko I think my comment was not quite right. What I meant was that I created several generic form fields (extended from `FormField<T>`), where T is of type `List` and not of `RealmList` or `RealmResults` (I use them in apps without Realm as well), loosing some of the benefits of the Realm format.
