### ISSUE TITLE
RealmException: Switch user failed. Error code: 1 . Message: Unknown error

### ISSUE THREAD

**Issue by RedFox64** [realm/realm-dart#1181]
### What happened?

When I try switch user

### Repro steps

_app.switchUser(user);

1) Auth User ID:1
2) Open Realm Object (Open DB)
3) Logout user
4) Close DB
5) Auth User ID:2
6) Open Realm Object (Open DB)
7) Get users (App _app.users.toList())
7) Switch User

I do not get an error when switching the same user which logged.

### Version

Flutter 3.7.5, Realm 1.0.2

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### What type of application is this?

Flutter Application

### Client OS and version

Android 11

### Stacktrace of the exception/crash you're getting

```shell
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RealmException: Switch user failed. Error code: 1 . Message: Unknown error
E/flutter (31485): #0      _RealmCore.throwLastError.<anonymous closure>
realm_core.dart:119
E/flutter (31485): #1      using
arena.dart:124
E/flutter (31485): #2      _RealmCore.throwLastError
realm_core.dart:113
E/flutter (31485): #3      _RealmLibraryEx.invokeGetBool
realm_core.dart:2777
E/flutter (31485): #4      _RealmCore.switchUser.<anonymous closure>
realm_core.dart:1950
E/flutter (31485): #5      using
arena.dart:124
E/flutter (31485): #6      _RealmCore.switchUser
realm_core.dart:1949
E/flutter (31485): #7      App.switchUser
app.dart:161
E/flutter (31485): #8      AuthCubit.switchUser
auth_cubit.dart:128
```

### Relevant log output

```shell
RealmException: Switch user failed. Error code: 1 . Message: Unknown error
```

**Comment by nielsenko** [comment]
You cannot switch to a user that has been logged out, if that is what you are trying?

**Comment by desistefanova** [comment]
Hi @RedFox64,
We closed this issue. You still can not switch to a user that is not logged in (it is by design), but we fixed the error message.
Thanks for reporting!
