### ISSUE TITLE
Use a library that imports realm_dart in a Flutter application

### ISSUE THREAD

**Issue by vandir** [realm/realm-dart#1184]
I have developed a library that defines all the models of my Flutter application. This library will also be used by two pure Dart projects (one of which is a web server). My need is to define my models only once and allow code reuse.

Is this scenario supported?

I get the following error in my Flutter application:

```
The element type 'SchemaObject 
(where SchemaObject is defined in <redacted>\pub.dev\realm_dart-1.0.2\lib\src\configuration.dart)' 
can't be assigned to the list type 'SchemaObject 
(where SchemaObject is defined in <redacted>\pub.dev\realm-1.0.2\lib\src\configuration.dart)'.
```

when trying to define my configuration (imported from `realm`) with schemas defined in my library (generated from `realm_dart`).

```dart
final config = Configuration.local(
  [
    LibraryModel1.schema,
    LibraryModel2.schema,
  ]
);
```

Can't I just use `realm_dart` in my Flutter application or can I use `realm` in a pure Dart web server?

**Comment by nielsenko** [comment]
Yes, this is a good argument for consolidating `realm` and `realm_dart` into one package. Anyway there is a trick you can use, if a bit ugly. In your flutter project take a dependency on both `realm` and `realm_dart` and use `realm_dart` in your shared project. 

I have a wip-branch on the realm-dart-sample repo where I do the same: https://github.com/realm/realm-dart-samples/blob/kn/time_track_flutter_ui/time_track/flutter_ui/pubspec.yaml. Essentially you are just using the `realm` package to install the shared lib like this.

Can this work for you?

**Comment by vandir** [comment]
I was just trying an alternative solution to get it to work, so thanks, it's good for me!
