### ISSUE TITLE
Implementing write(withoutNotifying: ...)

### ISSUE THREAD

**Issue by frmatthew** [realm/realm-dart#1201]
### Problem

The Swift SDK includes a transaction option on the write function to start a transaction without notifying a specific listener: https://www.mongodb.com/docs/realm-sdks/swift/latest/Structs/Realm.html#/ Is this feature implemented or planned for the Dart SDK? Thank you...

### How important is this improvement for you?

I would like to have it but have a workaround

### Feature would mainly be used with

Local Database only

**Comment by blagoev** [comment]
Hi, 
This it is not available in the Dart SDK and we don't have immediate plans on supporting it. 

cheers.

**Comment by blagoev** [comment]
closing as no further action is needed on this issue.
