### ISSUE TITLE
Usync async callback inside write or writeAsync will ignore any error throw inside and execute transaction

### ISSUE THREAD

**Issue by geosebas** [realm/realm-dart#1203]
### What happened?

Hello, 

I just saw that after getting an error inside an async callback in the `writeAsync` or `write` method, the transaction will still be completed. 

Here is my original code 

```
    try {
      final realm = await realmService.realm;
      await realm.writeAsync(() async {
        final stripeCredits = widget.match.playersCredits
            .where((element) => element.stripeId != null)
            .map(
              (e) => e.stripeId!,
            )
            .toSet();
        
        realm.deleteMany(widget.match.playersCredits);
        realm.delete(widget.match);
        
        // Error here,  Message: Access to invalidated Collection object, using .toSet() on stripeCredit seems to fix the error, I don't know why
        for (final stripeCredit in stripeCredits) {
          await stripeService.refundPayment(stripeCredit);
        }
      });
      await realm.syncSession.waitForUpload();
    } on RealmException catch (e) {
      debugPrint(e.message);
      if (mounted) {
        setState(() {
          error = e.message;
        });
      }
    } on Exception catch (e) {
      debugPrint(e.toString());
      if (mounted) {
        setState(() {
          error = e.toString();
        });
      }
    } 
```

Beside the fact that the error was really weird (`Unhandled Exception: RealmException: Error code: 7 . Message: Access to invalidated Collection object`), I since then saw that getting an error with an async callback will make the sdk ignore the error and still complete the transaction. 

I managed to reproduce by simplifying my code. Here 2 snippets to reproduce : 
First with `write` method
```
try {
  final realm = await realmService.realm;
  realm.write(() async {
    realm.delete(widget.match);
    throw Exception('test error on write transaction');
  });
  await realm.syncSession.waitForUpload();
} on Exception catch (e) {
  debugPrint(e.toString());
}
```
And with `writeAsync` method
```
try {
  final realm = await realmService.realm;
  await realm.writeAsync(() async {
    realm.delete(widget.match);
    throw Exception('test error on write transaction');
  });
  await realm.syncSession.waitForUpload();
} on Exception catch (e) {
  debugPrint(e.toString());
}
```

Everything work well if you remove the `async` keyword, but I need it, or at least I need a way to cancel the write transaction on some conditions. 

### Repro steps

Use my 2 code snippets to reproduce

### Version

Flutter 3.7.1

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### What type of application is this?

Flutter Application

### Client OS and version

Realm 1.02

**Comment by nirinchev** [comment]
This is the expected behavior - both `write` and `writeAsync` take a synchronous callback. This is not super easy to express with the dart API, but what's happening is you're returning a `Future` from the callback, so the transaction completes as soon as we hit an `await` and the incomplete future is returned. We should probably special case this and throw a meaningful exception to indicate this is a misuse of the API.

There are two ways to implement what you're trying to achieve. The first is to do a two-step deletion, where the first step marks the objects for deletion while the second step finalizes the deletion operation - e.g.:

```dart
realm.write(() {
  for (final credit in credits) {
    credit.state = CreditState.refunding;
  }
});

await stripeService.refundPayment(stripeCredits);

realm.write(() {
  realm.deleteMany(credits);
});
```

The alternative is using the manual transaction API:

```dart
final transaction = await realm.beginWriteAsync();

realm.deleteMany(credits);
await stripeService.refundPayment(stripeCredits);

await transaction.commitAsync();
```

**Comment by geosebas** [comment]
> The alternative is using the manual transaction API:

Amazing ! I wanted to do something like this but didn't manage to find any doc about this. 
Do I still need to rollback inside my catch ? 

Thanks a lot for your help !

**Comment by nirinchev** [comment]
Yes, you'll need to call `rollback` in the catch clause to cancel the transaction and roll back any changes made.

**Comment by geosebas** [comment]
Thanks a lot for your help !
