### ISSUE TITLE
Realm: App: log_in_with_credentials failed: 401 message: invalid id token: 'aud' must be a string containing the client_id

### ISSUE THREAD

**Issue by RedFox64** [realm/realm-dart#1205]
### What happened?

I implemented authorization through Google. Authorization works through Google on the Android platform, but does not work on the iOS platform. Error: Realm: App: log_in_with_credentials failed: 401 message: invalid id token: 'aud' must be a string containing the client_id

I think it doesn't work because each platform has a different client_id, and in mongodb atlas only set one client_id for google provider.

How can this be fixed? I need to authorize through google on two platforms. I may need to do this on other platforms as well in the future.

Translated with www.DeepL.com/Translator (free version)

### Repro steps

logging in through google on the ios platform

### Version

Flutter 3.7.7, Realm 1.0.2

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### What type of application is this?

Flutter Application

### Client OS and version

Android 11

### Code snippets

final AppConfiguration appConfig = AppConfiguration(Config.mongoAppID);
_app = App(appConfig);

_googleSignIn = GoogleSignIn(
      serverClientId: Platform.isAndroid
          ? "104871183495*-pbs13p6rk8jahhdbc45ag50rst2c****.apps.googleusercontent.com"
          : "104871183495*-n83avo1avbddc4i3njt88016v0ng****.apps.googleusercontent.com",
      scopes: <String>[
        'email',
        'profile',
        "openid",
        'https://www.googleapis.com/auth/userinfo.email',
        'https://www.googleapis.com/auth/userinfo.profile',
      ],
    );

    GoogleSignInAccount? signRes = await _googleSignIn.signIn();

    if (googleSign != null) {
      GoogleSignInAuthentication auth = await googleSign.authentication;

      if (auth.idToken != null) {
        user = await _app.logIn(Credentials.googleIdToken(auth.idToken!));
      }
    }

### Stacktrace of the exception/crash you're getting

```shell
Realm: App: log_in_with_credentials failed: 401 message: invalid id token: 'aud' must be a string containing the client_id
```

**Comment by RedFox64** [comment]
I wrote wrong "Client OS and version". I used iOS 16.2

**Comment by nielsenko** [comment]
I see your point 🤔 

Would using [Firebase Authentication](https://firebase.google.com/docs/auth/flutter/start) be an option? There the `aud` is taken from the project name, and is stable between iOS and Android. You would then use the jwt credentials instead:
```dart
final app = App(AppConfiguration(...));
final user = app.currentUser;
if (user != null) return user;

// trigger firebase authentication

final firebaseUser = FirebaseAuth.instance.currentUser; 
if (firebaseUser != null) {
  final jwt = await firebaseUser.getIdToken();
  final user = await app.logIn(Credentials.jwt(jwt));
  return user;
}
...
```
You can use the suite of `firebase_ui_*` packages to integrate with various providers:
```yaml
  firebase_ui_auth: ^1.1.16
  firebase_ui_oauth_apple: ^1.0.23
  firebase_ui_oauth_facebook: ^1.0.23
  firebase_ui_oauth_google: ^1.0.23
```
