### ISSUE TITLE
Error opening realm at path ~/default.realm. Error code: 18 > already opened with a different schema mode.

### ISSUE THREAD

**Issue by SPSpisoft** [realm/realm-dart#1206]
### What happened?

realm: ^1.0.2

Error opening realm at path /data/data/.../files/default.realm. Error code: 18 . Message: Realm at path '/data/data/.../files/default.realm' already opened with a different schema mode.

### Repro steps

The relevant error-causing widget was: 
When the exception was thrown, this was the stack: 
#0      _RealmCore.throwLastError.<anonymous closure> (package:realm/src/native/realm_core.dart:119:7)
#1      using (package:ffi/src/arena.dart:124:31)
#2      _RealmCore.throwLastError (package:realm/src/native/realm_core.dart:113:5)
#3      _RealmLibraryEx.invokeGetPointer (package:realm/src/native/realm_core.dart:2784:17)
#4      _RealmCore.openRealm (package:realm/src/native/realm_core.dart:599:32)
#5      Realm._openRealm (package:realm/src/realm_class.dart:194:22)
#6      new Realm._ (package:realm/src/realm_class.dart:149:98)
#7      new Realm (package:realm/src/realm_class.dart:147:38)
#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5015:57)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
...     Normal element mounting (24 frames)
#34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#35     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#36     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
...     Normal element mounting (175 frames)
#211    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#212    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#213    Element.updateChild (package:flutter/src/widgets/framework.dart:3592:18)
#214    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5964:32)
#215    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#216    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#217    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#218    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#219    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#220    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#221    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#222    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#223    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#224    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#225    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#226    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#227    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#228    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#229    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#230    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#231    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#232    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#233    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#234    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#235    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#236    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#237    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#238    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#239    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#240    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#241    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#242    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#243    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#244    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#245    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#246    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#247    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#248    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#249    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#250    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#251    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#252    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#253    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#254    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#255    _invoke (dart:ui/hooks.dart:148:13)
#256    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#257    _drawFrame (dart:ui/hooks.dart:115:31)

### Version

Flutter 3.3.9 & Dart SDK 2.18.5

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

windows & android

**Comment by nielsenko** [comment]
This could happen if for example the realm is being opened simultaneously with different configuration types (`flexibleSync` vs `local`). That is not allowed.

**Comment by blagoev** [comment]
closing as no further action needed
