### ISSUE TITLE
Offline End-User Login / Access

### ISSUE THREAD

**Issue by dotjon0** [realm/realm-dart#1207]
### Problem

We have checked the docs but can not find any information around this, it may be this is already supported.

We are building an 'offline first' Realm Flutter application using MongoDB Device Sync. End-users login with MongoDB App Services authentication. When the end-user has network connectively (is online) the end-user can log into MongoDB App Services authentication and then access Realm local data. If the end-user then looses network connectivity (goes offline) but 'does not log out of MongoDB App Services authentication' the end-user is still able to use our Flutter app offline (but with no API calls, Device Sync is paused, etc).

**Offline & Logged Out - the feature request**
If the end-user is 'logged out' of MongoDB App Services authentication and is 'offline' (no network connectively), how does the user authenticate with MongoDB App Services authentication to use the application 'offline' (with no API calls, Device Sync is paused, etc)? Is this supported and if yes what is the recommended approach?

### Solution

see above

### Alternatives

see above

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Atlas Device Sync

**Comment by nielsenko** [comment]
To open a synchronized realm you need a logged in user, ie:
```dart
  final user = app.current;
  if (user == null) {
    // trigger authentication flow, this require you are online
    Credentials creds = ...;
    user = await app.logIn(creds);
  }
  final realm = await Realm.open(Configuration.flexibleSync(
    user, // <--- we need a logged in user
    [ ... ],
  ));
```
However the fact that a user is logged in is persisted, so when you re-start the app `app.currentUser` is not null, and hence you can open the realm again without re-authenticating.

If you are asking to create a user while offline, and then later go online and only then authenticate, then no that cannot be done.

**Comment by nielsenko** [comment]
So just don't call `user.logOut()` (or `app.removeUser(user)` for that matter).

But maybe I'm not understanding the use-case. Perhaps you can elaborate?

**Comment by nielsenko** [comment]
Actually Atlas Device Sync has its own auth provider. 

Once a user is created and logged in, it hands out its own _realm refresh token_ to the client, and from then on the client uses the _realm refresh token_ to refresh its _realm id token_ (jwt) whenever needed.

The only thing the SoMe Auth Provider's id token (say from firebase) is used for is that first authentication that allows the process to start. And if you for some reason choose to re-authenticate with a fresh SoMe token, but it is important to understand you don't need to.

This also means, that if the SoMe token becomes invalid, and for some reason can not be refreshed, that has no bearing on the status of the realm user, which may be a bit surprising (it was for me 🙂)

**Comment by dotjon0** [comment]
> Actually Atlas Device Sync has its own auth provider.
> 
> Once a user is created and logged in, it hands out its own _realm refresh token_ to the client, and from then on the client uses the _realm refresh token_ to refresh its _realm id token_ (jwt) whenever needed.
> 
> The only thing the SoMe Auth Provider's id token (say from firebase) is used for is that first authentication that allows the process to start. And if you for some reason choose to re-authenticate with a fresh SoMe token, but it is important to understand you don't need to.
> 
> This also means, that if the SoMe token becomes invalid, and for some reason can not be refreshed, that has no bearing on the status of the realm user, which may be a bit surprising (it was for me 🙂)

perhaps we need to raise a feature request so that Atlas Device Sync auth respects the authentication state of the 'custom JWT' third-party auth provider (Firebase, etc) when Atlas Device Sync auth attempts to refresh a user JWT token?

**Comment by nielsenko** [comment]
**Lol** I was having this exact discussion yesterday..

BTW, even if we used the jwt from firebase directly, firebase supports the same. If you don't log out it will keep the refresh token persisted, and you don't have to log in on next app start. 

Basically you just call `await firebaseUser.getIdToken()` to get a fresh token. As a user you would need do that for us on some callback, when realm discovers it needs a fresh token.

Anyway.. that is really a different issue.

**Comment by nielsenko** [comment]
BTW, if you are using shared devices, as I know is sometimes the case with field workers using dedicated rugged devices, then _not logging out_ doesn't work so well. Is that by any change the case for you?

**Comment by dotjon0** [comment]
> BTW, if you are using shared devices, as I know is sometimes the case with field workers using dedicated rugged devices, then _not logging out_ doesn't work so well. Is that by any change the case for you?

Later on yes...

**Comment by nielsenko** [comment]
> Later on yes...

If it happens infrequently enough, ie. user mostly have their own devices, and only rarely do they switch, then just have some user specific pin-code that you get prompted for on app start. If the user fails 3 times in a row, or explicitly ask to switch user, then log out the current realm user and do authentication again. 

That way you can defer the logout until you know that a new user wants to use the device. And in most cases users can just pick up the same device as they used yesterday without doing online re-authentication.

Also remember that while this will allow you to start your day without connectivity, staying offline all the time does not a distributed system make 🙂

**Comment by nielsenko** [comment]
Wrt.

> Should we not be respecting the master auth provider, which in the case of using MongoDB App Services custom JWT should the the third party auth provider (firebase, etc) - otherwise its causing more boilerplate logic within flutter apps and server side for companies using Realm Device Sync in flutter? It's not a problem for us to support but it may make life easier..

This is a change in philosophy and a larger undertaking as it impacts the server as well as all SDKs. It is not really something I'm at liberty to discuss.

**Comment by nielsenko** [comment]
To answer on:

> If the Atlas Device Sync auth user JWT is stored within the Realm local database we guess this JWT is only ever encrypted if the local Realm database in encrypted via https://www.mongodb.com/docs/realm/sdk/flutter/realm-database/realm-files/encrypt/ ? Is it not better to store the Realm user JWT in the secure storage on the applicable native device, i.e. macOS in key chain?

The refresh token is itself stored in a metadata realm. You can set the encryption mode and encryption key for the metadata realm in your app configuration. 

You can generate a random secret on first run, use that as encryption key, and store that in the keychain to achieve what you request.

I believe for apple platforms we automatically do this, even if the user don't specify it explicitly.

**Comment by nielsenko** [comment]
This got a bit messy.. did you learn what you needed?

**Comment by dotjon0** [comment]
> Wrt.
> 
> > Should we not be respecting the master auth provider, which in the case of using MongoDB App Services custom JWT should the the third party auth provider (firebase, etc) - otherwise its causing more boilerplate logic within flutter apps and server side for companies using Realm Device Sync in flutter? It's not a problem for us to support but it may make life easier..
> 
> This is a change in philosophy and a larger undertaking as it impacts the server as well as all SDKs. It is not really something I'm at liberty to discuss.

which repo is best to raise a feature request for this? realm core?

**Comment by dotjon0** [comment]
> This got a bit messy.. did you learn what you needed?

yes thank you @nielsenko very helpful and has opened up various action points we need to put in! Thank you so much for being so thorough, great chat!
