### ISSUE TITLE
Weird behavior with .query().where callback

### ISSUE THREAD

**Issue by geosebas** [realm/realm-dart#1210]
### What happened?

Hello, 

I got a very weird problem, I'm really not sure if it's a bug on your sdk, on dart/flutter or if I missunderstood callback order execution. 

So I have this very simple code : 
``` dart
      debugPrint('start delete');
      final matchDate = _fromFormattedDate(widget.match.date);
      debugPrint('get event');
      final allEvents = realm
          .query<Match>(r'_id != $0 and recurrentId = $1', [widget.match.id, widget.match.recurrentId]).where((match) {
        debugPrint('filter event');
        return true;
        // final date = _fromFormattedDate(match.date);
        // if (date.isAfter(matchDate)) {
        //   return true;
        // }
        // if (date.isAtSameMomentAs(matchDate)) {
        //   debugPrint('same moment');
        //   return match.slotIndex > widget.match.slotIndex;
        // }
        // return false;
      });
      debugPrint('got event');
      realm.delete(widget.match);
      debugPrint(' delete event');
      realm.deleteMany(allEvents);
      debugPrint(' delete all event');

```
I simplified my code by just returning `true` in the callback. 

Here the order exec with the logs :
```
I/flutter (24220): start delete
I/flutter (24220): get event
I/flutter (24220): got event
I/flutter (24220):  delete event
I/flutter (24220): filter event
I/flutter (24220):  delete all event
``` 

It is normal that the `realm.delete()` line is called before the `.where()` callback ? 

### Repro steps

See example 

### Version

Flutter 3.7.7

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### What type of application is this?

Flutter Application

### Client OS and version

Realm 1.02

**Comment by nirinchev** [comment]
Yes, `.where` returns iterable that is not evaluated until someone actually iterates the collection - that could be in a `for` loop or by calling `.toList()`. When you call `.deleteMany`, Realm starts iterating over the collection which is why you're seeing the callback being invoked.

**Comment by geosebas** [comment]
Thanks for the help and sorry for the issue.
