### ISSUE TITLE
Using the aggregation functions

### ISSUE THREAD

**Issue by RedFox64** [realm/realm-dart#1244]
### Problem

Using aggregation functions when using flexibleSync configuration. 
Is that possible? I need to use complex queries using $unwind (aggregation) and $project (aggregation) and etc.

Example:
`[
  {
    $match:
      {
        "notes.userIdAssigned": ObjectId(
          "6388b275af5c09fb173f943b"
        ),
      },
  },
  {
    $unwind:
      {
        path: "$notes",
      },
  },
  {
    $match:
      {
        "notes.userIdAssigned": ObjectId(
          "6388b275af5c09fb173f943b"
        ),
      },
  },
  {
    $project:
      {
        topicId: "$_id",
        _id: "$notes._id",
        name: "$notes.name",
        description: "$notes.description",
        priorityId: "$notes.priorityId",
        statusId: "$notes.statusId",
        userIdAssigned: "$notes.userIdAssigned",
        userIdCreated: "$notes.userIdCreated",
      },
  },
]`

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Atlas Device Sync

**Comment by nielsenko** [comment]
@RedFox64 

I'm afraid not. Flexible sync subscription only support a subset of RQL (Realm Query Language) which differs from MQL (MongoDB Query Language).

You could perhaps use the [`$out`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/out/) operator server-side and store the aggregation in a collection, that you then sync down to the client.

**Comment by BrockCodes** [comment]
Yes, it's possible to use aggregation functions with the `flexibleSync` configuration in MongoDB. However, there are some limitations to what you can do with aggregations in a synced realm. 

Aggregations can only be performed on the client side, which means you can't perform server-side aggregations. Additionally, some aggregation operators are not supported in synced realms. For example, `$group`, `$lookup`, `$graphLookup`, `$geoNear`, and `$out` are not supported. 

In your example, the `$match`, `$unwind`, and `$project` aggregation stages are all supported in synced realms, so you should be able to use them without any issues. However, keep in mind that the aggregation will be performed on the client side, so you'll need to consider the performance implications of that. 

Also, note that the `ObjectId` type is not supported in the flexible sync configuration. You'll need to use a different type, such as `string`, to represent object IDs in your queries.

IIt depends on the specific configuration and data being used. However, I can give you an example of using aggregation functions in MongoDB Realm flexible sync:

Suppose you have a collection called "orders" that contains documents with the following structure:

```
{
  "_id": ObjectId("615b4ec211ea0c7b5c5fa5f3"),
  "customerId": ObjectId("615b4eaa11ea0c7b5c5fa5f2"),
  "items": [
    { "name": "item1", "price": 10 },
    { "name": "item2", "price": 15 }
  ]
}
```

And you want to calculate the total price of all orders for a specific customer. You can use the following pipeline:

```
[
  { $match: { "customerId": ObjectId("615b4eaa11ea0c7b5c5fa5f2") } },
  { $unwind: "$items" },
  { $group: { _id: null, total: { $sum: "$items.price" } } }
]
```

This pipeline filters the documents to match the customer ID, unwinds the "items" array to create a document for each item, and groups the documents by a constant value (null) and calculates the sum of the "price" field in each document. The result will be a single document with the total price of all items for the selected customer.

To use this pipeline in MongoDB Realm flexible sync, you can define a realm function that runs the pipeline:

```
exports.getTotalPriceForCustomer = async function(customerId) {
  const orders = context.services.get("mongodb-atlas").db("mydb").collection("orders");
  const pipeline = [
    { $match: { "customerId": customerId } },
    { $unwind: "$items" },
    { $group: { _id: null, total: { $sum: "$items.price" } } }
  ];
  const result = await orders.aggregate(pipeline).toArray();
  return result[0].total;
}
```

This function uses the "mongodb-atlas" service to access the "orders" collection and runs the pipeline using the `aggregate` method. The result is returned as a single number (the total price). You can then call this function from your client application to get the result:

```
const mongodb = realmApp.currentUser.mongoClient("mongodb-atlas");
const orders = mongodb.db("mydb").collection("orders");
const totalPrice = await realmApp.functions.getTotalPriceForCustomer(orders, customerId);
console.log(`Total price: ${totalPrice}`);
```

**Comment by nielsenko** [comment]
@RedFox64 I have deleted some ChatGPT nonsense that was added as a reply and closed the issue for discussion.
