### ISSUE TITLE
cancel the manage state of RealmEntity

### ISSUE THREAD

**Issue by SUNbrightness** [realm/realm-dart#1253]
### Problem

I have some experience of  Java and Android. As far as know, the following are allowed.
`var person = Person('Lucas');
  realm.write(() => {
    realm.add(person)
  });
// isManaged now can't change, following just is a way of I'm thinking
  person.isManaged = false;
  person.name = 'Mark';

  realm.write(() => realm.add(person,update: true));`
when I get entity from database，I modify some properties then update it using transaction。
But when I just want to change it's properties without database. there are wrong.

RealmException: Error setting property Person.name Error: RealmException: Error code: 2005 . Message: Trying to modify database while in read transaction

### How important is this improvement for you?

I would like to have it but have a workaround

### Feature would mainly be used with

Local Database only

**Comment by SUNbrightness** [comment]
I think the design pattern I mentioned above。
Conducive to the cohesion of the realm。
most dart can't quote the realm, they can design a util class used operating realm， rather than there are all realm quotes in my project

**Comment by SUNbrightness** [comment]
I think the design pattern I mentioned above。
Conducive to the cohesion of the realm。
most dart can't quote the realm, they can design a util class used operating realm， rather than there are all realm quotes in my project

**Comment by blagoev** [comment]
Hi,
Once an object is managed it can not be reverted back to unmanaged one. You can create another unmanaged object from your managed one using a custom factory constructor for example.

closing this issue since the behavior is per design.
