### ISSUE TITLE
defaultConfiguration

### ISSUE THREAD

**Issue by shinriyo** [realm/realm-dart#1255]
### Problem

```
  final config = Realm.Configuration.defaultConfiguration;
  final realm = Realm(config);
```

### Solution

Swift `let realmURL = Realm.Configuration.defaultConfiguration`

Add add defaultConfiguration to dart.

### Alternatives

pick up from `flutter_realm`
https://pub.dev/documentation/flutter_realm/latest/flutter_realm/Configuration/defaultConfiguration-constant.html

### How important is this improvement for you?

I would like to have it but have a workaround

### Feature would mainly be used with

Local Database only

**Comment by blagoev** [comment]
Hi, we have plans to support this in the future. Please follow this issue https://github.com/realm/realm-dart/issues/75

closing this one as duplicate.

**Comment by shinriyo** [comment]
@blagoev Thank you!
