### ISSUE TITLE
toMap method

### ISSUE THREAD

**Issue by shinriyo** [realm/realm-dart#1256]
### Problem

I want the `toMap` method.

you have a generator.
but it doesn't make `toMap` method.

Do you know `DynamicRealm`?

```
realm.dynamic.all('TableName');
```

The returned object can't cast TableClass....

cast as `dynamic` and access.
it is also not good.a 

### Solution

making `toMap` methods when generate.

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by shinriyo** [comment]
`realm_generator`

**Comment by shinriyo** [comment]
Ah. is it a generator option?
Thank you for replying.

**Comment by shinriyo** [comment]
I read the document.
Why are they different names?

why is it `_id`? not just `id`.
```
@MapTo("_id")
late ObjectId id;
```


and why is it a different name? 
I guess `_Boat` is `Boat`. just `Boat` is better. or should I use different name?
```
@MapTo('naval_ship')
class _Boat {
```

**Comment by nirinchev** [comment]
What is the use case for converting from strongly-typed objects to and from a `Map`? Generally, our expectation is that people prefer to use model classes rather than an untyped data structure, but perhaps we're missing something?

**Comment by shinriyo** [comment]
I'd like to convert to json file and back up realm as zip file for uploading.

**Comment by desistefanova** [comment]
We suggest defining realm models using underscore like `_Boat`, because the name `Boat` will be generated by the realm generator and you will be able to access the generated class from your application.
```dart
@MapTo('naval_ship')
class _Boat {
```
In your case 'naval_ship' will be the name of the table into the realm file that is associated to the class _Boat.

**Comment by desistefanova** [comment]
You can also zip and upload the `.realm` file as it is. It can be opened with the [Realm Studio](https://www.mongodb.com/docs/realm/studio/install/).
Does this work for you?

**Comment by shinriyo** [comment]
I use Realm Studio. But I want to convert on iPhone/Android apps which developed by Flutter.

**Comment by shinriyo** [comment]
I can get the property's name and type by a table's schema.
Flutter can't use a mirror so I can't access the value by indexing(`[]`).
Google prepared `reflectable` package. but It should put `@Reflector()` annotations in the class.
https://pub.dev/packages/reflectable

Realm's table classes was built by command line and I can't put `@Reflector()`

**Comment by desistefanova** [comment]
If I got it correctly you want to get the value of each property of the realm objects.
Did you already try the dynamic that you mentioned at the beginning?
```dart
 final dynamicRealm = Realm(config);
        final cars = dynamicRealm.dynamic.all(Car.schema.name);
        for (var car in cars) {
          for (var prop in Car.schema.properties) {
            print("${prop.name}: ${car.dynamic.get<String>(prop.name)}");
          }
        }
```
Does this sample work for your case?
Unfortunately, we still don't support json serialisation, but it is planned to be done.
If this is not what you need, please share some sample of your code.

**Comment by shinriyo** [comment]
Wow!
I didn't know `car.dynamic.get<String>(prop.name)` method.
Thank you.

**Comment by shinriyo** [comment]
`prop` type is not always `String`.

```
if (RealmPropertyType.string == prop.propertyType) {
  print("${prop.name}: ${car.dynamic.get<String>(prop.name)}");
} else if (RealmPropertyType.int == prop.propertyType) {
  print("${prop.name}: ${car.dynamic.get<int>(prop.name)}");
} else .. bla bla
}
```

or remove `<String>` is okey?
like this
```
print("${prop.name}: ${car.dynamic.get(prop.name)}");
```

**Comment by desistefanova** [comment]
Yes, you can remove the generic type.
I hope this solves the issue that you had. 
I'm closing this issue.
