### ISSUE TITLE
Embedded objects do not appear to sync

### ISSUE THREAD

**Issue by n-doton** [realm/realm-dart#1257]
### What happened?

When adding an embedded object as a property to a RealmModel, the embedded object does not appear to sync resulting in the property returning null when accessed in our Flutter application.

The embedded object is confirmed to be populated in Atlas.

When another collection was configured to include embedded objects, other collections do not sync at all until their Realm schema is updated to remove the embedded object, a sync is performed, and the embedded object is re-added to the schema. The collection then syncs, but the embedded object is still missing.

Are we defining and accessing things properly or could we have missed something?

Thanks in advance.

### Repro steps

1. Define a collection with an embedded object
2. Sync collection in Flutter
3. Attempt to read a property from the embedded object in a document from the collection

### Version

Dart 2.16.6 | Flutter 3.7.12

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

MacOS Ventura 13.3.1

### Code snippets

Collection schema example with embedded collection:
```json
{
  "title": "Collection",
  "type": "object",
  "required": [
    "_id"
  ],
  "properties": {
    "_id": {
      "bsonType": "objectId"
    },
    "embedded_object": {
      "title": "Embedded Object",
      "bsonType": "object",
      "required": [
        "property_1"
      ],
      "properties": {
        "property_1": {
          "bsonType": "bool"
        },
        "property_2": {
          "bsonType": "string"
        }
      }
    }
  }
}
```

RealmModels in Flutter:
```dart
@RealmModel()
@MapTo("Collection")
class _Collection {

  @PrimaryKey()
  @MapTo("_id")
  late ObjectId id;

  @MapTo("property_1")
  late String property1;

  @MapTo("embedded_object")
  _EmbeddedObject? embeddedObject;
}

@RealmModel(ObjectType.embeddedObject)
@MapTo("Embedded Object")
class _EmbeddedObject {

  @MapTo("property_1")
  late String property1;

  @MapTo("property_2")
  String? property2;
}
```

Adding collections to flexible sync configuration:
```dart
final Configuration configuration = Configuration.flexibleSync(
  user,
  <SchemaObject>[
    Collection.schema,
    EmbeddedObject.schema,
  ],
);
```

Subscribing to changes:
```dart
realm.subscriptions.update((final MutableSubscriptionSet mutableSubscriptions) {
  mutableSubscriptions.add(realm.all<Collection>(), name: Collection.schema.name);
});
```

Attempting to read embedded object:
```dart
final Collection collection = realm.query<Collection>("_id == oid($id)").first;

// This is null
print(collection.embeddedObject);
```

Attempting to query embedded object:
```dart
// This does not return any documents
final example = realm.query<Collection>("embedded_object.property_2 == 'example'");
```

**Comment by nielsenko** [comment]
Are you sure the `Collection` was not constructed without a `EmbeddedObject`? When it comes to sync, one if the benefits of using embedded objects is exactly that they are pulled in together with their parent.

**Comment by n-doton** [comment]
@nielsenko Sorry, this seemed to be a mistake on our end! We just found we have additional fields in our embedded Realm model that weren't present in our device sync schema which was causing the problem.
