### ISSUE TITLE
insert from map with table name string.

### ISSUE THREAD

**Issue by mkbsugita** [realm/realm-dart#1260]
### Problem

I have map data.
`Map<String, dynamic>`

```
{
  'name': 'sugi',
  'age': 11
}
```

And I want to insert the data with table name or SchemaObject's instance.

for example it is `Person` table
I want to make `Person` instance and insert it.

### How important is this improvement for you?

Dealbreaker

### Feature would mainly be used with

Local Database only

**Comment by desistefanova** [comment]
Hi @mkbsugita ,
You can use this suggestion if I correctly understand your case:
```dart
    var config = Configuration.local([Person.schema]);
    var realm = getRealm(config);

    final map = <String, dynamic>{'name': 'sugi', 'age': 11};
    var person = Person();
    map.forEach((key, dynamic value) => RealmObjectBase.set(person, key, value));
    realm.write(() => realm.add(person));
```

You can have and empty constructor if you define your model with default values:
```dart
@RealmModel()
class _Person {
  late String name = "";
  late int age = 0;
}
```

We are going to support json deserialization, but for now you can use this way.

**Comment by mkbsugita** [comment]
@desistefanova Thank you for replying always.

I want to make this dynamically `Person` instance by using `Person.scheme` or class name.
Is it possible?

```
    final map = <String, dynamic>{'name': 'sugi', 'age': 11};
    // var person = Person(); // <= I want to make this dynamically this instance
    map.forEach((key, dynamic value) => RealmObjectBase.set(person, key, value));
    realm.write(() => realm.add(person));
```

`_Person` is defined and `Person` class is already generated.

I think you think what use case do we need.
I want to recover data from json data.

**Comment by desistefanova** [comment]
On this stage we don't provide an external method for creating objects by the name of the class.
Json serialization/deserialization is in our to do list.
I would suggest you to create some factory that to initialize the objects by name.
Something like:
```dart
  RealmObjectBase? getInstanceOf(String className) {
    switch (className) {
      case "Person":
        return Person();
        break;
      default:
        return null;
    }
  }
```

**Comment by desistefanova** [comment]
I made a simple suggestion for exposing some additional methods for achieving this task. But you can really go with the factory method for now.

**Comment by mkbsugita** [comment]
Unfortunately if `Person` has primary key it can't...

**Comment by desistefanova** [comment]
We are working on supporting `EJson` serialization/deserialization in this [PR](https://github.com/realm/realm-dart/pull/1295). This will cover the issue with the primary keys and ObjectIds. 
I'm closing this issue.
