### ISSUE TITLE
Can't build iOS app using a mirror server for dependencies

### ISSUE THREAD

**Issue by michaelferwer** [realm/realm-dart#1263]
### What happened?

Hello everyone,

We are using a mirror server to get dependencies to build our flutter app.
We have followed the [official documentation](https://dart.dev/tools/pub/environment-variables) to setup the mirror server with dart.

We have introduced realm into our app and we are facing an issue when we want to run on iOS :

    The pubspec.yaml file has changed since the pubspec.lock file was generated, please run "flutter pub get" again.
    pub finished with exit code 65

This error is coming from the build phase '[CP-User] Download Realm Flutter iOS Binaries'

When we remove the configuration, getting dependencies from pub.dev, and build the iOS app is working fine.

I'm wondering if the command `flutter pub run realm install` during this build phase, does not use the mirror configuration.

Versions :

Flutter 3.7.12
Dart 2.19.6
Xcode 14.3
cocoapods 1.12.1

### Repro steps

1. Setup a mirror server
2. flutter pub get
3. launch the app in an IDE

### Version

1.0.3

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

iOS 11

### Stacktrace of the exception/crash you're getting

```shell
The pubspec.yaml file has changed since the pubspec.lock file was generated, please run "flutter pub get" again.
pub finished with exit code 65
```

**Comment by nielsenko** [comment]
`flutter pub run realm install` doesn't contact the pub server, but downloads the appropriate binaries from S3. It doesn't change the `pubspec.yaml` file in any way.

Out of curiosity, why not just run `flutter pub get` to fix it, as suggested by the error message?

**Comment by michaelferwer** [comment]
I try to run `flutter pub get` and build but that does not solve the problem in my case.

**Comment by nielsenko** [comment]
What mirror are you using?

**Comment by michaelferwer** [comment]
We are using a private instance of Artifactory.

**Comment by nielsenko** [comment]
I assume we are talking about JFrog's Artifactory. I don't have experience with this, but if you can give me read access? I can try setup a test project that downloads realm from your private artifactory.

**Comment by nielsenko** [comment]
Are you by any chance also using melos?

**Comment by michaelferwer** [comment]
I confirm, the problem was due to bad propagation of environments variables to Intelllij or VScode.
I was never facing this issue before integrating realm. 
May be the dart command check something even if it's not downloading as you said.

Do you think it could be interesting to add this point to a troubleshooting section or something like that ?

**Comment by nielsenko** [comment]
Well, people will likely find this issue if they experience something similar. I'm reluctant to add anything to the official docs until we understand the issue better, and realms role in it. But glad you got it working 🎉
