### ISSUE TITLE
deleteAll error

### ISSUE THREAD

**Issue by mkbsugita** [realm/realm-dart#1266]
### What happened?

A bug happened!

```
Realm error : Object type RealmObject not configured in the current Realm's schema. Add type RealmObject to your config before opening the Realm
```

### Repro steps

just call
```
realm.deleteAll();
```

I set `schemaObjects`for all `schema`.

### Version

1.0.3

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

iOS 15.5

**Comment by nielsenko** [comment]
You need to pass the type like `realm.deleteAll<X>()` otherwise it falls back to the type constraint, ie. `RealmObject` which was not provisioned when opening the realm. I agree the error message could be more informative in this case

**Comment by mkbsugita** [comment]
@nielsenko 
Thank you for your quick response.

I want to delete all tables in the db?

or I defined schemas like this.
Can I use the list for `deleteAll` method?

```
  static List<SchemaObject> schemaObjects = [
    Hoge.schema,
    Bar.schema,
    Fuga.schema,
  ];
```

**Comment by nielsenko** [comment]
No. If you just want to delete everything it is better to just delete the realm file with `Realm.deleteRealm(config.path)`. You need to ensure the realm is not opened when you do this.

**Comment by Falliot** [comment]
@nielsenko you Rock 😎 Thanks :)
