### ISSUE TITLE
Ability to change output directory for generated files

### ISSUE THREAD

**Issue by dannyglover** [realm/realm-dart#1273]
### Problem

I want to put my generated part files (e.g. `*.g.dart`) files into a `generated` folder. Doing `part 'generated/myclass.g.part'` does not work, and the generator gives the following warning:

`myclass.g.dart must be included as a part directive in the input library with: part 'myclass.g.dart';`

If the ability to output to a custom directory already exists, I couldn't seem to find any reference to it in the documentation.

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by nielsenko** [comment]
The `dart run realm generate` command is just a convenient a front to `build_runner`, as I guess you already know. What you want is to setup where `source_gen` combines the output. I suggest you look at Simon Binders blog post about the same: https://simonbinder.eu/posts/build_directory_moves/

**Comment by dannyglover** [comment]
> The `dart run realm generate` command is just a convenient front to `build_runner`, as I guess you already know. What you want is to setup where `source_gen` combines the output. I suggest you look at Simon Binders blog post about the same: https://simonbinder.eu/posts/build_directory_moves/

Thanks for the link. Your advice resulted in my issue being resolved. 
Thank you very much for the information.

**Comment by nielsenko** [comment]
Actually, to make it easy for all who follows, you probably want a `build.yaml` file that looks like this:
```yaml
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'
```
but the blog post above will help you understand why.
