### ISSUE TITLE
Date between queries throwing exception

### ISSUE THREAD

**Issue by dannyglover** [realm/realm-dart#1276]
### What happened?

Trying to implement the dart query BETWEEN results in the exception I've listed below. I've also tried doing `'date >= ${startDate.toUtc()} AND date <= ${endDate.toUtc()}'` which results in the same error. Which leads me to believe queries using DateTime are broken.

exception has occurred.
RealmException (RealmException: Error code: 3008 . Message: Invalid predicate: 'date BETWEEN{2023-05-12 17:27:00.000Z, 2023-05-12 17:29:00.000Z}': syntax error, unexpected number, expecting ',' or '}')

### Repro steps

1) Try the query listed in the code snippets section
2) Observe the runtime exception that occurs

### Version

3.0/3.10

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

Pop OS 22.04

### Code snippets

```dart
var startDate = DateTime(2023, 5, 12, 18, 27);
var endDate = DateTime(2023, 5, 12, 18, 29);

RealmResults query = realm.query("date BETWEEN{${startDate.toUtc()}, ${endDate.toUtc()}}");
```

### Stacktrace of the exception/crash you're getting

```shell
exception has occurred.
RealmException (RealmException: Error code: 3008 . Message: Invalid predicate: 'date BETWEEN{2023-05-12 17:27:00.000Z, 2023-05-12 17:29:00.000Z}': syntax error, unexpected number, expecting ',' or '}')
```

**Comment by dannyglover** [comment]
Edit: Solved. This answer got me on the right track: https://stackoverflow.com/a/74957004
It'd be great if the query syntax page got a few more examples to make these things a little clearer.

**Comment by nirinchev** [comment]
What page is that - is it https://www.mongodb.com/docs/realm/realm-query-language/ ? I can see that most example do use argument substitution but the comparison section indeed doesn't.

**Comment by dannyglover** [comment]
> What page is that - is it https://www.mongodb.com/docs/realm/realm-query-language/ ? I can see that most example do use argument substitution but the comparison section indeed doesn't.

That's the page I was referencing yeah.

**Comment by nirinchev** [comment]
Thanks, I added a docs ticket to improve it (can't link to it since it's in private Jira).

**Comment by nfadhil13** [comment]
> Edit: Solved. This answer got me on the right track: https://stackoverflow.com/a/74957004 It'd be great if the query syntax page got a few more examples to make these things a little clearer.

Can you show me the query string please ? I am facing the same issue rn
