### ISSUE TITLE
Limit query fails when using argument substitution

### ISSUE THREAD

**Issue by dannyglover** [realm/realm-dart#1277]
### What happened?

When running a realm query making use of the LIMIT option, I ran into the issue stated below.

### Repro steps

Run the following query

```dart
// fails
int limit = 2;
realm.query(r"name == $0 SORT(age DESC) LIMIT($1)", ["bob", limit]);
```

The following exception is thrown:

```
Exception has occurred.
RealmException (RealmException: Error code: 3008 . Message: Invalid predicate: 'name == $0 SORT(age DESC) LIMIT($1)': syntax error, unexpected argument, expecting natural0)
```

### Version

3.0/3.10

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

Pop OS 22.04

### Code snippets

```dart
// fails
int limit = 2;
realm.query(r"name == $0 SORT(age DESC) LIMIT($1)", ["bob", limit]);
```

An adjacent string works however

```dart
// works
int limit = 2;
realm.query(r"name == $0 SORT(age DESC)" " LIMIT($limit)", ["bob"]);
```

**Comment by nirinchev** [comment]
Right, argument substitution only works for arguments you pass to the filter clause and not for the sort/limit clauses.

I realize it may be a little annoying having to mix string interpolation and argument substitution in the case where you want to pass the limit value as a parameter, but that's how it works today and we don't have short-term plans to change it.
