### ISSUE TITLE
Unable to add realm as a dependency due to http dependency conflict

### ISSUE THREAD

**Issue by botraunak** [realm/realm-dart#1326]
### What happened?

While adding realm as a dependency to the project, pub complains due to conflict with the http dependency

### Repro steps

Add google fonts package as a dependency or any other package that depends on http 
Add the realm package
Error

### Version

Dart SDK version: 3.0.5, Flutter 3.10.5 • channel stable

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

Both

### Relevant log output

```shell
flutter pub get
Resolving dependencies...
Because no versions of realm match >1.2.0 <2.0.0 and realm 1.2.0 depends on http ^0.13.4, realm ^1.2.0 requires http ^0.13.4.
And because google_fonts >=4.0.5 depends on http ^1.0.0, realm ^1.2.0 is incompatible with google_fonts >=4.0.5.
So, because realm_test depends on both google_fonts ^5.1.0 and realm ^1.2.0, version solving failed.
exit code 1
```
```

**Comment by botraunak** [comment]
fixed it locally for now by overriding the http depedency in my project
```
dependency_overrides:
  http: ^1.0.0
```

**Comment by desistefanova** [comment]
Hi @botraunak, 
we really appreciate that you have reported this issue!
We will fix it. Thank you!
