### ISSUE TITLE
Embedded object referencing itself within a property

### ISSUE THREAD

**Issue by dotjon0** [realm/realm-dart#1333]
### What happened?

We referenced an embedded object to reference itself again, however we are getting this error "Cycles containing embedded objects are not currently supported".  We guess this is not supported, so we will have to create $CatShowMetric2 which is the same as $CatShowMetric to achieve what we want to do? Please see 

List<$CatShowMetric> moreShowMetrics = <$CatShowMetric>[];

Here is an example of the code structure:

```
@RealmModel()
class _Cat {

  @PrimaryKey()
  late ObjectId id;
  late String catName;
  late List<$CatShow> catShows;
}
  
@RealmModel(ObjectType.embeddedObject)
class $CatShow {

  late ObjectId showId;
  late String showName;
  late $CatShowDetails showDetails;
  List<$CatShowMetric> showMetrics = <$CatShowMetric>[];
}

@RealmModel(ObjectType.embeddedObject)
class $CatShowDetails {

  late String county;
  late String country;
}

@RealmModel(ObjectType.embeddedObject)
class $CatShowMetric {

  late int score;
  late String judge;
  List<$CatShowMetric> moreShowMetrics = <$CatShowMetric>[];
}
  
```

### Repro steps

See above

### Version

1.3.0

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

macOS 13.4.1

**Comment by nielsenko** [comment]
@dotjon0 I'm afraid my best advice is to avoid making `$CatShowMetric` embedded.

I know that is not a super good story with respect to sync, as it it will require you to handle subscriptions for `$CatShowMetric` as well.

I will bring this up internally to hear if this restriction is likely to be lifted.

**Comment by nielsenko** [comment]
Yes, as long as you avoid the cycle between embedded models (here `$CatShowMetric` referencing itself via `moreShowMetrics`) you are fine. 

I have checked internally, and it is not a restriction we are likely to lift in the near future.

**Comment by nielsenko** [comment]
Yes that should work. It is the cycles we don't like. I'm not aware of any limits to the allowed nesting, except the obvious such as space is finite, and `size_t` has fixed width, etc. I'll get back if I'm mistaken. 

But in general, if you find yourself using many classes with few instances of each, it seems like a code-smell to me. There is an overhead associated with each class (like there is with tables in a relational db).

**Comment by nielsenko** [comment]
There is 64K limit on number of realm model classes.

**Comment by nielsenko** [comment]
There is also limits [serverside](https://www.mongodb.com/docs/manual/reference/limits/#mongodb-limit-Nested-Depth-for-BSON-Documents). Nesting cannot exceed 100 on MongoDB.

**Comment by dotjon0** [comment]
This is all perfect, thanks so much for clarifying @nielsenko and being soooo helpful once again! Very appreciated.
