### ISSUE TITLE
build_runner conflict with dart run realm generate

### ISSUE THREAD

**Issue by dotjon0** [realm/realm-dart#1334]
### What happened?

Hi, we have implemented a `custom build` via `build_runner`, however when we run `dart run realm generate` this also triggers our `custom build`... `dart run realm generate` then fails to build.

So our question is, what is the best approach for running `build_runner` independently, so we can run our `custom build` and  `dart run realm generate` independently so there are no conflicts please?

### Repro steps

see above

### Version

3.3.9

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

macOS 13.4.1

**Comment by nielsenko** [comment]
Hi @dotjon0 

`dart run realm generate` is just a wrapper around `dart run builder_runner build`. 

You can configure behaviour with `build.yaml`.

**Comment by dotjon0** [comment]
thanks @nielsenko, appreciated
