### ISSUE TITLE
Unable to sync Realm with device sync due to schema mismatch error

### ISSUE THREAD

**Issue by erdzan12** [realm/realm-dart#1347]
### What happened?

**Description:**
I am currently using Realm with Flutter, specifically version 1.2.0, and I am encountering an issue with the device sync feature of Realm. My application utilizes a model with nested objects, retrieved from the device sync feature on MongoDB Atlas.

The model classes I'm using are as follows:

```dart
@RealmModel()
@MapTo('firstmod')
class _Firstmod {
  @PrimaryKey()
  @MapTo('_id')
  ObjectId? id;

  @MapTo('__v')
  int? v;

  _FirstmodSecond? second;
}

@RealmModel(ObjectType.embeddedObject)
@MapTo('firstmod_second')
class _FirstmodSecond {
  _FirstmodSecondThird? third;
}

@RealmModel(ObjectType.embeddedObject)
@MapTo('firstmod_second_third')
class _FirstmodSecondThird {
  _FirstmodSecondThirdFourth? fourth;
}

@RealmModel(ObjectType.embeddedObject)
@MapTo('firstmod_second_third_fourth')
class _FirstmodSecondThirdFourth {
  _FirstmodSecondThirdFourthFifth? fifth;
}

@RealmModel(ObjectType.embeddedObject)
@MapTo('firstmod_second_third_fourth_fifth')
class _FirstmodSecondThirdFourthFifth {
  _FirstmodSecondThirdFourthFifthSixth? sixth;
}

@RealmModel(ObjectType.embeddedObject)
@MapTo('firstmod_second_third_fourth_fifth_sixth')
class _FirstmodSecondThirdFourthFifthSixth {
  _FirstmodSecondThirdFourthFifthSixthSeventh? seventh;
}

@RealmModel(ObjectType.embeddedObject)
@MapTo('firstmod_second_third_fourth_fifth_sixth_seventh')
class _FirstmodSecondThirdFourthFifthSixthSeventh {
  _FirstmodSecondThirdFourthFifthSixthSeventhEight? eight;
}

@RealmModel(ObjectType.embeddedObject)
@MapTo('firstmod_second_third_fourth_fifth_sixth_seventh_eight')
class _FirstmodSecondThirdFourthFifthSixthSeventhEight {
  _FirstmodSecondThirdFourthFifthSixthSeventhEightNinth? ninth;
}

@RealmModel(ObjectType.embeddedObject)
@MapTo('firstmod_second_third_fourth_fifth_sixth_seventh_eight_ni')
class _FirstmodSecondThirdFourthFifthSixthSeventhEightNinth {
  String? text;
}
```

In order to fit within the 57-character limit for class names, I have modified the `MapTo` decorator for each class.

However, despite these modifications, I am unable to start the application and sync with Realm using device sync. I consistently encounter the following error:

```
Error integrating bootstrap changesets: Failed to transform received changeset: Schema mismatch: Link property 'ninth' in class 'firstmod_second_third_fourth_fifth_sixth_seventh_eight' points to class 'firstmod_second_third_fourth_fifth_sixth_seventh_eight_ni' on one side and to 'firstmod_second_third_fourth_fifth_sixth_seventh_eight_ninth' on the other.
```

It seems that there is a schema mismatch between the link property 'ninth' in class 'firstmod_second_third_fourth_fifth_sixth_seventh_eight' and 'firstmod_second_third_fourth_fifth_sixth_seventh_eight_ninth'.

I suspect that there might be a bug or an issue with handling nested objects and the modified `MapTo` decorators. It's worth noting that I

 create the schema in the app services using the "generate schema" feature, which is based on the documents present in the corresponding collection.

### Repro steps
Here is also a demo flutter app with this issue:
https://github.com/erdzan12/realm_sync_issue

1. Create a Flutter project with Realm integration.
2. Define the model classes with nested objects, including `_Firstmod`, `_FirstmodSecond`, `_FirstmodSecondThird`, `_FirstmodSecondThirdFourth`, `_FirstmodSecondThirdFourthFifth`, `_FirstmodSecondThirdFourthFifthSixth`, `_FirstmodSecondThirdFourthFifthSixthSeventh`, `_FirstmodSecondThirdFourthFifthSixthSeventhEight`, `_FirstmodSecondThirdFourthFifthSixthSeventhEightNinth`.
3. Modify the `MapTo` decorator for each class to fit within the 57-character limit.
4. Set up the necessary dependencies and configurations for Realm and device sync in your Flutter project.
5. Start the application and initiate the sync with Realm using device sync.
6. Observe the error message mentioned above.
```
Error integrating bootstrap changesets: Failed to transform received changeset: Schema mismatch: Link property 'ninth' in class 'firstmod_second_third_fourth_fifth_sixth_seventh_eight' points to class 'firstmod_second_third_fourth_fifth_sixth_seventh_eight_ni' on one side and to 'firstmod_second_third_fourth_fifth_sixth_seventh_eight_ninth' on the other.
```

### Version

1.3.0

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

Android 10

### Code snippets

https://github.com/erdzan12/realm_sync_issue

### Relevant log output
```
Error integrating bootstrap changesets: Failed to transform received changeset: Schema mismatch: Link property 'ninth' in class 'firstmod_second_third_fourth_fifth_sixth_seventh_eight' points to class 'firstmod_second_third_fourth_fifth_sixth_seventh_eight_ni' on one side and to 'firstmod_second_third_fourth_fifth_sixth_seventh_eight_ninth' on the other.
```

**Comment by desistefanova** [comment]
Hi @erdzan12!
I suppose that an old version of `realm `is downloaded on your side, since you have configured 
```
environment:
  sdk: ">=2.19.6 <3.0.0"
```
Could you please try to set the following in your` pubspec.yaml`?
```
environment:
  sdk: ^3.0.2
```
and be sure your flutter is upgraded.

**Comment by erdzan12** [comment]
Hi, @desistefanova still the same issue

**Comment by desistefanova** [comment]
It seems that there is difference between the schema on the server and the schema of the local realm file.
Did you try to terminate the Device sync after you did the change and then to enable it again?

**Comment by erdzan12** [comment]
When using for example a demo node backend, to add this data to mongodb

```
export class Ninth {
  id?: string;
  text!: string;
}

export class Eighth {
  id?: string;
  @Prop()
  ninth!: Ninth;
}

export class Seventh {
  id?: string;
  @Prop()
  eighth!: Eighth;
}

export class Sixth {
  id?: string;
  @Prop()
  seventh!: Seventh;
}

export class Fifth {
  id?: string;
  @Prop()
  sixth!: Sixth;
}

export class Fourth {
  id?: string;
  @Prop()
  fifth!: Fifth;
}

export class Third {
  id?: string;
  fourth!: Fourth;
}

export class Second {
  id?: string;
  @Prop()
  third!: Third;
}

@Schema()
export class Firstmod {
  id?: string;
  @Prop()
  second!: Second;
}

export const FirstmodSchema = SchemaFactory.createForClass(Firstmod);
```

And I let the scheme be defined by letting it analyse the data in the collection
<img width="256" alt="image" src="https://github.com/realm/realm-dart/assets/32931186/b457ab3d-3fcd-4bcc-97bf-19d0578e7c1c">

I get following schema:
```
{
  "title": "firstmod",
  "properties": {
    "__v": {
      "bsonType": "int"
    },
    "_id": {
      "bsonType": "objectId"
    },
    "second": {
      "bsonType": "object",
      "properties": {
        "third": {
          "bsonType": "object",
          "properties": {
            "fourth": {
              "bsonType": "object",
              "properties": {
                "fifth": {
                  "bsonType": "object",
                  "properties": {
                    "sixth": {
                      "bsonType": "object",
                      "properties": {
                        "seventh": {
                          "bsonType": "object",
                          "properties": {
                            "eighth": {
                              "bsonType": "object",
                              "properties": {
                                "ninth": {
                                  "bsonType": "object",
                                  "properties": {
                                    "text": {
                                      "bsonType": "string"
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

After that under the Sync Models tab the proposed models for flutter is (only now for _FirstmodSecondThirdFourthFifthSixthSeventhEighthNinth)
```
import 'package:realm/realm.dart';
--
part 'realm_models.g.dart';
 
// NOTE: These Realm models are private and therefore should be copied into the same .dart file.
 
@RealmModel(ObjectType.embedded)
@MapTo('firstmod_second_third_fourth_fifth_sixth_seventh_eighth_ninth')
class _FirstmodSecondThirdFourthFifthSixthSeventhEighthNinth {
String? text;
}
```

Where there, the limit of 57 chars is also not respected.
Does this mean that I have to pay attention in general about nested data so that it fits in the 57 chars limit, I don't see how I can change the server schema so that it can match the local realm file, and still that the server schema refers to data to the respective collection data (changing ninth to nin)

**Comment by desistefanova** [comment]
The limitation of 57 symbols is required only by the core implementation of realm SDKs used by the client. That's why the server doesn't respect this limitation.

**Comment by erdzan12** [comment]
Great thanks a lot, did not knew about the "title" field which is used for the mapping, it works now thanks

**Comment by erdzan12** [comment]
Maybe it would be interesting that the atlas schema generation creates a corresponding title for the schema, but I only saw that the 57 char limitation is for Flutter and Android?
