### ISSUE TITLE
Incorrect schema generation for Realm models in Flutter

### ISSUE THREAD

**Issue by erdzan12** [realm/realm-dart#1348]
### What happened?

I have encountered an issue with the schema generation for Realm models in Flutter. When using the app services to generate the schema for Flutter, the generated code contains a discrepancy in the `ObjectType` for embedded objects.

The generated code is as follows:

```dart
import 'package:realm/realm.dart';
part 'realm_models.g.dart';

@RealmModel()
@MapTo('firstmod')
class _Firstmod {
  @PrimaryKey()
  @MapTo('_id')
  ObjectId? id;

  @MapTo('__v')
  int? v;

  _FirstmodSecond? second;
}

@RealmModel(ObjectType.embedded)
@MapTo('firstmod_second')
class _FirstmodSecond {
  _FirstmodSecondThird? third;
}
```

However, the correct code should be:

```dart
import 'package:realm/realm.dart';
part 'realm_models.g.dart';

@RealmModel()
@MapTo('firstmod')
class _Firstmod {
  @PrimaryKey()
  @MapTo('_id')
  ObjectId? id;

  @MapTo('__v')
  int? v;

  _FirstmodSecond? second;
}

@RealmModel(ObjectType.embeddedObject)
@MapTo('firstmod_second')
class _FirstmodSecond {
  _FirstmodSecondThird? third;
}
```

As you can see, there is a discrepancy in the `ObjectType` for the `_FirstmodSecond` class. It should be `embeddedObject` instead of `embedded`.

This inconsistency in the generated code can lead to issues when working with embedded objects in Realm models.

**Additional Information:**
- The correct `ObjectType` for embedded objects in Realm models is `embeddedObject`.
- The discrepancy in the generated code can cause issues when working with embedded objects in Realm models.

Thank you for your attention to this matter. Please let me know if you require any further information.

### Repro steps

**Steps to Reproduce:**
1. Use the app services to generate the schema for Flutter Realm models.
2. Observe the generated code and check the `ObjectType` for embedded objects.

**Expected Behavior:**
The generated code should correctly set the `ObjectType` to `embeddedObject` for embedded objects in Realm models.

**Actual Behavior:**
The generated code incorrectly sets the `ObjectType` to `embedded` for embedded objects in Realm models.

### Version

1.2.0

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### What type of application is this?

Flutter Application

### Client OS and version

Android

**Comment by desistefanova** [comment]
Hi @erdzan12!
Thank you for reporting this issue! We appreciate it.
Based on your report we created a private ticket for the app service team and it will be handle in some of the next Atlas UI releases!
I'm closing the issue.
