### ISSUE TITLE
ObjectId.getTimestamp()

### ISSUE THREAD

**Issue by dotjon0** [realm/realm-dart#1349]
### Problem

To support ObjectId.getTimestamp() as in MongoDB NodeJS ObjectId

### Solution

see above

### Alternatives

see above

### How important is this improvement for you?

I would like to have it but have a workaround

### Feature would mainly be used with

Atlas Device Sync

**Comment by nirinchev** [comment]
You can use `ObjectId.timestamp` to get the timestamp portion of the object id.

**Comment by dotjon0** [comment]
Fantastic, must have missed this. Thanks so much @nirinchev for pointing us in the right direction

**Comment by dotjon0** [comment]
If you do a sort on a realm property that is ObjectId type, we assume this sort orders the realm database documents in order of timestamp (that is within the ObjectId)? So effected we could make a created at column within a list view via ObjectId.timestamp and then sort of this created at date in ascending order?

**Comment by nirinchev** [comment]
Yes, the first component of the ObjectId is the timestamp, so sorting on `ObjectId` should yield results similar to sorting on a timestamp property.

**Comment by dotjon0** [comment]
Amazing, thank you so much
