### ISSUE TITLE
RealmException: FilesDir not set

### ISSUE THREAD

**Issue by blueskky** [realm/realm-dart#137]
I/flutter (24542): RealmException: FilesDir not set
I/flutter (24542): #0      new Realm (package:realm/src/realm_class.dart:78:65)
I/flutter (24542): #1      new DeparmentModel (package:telemedicine_app/models/data.dart:103:13)
I/flutter (24542): #2      TestPage.initState (package:telemedicine_app/dbtest.dart:31:5)
I/flutter (24542): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4632:57)
I/flutter (24542): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4469:5)
I/flutter (24542): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3541:14)
I/flutter (24542): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:3306:18)

**Comment by blagoev** [comment]
Hi, our preview version requires Flutter 2.0 I suspect this error is related to the environment used. 
We are working on our next version which will remove this limitation.

**Comment by blagoev** [comment]
I am closing this issue for now
