### ISSUE TITLE
Login on windows is not working: non-zero custom status code considered fatal

### ISSUE THREAD

**Issue by dani-weiss** [realm/realm-dart#1370]
### What happened?

I'm developing a flutter app that uses realm with device sync and atlas user management using anonymous login or custom function credentials.
It is working perfectly on iOS, Android, MacOS (with exactly the same code) but it is failing for Windows. This is the error I get upon calling the login function (with either credentials):
```
AppException (AppException: non-zero custom status code considered fatal, link to server logs: null)
```
There is nothing in the logs of the Atlas app. Could you help me narrow down what the issue might be? Since I don't know what the underlying error is, it is almost impossible for me to start debugging.

### Repro steps

Call App.logIn with anonymous credentials or custom function credentials on Windows 10.

### Version

1.3.0

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### What type of application is this?

Flutter Application

### Client OS and version

Windows 10

### Code snippets

Either:
```
final app = App(AppConfiguration("<app>"));
final credentials = Credentials.anonymous();
final user = await app.logIn(credentials);
```

or:
```
final app = App(AppConfiguration("<app>"));
final credentials = Credentials.function(jsonEncode({
  "email": email,
  "password": password
}));
final user = await app.logIn(credentials);
```

### Stacktrace of the exception/crash you're getting

```shell
Empty stack trace: _StringStackTrace
```

### Relevant log output

```shell
flutter: 2023-08-05T17:55:13.721611: [ERROR] Realm: App: log_in_with_credentials failed: 0 message: non-zero custom status code considered fatal


AppException (AppException: non-zero custom status code considered fatal, link to server logs: null) with status code 999
```

**Comment by nielsenko** [comment]
Can I ask you to put a breakpoint on
```dart
        responseRef.custom_status_code = _CustomErrorCode.unknown.code;
```
in `realm_core.dart` (If you are using v1.3.0 it is line 1730).and report back what the exact exception it is that causes the `unknown` error code to be set.

**Comment by dani-weiss** [comment]
**Update:**
I added a global interceptor for bad certificates (`badCertificateCallback`) with the flutter http client using `HttpOverrides`. The failing host is:
```
eu-central-1.aws.realm.mongodb.com
```

I then went on to verify the ssl certificate used by the host with this result (using https://www.geocerts.com/ssl-checker):

<img width="853" alt="Bildschirmfoto 2023-08-09 um 23 25 47" src="https://github.com/realm/realm-dart/assets/44534372/7a1afede-5753-4052-bb4c-4e246eed501e">

There seems to be a configuration error concerning the certificate chain. See also this thread talking about the same problem but not related to flutter:
https://community.letsencrypt.org/t/handshake-verification-error/61614

**Comment by nielsenko** [comment]
On macos 13.5 it resolves fine:
```sh
❯ gnutls-cli eu-central-1.aws.realm.mongodb.com
Processed 138 CA certificate(s).
Resolving 'eu-central-1.aws.realm.mongodb.com:443'...
Connecting to '3.124.220.115:443'...
- Certificate type: X.509
- Got a certificate list of 3 certificates.
- Certificate[0] info:
 - subject `CN=*.aws.realm.mongodb.com', issuer `CN=R3,O=Let's Encrypt,C=US', serial 0x0415a544e6686b98a3a4f1068226dbb907fe, RSA key 2048 bits, signed using RSA-SHA256, activated `2023-07-26 11:31:23 UTC', expires `2023-10-24 11:31:22 UTC', pin-sha256="CVaXq2/zpuX8BaHTwVmlMV728SayahkassVuF1dxIYQ="
        Public Key ID:
                sha1:16a8f104ea29796f4eda59186070c3f0c0cfc254
                sha256:095697ab6ff3a6e5fc05a1d3c159a5315ef6f126b26a191ab2c56e1757712184
        Public Key PIN:
                pin-sha256:CVaXq2/zpuX8BaHTwVmlMV728SayahkassVuF1dxIYQ=

- Certificate[1] info:
 - subject `CN=R3,O=Let's Encrypt,C=US', issuer `CN=ISRG Root X1,O=Internet Security Research Group,C=US', serial 0x00912b084acf0c18a753f6d62e25a75f5a, RSA key 2048 bits, signed using RSA-SHA256, activated `2020-09-04 00:00:00 UTC', expires `2025-09-15 16:00:00 UTC', pin-sha256="jQJTbIh0grw0/1TkHSumWb+Fs0Ggogr621gT3PvPKG0="
- Certificate[2] info:
 - subject `CN=ISRG Root X1,O=Internet Security Research Group,C=US', issuer `CN=DST Root CA X3,O=Digital Signature Trust Co.', serial 0x4001772137d4e942b8ee76aa3c640ab7, RSA key 4096 bits, signed using RSA-SHA256, activated `2021-01-20 19:14:03 UTC', expires `2024-09-30 18:14:03 UTC', pin-sha256="C5+lpZ7tcVwmwQIMcRtPbsQtWLABXhQzejna0wHFr8M="
- Status: The certificate is trusted.
- Description: (TLS1.3-X.509)-(ECDHE-X25519)-(RSA-PSS-RSAE-SHA256)-(AES-256-GCM)
- Session ID: FC:98:D3:39:7D:81:9A:E9:C8:78:FB:87:21:92:39:C5:5B:0F:B1:35:30:4A:96:2B:91:67:98:56:6B:1E:70:9E
- Options:
- Handshake was completed
```
Will investigate

**Comment by nielsenko** [comment]
Could you try loading https://letsencrypt.org/ in a browser on the windows box in question? It is signed with the same root certificate **ISRG Root X1**.

Windows does some shenanigans downloading installing certificates lazily, but I speculate that boringssl does not.

**Comment by nielsenko** [comment]
https://github.com/realm/realm-dart/issues/1087 relates to a somewhat similar issue with Android 7 and earlier, and how you can work around it.

The PR #1088 never landed, but it illustrates a work-around.

**Comment by nielsenko** [comment]
I think the most failsafe approach is to install the **ISRG Root X1** root certificate on the `SecurityContext` of the `HttpClient` and _try_ not to forget to update it before 2035. A lot can happen with the certificate chains before that anyway.
 
Other than that I guess you need to look into why and when Windows will automatically download a missing root certificate.

**Comment by nielsenko** [comment]
We will likely add it automatically on all platforms in the next version. Stay tuned.

**Comment by dani-weiss** [comment]
> I think the most failsafe approach is to install the **ISRG Root X1** root certificate on the `SecurityContext` of the `HttpClient` and _try_ not to forget to update it before 2035. A lot can happen with the certificate chains before that anyway.

This is exactly what I did now. Yes, I set a reminder to repeatedly check the situation about the certificates.
Thanks for your help.

**Comment by dotjon0** [comment]
Just checking to see how #1378 is progressing?

**Comment by nirinchev** [comment]
@fealebenpae that's more in your alley - can you take a look and see if the approach in #1378 is what we want to do?

**Comment by milindgoel15** [comment]
I encountered this error after i did a password reset using bcrypt coded in nextjs and tried logging on windows on flutter side. But logging with plain passwords work.
