### ISSUE TITLE
Support diacritic string operator when filtering data

### ISSUE THREAD

**Issue by bryanless** [realm/realm-dart#1407]
### Problem

Currently the only string operator that can be used in Flutter Realm is `[c]`  for case insensitivity as described in the [Realm query language](https://www.mongodb.com/docs/realm/realm-query-language/#string-operators). For example, this operator will strictly compare for diacritics which mean it will filter out `é` while using `name CONTAINS[c] 'e'`

As far as I know, there is no workaround for it. I decided to completely ignore string filtering while searching for an object in the Realm local database.

### Solution

In Swift, there are 2 string operators which are `.caseInsensitive` and `.diacriticInsensitive`. These can be used in the `options` property such as `$0.name.contains("e", options: .diacriticInsensitive)` as described in the [Swift filter data docummentation](https://www.mongodb.com/docs/realm/sdk/swift/crud/filter-data/#string-operators)

A new string operator should work such as having `[d]` for diacritic insensitivity. It can be used like `name CONTAINS[d] 'e'` and will also return string containing `é`

### How important is this improvement for you?

Dealbreaker

### Feature would mainly be used with

Local Database only

**Comment by nirinchev** [comment]
This is not currently supported with the flutter SDK, but you can add a [full-text search index](https://pub.dev/documentation/realm/latest/realm/Indexed-class.html), which is always diacritic- and case-insensitive.

**Comment by bryanless** [comment]
As my use case is to search something that "starts with" or "contains" a phrase, I don't think I can use FTS. However, my current workaround is to add a normalized text as a new property. Anyway, thank you for telling me about TFS. I wasn't aware that FTS supports diacritic insensitive.

**Comment by dotjon0** [comment]
Any movement on this?

**Comment by nirinchev** [comment]
No. This is not supported in the Core database and we'll need to add support there before exposing it in the Dart SDK. This is the Core issue: https://github.com/realm/realm-core/issues/1082.

**Comment by nirinchev** [comment]
I'm going to close this as there's no work on the Dart SDK needed once the Core work is done.
