### ISSUE TITLE
iOS: Failed to load dynamic library 'realm_dart'

### ISSUE THREAD

**Issue by SPodjasek** [realm/realm-dart#1408]
### What happened?
I'm aware that this exact error was already discussed in #1157 but I've started to notice the exact same problem in pre-production builds in recent weeks. Reading through referened issue https://github.com/realm/realm-dart/issues/1157#issuecomment-1427640680 it seems that this error might be expected, but strange thing is, that is causing issues only on applications built with Flutter version 3.13.5 and 3.13.6. When I build them with 3.13.4 - they work as expected without any change in code.

Is this issue realm related, or should this be posted to flutter team?

Looking through flutter hotfixes you can see that 3.13.5 introduced this [fix](https://github.com/flutter/flutter/issues/134825)

* maybe it introduced some regression which is visible here during realm startup.

### Repro steps
1. Compile app with Flutter framework from stable channel - version 3.13.5 or higher
1. Run it on iOS
1. Few moments after start (you can see some content being rendered for less than a second) - gray screen - crash

### Version
1.5.0

### What Atlas Services are you using?
Atlas Device Sync

### What type of application is this?
Flutter Application

### Client OS and version
iOS 16.7.0, 17.0.2

### Stacktrace of the exception/crash you're getting
```shell
Fatal Exception: FlutterError
Realm error : Invalid argument(s): Failed to load dynamic library 'realm_dart': dlopen(realm_dart, 0x0001): tried: 'realm_dart' (relative path not allowed in hardened program), '/private/preboot/Cryptexes/OSrealm_dart' (no such file), '/usr/lib/swift/realm_dart' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/realm_dart' (no such file), '/private/var/containers/Bundle/Application/<<some id>>/Runner.app/Frameworks/realm_dart' (no such file), '/private/var/containers/Bundle/Application/<<some id>>/Runner.app/Frameworks/realm_dart' (no such file), '/usr/lib/realm_dart' (no such file, not in dyld cache), 'realm_dart' (relative path not allowed in hardened program), '/usr/local/lib/realm_dart' (no such file), '/usr/lib/realm_dart' (no such file, not in dyld cache) Invalid argument(s): Failed to load dynamic library '/private/var/containers/Bundle/Application/<<some id>>/Runner.app/realm_dart': dlopen(/private/var/containers/Bundle/Application/<<some id>>/Runner.app/realm_dart, 0x0001): tried: '/private/var/containers/Bundle/Application/<<some id>>/Runner.app/realm_dart' (no such file), '/private/preboot/Cryptexes/OS/private/var/containers/Bundle/Application/<<some id>>/Runner.app/realm_dart' (no such file), '/private/var/containers/Bundle/Application/<<some id>>/Runner.app/realm_dart' (no such file) Invalid argument(s): Failed to load dynamic library '/private/var/containers/Bundle/Application/<<some id>>/Runner.app/Frameworks/realm_dart.framework/realm_dart': dlopen(/private/var/containers/Bundle/Application/<<some id>>/Runner.app/Frameworks/realm_dart.framework/realm_dart, 0x0001): tried: '/private/var/containers/Bundle/Application/<<some id>>/Runner.app/Frameworks/realm_dart.framework/realm_dart' (no such file), '/private/preboot/Cryptex


Fatal Exception: FlutterError
0  ???                            0x0 (null)._openRealmLib + 81 (init.dart:81)
1  ???                            0x0 (null).initRealm + 105 (init.dart:105)
2  ???                            0x0 _realmLib.<fn> + 59 (realm_core.dart:59)
3  ???                            0x0 (null)._realmLib + 67 (realm_core.dart:67)
4  ???                            0x0 _RealmCore.createScheduler (realm_core.dart)
5  ???                            0x0 new Scheduler._ + 47 (scheduler.dart:47)
6  ???                            0x0 (null).scheduler + 24 (scheduler.dart:24)
7  ???                            0x0 (null).new _RealmCore (realm_core.dart)
8  ???                            0x0 (null).realmCore + 93 (realm_core.dart:93)
9  ???                            0x0 Configuration.defaultStoragePath (configuration.dart)
10 ???                            0x0 Configuration.defaultRealmPath + 110 (configuration.dart:110)
11 ???                            0x0 (null).new AppConfiguration (app.dart)
12 ???                            0x0 AppServices._initialize + 184 (app_services.dart:184)
13 ???                            0x0 AppServices.updateSettings + 110 (app_services.dart:110)
14 ???                            0x0 _RootAppState.build.<fn> + 93 (root_app.dart:93)
15 ???                            0x0 new ListenableProxyProvider2.<fn> + 149 (listenable_provider.dart:149)
16 ???                            0x0 _CreateInheritedProviderState.build + 852 (inherited_provider.dart:852)
17 ???                            0x0 _InheritedProviderScopeElement.build + 546 (inherited_provider.dart:546)
18 ???                            0x0 ComponentElement.performRebuild + 5297 (framework.dart:5297)
19 ???                            0x0 Element.rebuild + 5016 (framework.dart:5016)
20 ???                            0x0 BuildOwner.buildScope + 2779 (framework.dart:2779)
21 ???                            0x0 WidgetsBinding.drawFrame + 916 (binding.dart:916)
22 ???                            0x0 RendererBinding._handlePersistentFrameCallback + 360 (binding.dart:360)
23 ???                            0x0 SchedulerBinding._invokeFrameCallback + 1297 (binding.dart:1297)
24 ???                            0x0 SchedulerBinding.handleDrawFrame + 1227 (binding.dart:1227)
25 ???                            0x0 SchedulerBinding._handleDrawFrame + 1085 (binding.dart:1085)
```

**Comment by SPodjasek** [comment]
Just checked with Flutter 3.13.8 and it still occurs, so I guess this might be Flutter related and I'll cross-post this issue there...

**Comment by rsanford-hh2** [comment]
My team just ran into this issue last week.

What worked for us was switching from realm_dart to just realm. It seems that realm_dart is a dynamic library and realm is a static library. At least, the dynamic library load error went away when we did that.

Old
`import 'package:realm_dart/realm.dart';`

New
`import 'package:realm/realm.dart';`

**Comment by rsanford-hh2** [comment]
We started with a Dart command-line app and so started with realm_dart. We liked it enough that we decided to try and reuse it in a mobile app. We made sure that everything was properly organized to pull the library out and built out the iOS interfaces and started running into the "failed to load dynamic library" error. 

It took us longer than I would have liked to come to the understanding of what the root cause actually was. Now that this GitHub issue exists, anyone else that runs into the same will hopefully have a shorter time of it.

@SPodjasek - would switching that up resolve your errors?

**Comment by SPodjasek** [comment]
@rsanford-hh2 My app is in Flutter so I've used `package:realm` from beginning. 

In my case it seems that this was an issue with flutter itself, as building app with 3.16.x fixed this problem.

**Comment by SPodjasek** [comment]
It seems that I've praised the day before sunset - this issue is back on iOS 17.2.0 and Flutter 3.16.2

**Comment by SPodjasek** [comment]
I've just tested my app with different Flutter versions from 3.16.x branch, and here's how it looks like:

| Flutter version | Result |
|--------|--------|
| 3.16.0 | :heavy_check_mark: |
| 3.16.1 | :x: |
| 3.16.2 | :x: |
| 3.16.3 | :x: |
| 3.16.4 | :x: | 
| 3.16.5 | :heavy_check_mark: |

Same code base, only Flutter version during build have changed.
Tested on the same device with iOS 17.2.0.

**Comment by nielsenko** [comment]
@SPodjasek Is this still an issue for you?
