### ISSUE TITLE
Realm-generator files ignore lint

### ISSUE THREAD

**Issue by Pluxury** [realm/realm-dart#1412]
### Problem

**Steps to reproduce:**

1. Create any realm model
2. Adjust `analysis_options.yaml` and enable non-default rules, for example, 'cast_nullable_to_non_nullable: true'
3. Proceed code generation
4. Execute `flutter analyze --fatal-warnings` on the code sample

**Expected results:**
No warnings or errors are shown for generated .g.dart files

**Actual results:**
Linter warnings are shown for .g.dart files:

info • Don't cast a nullable value to a non-nullable type.
Try adding a not-null assertion ('!') to make the type non-nullable.
<img width="1016" alt="изображение" src="https://github.com/realm/realm-dart/assets/33198447/3073aedd-b349-4cd3-b2f9-3d386155e7f4">

### Solution

It would help if you disabled the linter for the generated files.

So please add the comment in generated files // ignore_for_file: type=lint.

This approach is used by other projects like [built_value](https://github.com/google/built_value.dart/blob/master/built_value_generator/lib/built_value_generator.dart).

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by Pluxury** [comment]
@nirinchev How can i create PR for this feature ?

**Comment by nirinchev** [comment]
Fixed in https://github.com/realm/realm-dart/pull/1413.

**Comment by Taco55** [comment]
I encountered a minor issue with the current PR. When multiple Realm classes are defined in a single file, it results in multiple "// ignore_for_file: type=lint" comments in the file, each displaying the warning: 'The diagnostic 'lint' doesn't need to be ignored here because it's already being ignored.'

**Comment by nirinchev** [comment]
Yeah, I saw that as well but was a bit lazy to fix it 😅 Your comment was the motivation I needed to do it though.
