### ISSUE TITLE
Issue with converting local realm to flexible sync realm

### ISSUE THREAD

**Issue by milindgoel15** [realm/realm-dart#1416]
### What happened?

So i have this app that uses local config as I want to offer a fully offline first approach in my app. Now I am adding flexible sync config on the basis whether user wants to login so all that works fine. But the problem happens when the data created under local config does not copy to flexible sync so I looked into MongoDB docs but found [this](https://www.mongodb.com/docs/realm/sdk/node/realm-files/open-and-close-a-realm/#std-label-node-open-existing-realm-different-configuration). 

Following the way of JS/TS code throws me the realm exception as:
```console
RealmException (RealmException: Error code: 2007 . Message: Realm cannot be converted to a flexible sync realm unless flexible sync is already enabled)
```

Because switching from local to flexible would be very difficult for users and it will make flexible sync useless for them since no data was saved unless backed up externally which can only be opened in realm studio or a local config based app with same schema

### Repro steps

1. Initiate local realm
2. add flexible sync
3. login to a user
4. start copyTo
5. throws exception

### Version

3.13.8

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### What type of application is this?

Flutter Application

### Client OS and version

Android 13/Windows 11

### Code snippets

```dart
  Realm getSyncedRealm(App app) {
    // if (app.currentUser != null) {
    currentUser = app.currentUser;
    final Configuration syncConfig = Configuration.flexibleSync(
      app.currentUser!,
      realmSchemas,
    );
    final localConfig = Configuration.local(
      realmSchemas,
      schemaVersion: 11, // increase this number after updating any model
    );
    final localRealm = Realm.open(localConfig);
    localRealm.then((realm) => realm.writeCopy(syncConfig));

    notifyListeners();

    return Realm(syncConfig);
  }
```

**Comment by dotjon0** [comment]
Perhaps its best to keep your local and device sync realm db's separate, each with their own schema - then you could make a function to copy each db document programatically from the local to device sync. The JS/TS Realm SDKs far before the Dart/Flutter SDK, so there is occasionally functionality that is missing (yet to come) in the Dart/Flutter SDK. Hope this helps.

**Comment by milindgoel15** [comment]
> Perhaps its best to keep your local and device sync realm db's separate, each with their own schema 

Then it defeats the purpose of my app. The realm files are already stored in different locations for both local and flexible sync.

Even tried to fetch all documents written in the local configuration and tried running the write > addAll but it then throws:

cannot add object to realm because the object is managed by another realm instance

**Comment by dotjon0** [comment]
cannot add object to realm because the object is managed by another realm instance

-> If you try deep copying each document (i.e. create new instances of each document) before you write > addAll

**Comment by milindgoel15** [comment]
> If you try deep copying each document (i.e. create new instances of each document) before you write > addAll

Can you give some sample code?

**Comment by dotjon0** [comment]
> > If you try deep copying each document (i.e. create new instances of each document) before you write > addAll
> 
> Can you give some sample code?

Something like the below, FYI ive not spun this up, a rough quick draft but should give you the right idea. You'll obviously have to realm generate _CatOne and _CatTwo so CatOne and CatTwo can be utilised.

```
/// Cat One Model
@RealmModel()
@MapTo("CatOne")
class _CatOne {

  /// The id (unique identifier)
  @PrimaryKey()
  late ObjectId id;

  /// Cat Name
  late String name;
}

/// Cat Two Model
@RealmModel()
@MapTo("CatTwo")
class _CatTwo {

  /// The id (unique identifier)
  @PrimaryKey()
  late ObjectId id;

  /// Cat Name
  late String name;
}

/// Deep Copy Cate One List to Cat Two List
List<CatTwo> deepCopyCatOneListToCatTwoList({
  required final List<CatOne> catOneList,
}) {
  List<CatTwo> catTwoList = <CatTwo>[];
  
  // Process all Cat One Items
  for (int x = 0; x < catOneList.length; x++) {
    final CatOne catOne = catOneList[x];

    // Create Cat 2 Object
    catTwoList.add(
      CatTwo(
          catOne.id, // ideally a new id here and reference cat_one_id as second key
          catOne.name
      ),
    );
  }
  
  return catTwoList;
}

// Then after this write all catTwoList to your 2nd Realm local DB in a write async block
```

**Comment by milindgoel15** [comment]
So i did it in the following way.

I retrieved all the instances using .all() and assigned to x then from the x, I created a new list(y) and added each instance from x to y and then did realm.write -> realm.add(y.e). 

Could I have done it better? maybe not creating a redundant list y and directly writing from x?

**Comment by dotjon0** [comment]
Sounds good

**Comment by milindgoel15** [comment]
Why it got closed? The actual solution does not work. The one that worked is merely a workaround.

**Comment by nirinchev** [comment]
Because this is not something that can be done in the flutter SDK. We need it to be supported by the Core database first, which is tracked in https://github.com/realm/realm-core/issues/5711 (I can see that the issues didn't get linked correctly on Github).
