### ISSUE TITLE
Realm does not support dart Sets

### ISSUE THREAD

**Issue by matthewjsummers** [realm/realm-dart#1418]
### Problem

Currently, Realm does not appear to support dart:collection Sets out of the box.

For example:

```
final setOne = realm.all<MyObject>().toSet(); // or Set.of(realm.all<MyObject>())
final setTwo = realm.all<MyObject>().toSet();

final difference = setOne.difference(setTwo).length; 
print(difference); // <- Would expect there to be no difference, but difference is 1
```

### Solution

I believe that realm sets compare objects based off object identity `a == b` **and** object hashcode.

In the above example, assuming a result list size of 1:

```
setOne.first == setTwo.first; // is true
setOne.first.hashCode == setTwo.first.hashCode; // is false
```

### Alternatives

Could write a custom set implementation, but the dart set should ideally work out of the box, especially as RealmObjectBase overrides == operator.

### How important is this improvement for you?

Dealbreaker

### Feature would mainly be used with

Local Database only

**Comment by nirinchev** [comment]
I see, this seems like an oversight that should be easy to fix by overriding the object hash code. I'll see if I can port the code from the .NET SDK to dart.
