### ISSUE TITLE
No web 

### ISSUE THREAD

**Issue by victorcode1** [realm/realm-dart#1419]
### What happened?

A bug happened!

               ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12193
Try removing the 'external' keyword or adding a JS interop annotation.
  external ffi.Array<ffi.Uint8> bytes;
                                ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12199
Try removing the 'external' keyword or adding a JS interop annotation.
  external UnnamedUnion1 values;
                         ^

: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12202
Try removing the 'external' keyword or adding a JS interop annotation.
  external int type;
               ^

: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12224
Try removing the 'external' keyword or adding a JS interop annotation.
  external int version;
               ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12227
Try removing the 'external' keyword or adding a JS interop annotation.
  external int index;
               ^

: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12261
Try removing the 'external' keyword or adding a JS interop annotation.

  external ffi.Pointer<ffi.Char> address;
                                 ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12264
Try removing the 'external' keyword or adding a JS interop annotation.
  external int port;
               ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12266
Try removing the 'external' keyword or adding a JS interop annotation.
  external ffi.Pointer<ffi.Char> path;
                                 ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12268
Try removing the 'external' keyword or adding a JS interop annotation.
  external ffi.Pointer<ffi.Pointer<ffi.Char>> protocols;
                                              ^

: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12271
Try removing the 'external' keyword or adding a JS interop annotation.
  external int num_protocols;
               ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12274
Try removing the 'external' keyword or adding a JS interop annotation.
  external bool is_ssl;
                ^

Waiting for connection from debug se

### Repro steps

2

### Version

last

### What Atlas Services are you using?

-- select --

### What type of application is this?

Flutter Application

### Client OS and version

web

### Code snippets

               ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12193
Try removing the 'external' keyword or adding a JS interop annotation.
  external ffi.Array<ffi.Uint8> bytes;
                                ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12199
Try removing the 'external' keyword or adding a JS interop annotation.
  external UnnamedUnion1 values;
                         ^

: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12202
Try removing the 'external' keyword or adding a JS interop annotation.
  external int type;
               ^

: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12224
Try removing the 'external' keyword or adding a JS interop annotation.
  external int version;
               ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12227
Try removing the 'external' keyword or adding a JS interop annotation.
  external int index;
               ^

: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12261
Try removing the 'external' keyword or adding a JS interop annotation.

  external ffi.Pointer<ffi.Char> address;
                                 ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12264
Try removing the 'external' keyword or adding a JS interop annotation.
  external int port;
               ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12266
Try removing the 'external' keyword or adding a JS interop annotation.
  external ffi.Pointer<ffi.Char> path;
                                 ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12268
Try removing the 'external' keyword or adding a JS interop annotation.
  external ffi.Pointer<ffi.Pointer<ffi.Char>> protocols;
                                              ^

: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12271
Try removing the 'external' keyword or adding a JS interop annotation.
  external int num_protocols;
               ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12274
Try removing the 'external' keyword or adding a JS interop annotation.
  external bool is_ssl;
                ^

Waiting for connection from debug se

### Stacktrace of the exception/crash you're getting

```shell
^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12193
Try removing the 'external' keyword or adding a JS interop annotation.
  external ffi.Array<ffi.Uint8> bytes;
                                ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12199
Try removing the 'external' keyword or adding a JS interop annotation.
  external UnnamedUnion1 values;
                         ^

: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12202
Try removing the 'external' keyword or adding a JS interop annotation.
  external int type;
               ^

: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12224
Try removing the 'external' keyword or adding a JS interop annotation.
  external int version;
               ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12227
Try removing the 'external' keyword or adding a JS interop annotation.
  external int index;
               ^

: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12261
Try removing the 'external' keyword or adding a JS interop annotation.

  external ffi.Pointer<ffi.Char> address;
                                 ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12264
Try removing the 'external' keyword or adding a JS interop annotation.
  external int port;
               ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12266
Try removing the 'external' keyword or adding a JS interop annotation.
  external ffi.Pointer<ffi.Char> path;
                                 ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12268
Try removing the 'external' keyword or adding a JS interop annotation.
  external ffi.Pointer<ffi.Pointer<ffi.Char>> protocols;
                                              ^

: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12271
Try removing the 'external' keyword or adding a JS interop annotation.
  external int num_protocols;
               ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12274
Try removing the 'external' keyword or adding a JS interop annotation.
  external bool is_ssl;
                ^

Waiting for connection from debug se
```

### Relevant log output

```shell
^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12193
Try removing the 'external' keyword or adding a JS interop annotation.
  external ffi.Array<ffi.Uint8> bytes;
                                ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12199
Try removing the 'external' keyword or adding a JS interop annotation.
  external UnnamedUnion1 values;
                         ^

: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12202
Try removing the 'external' keyword or adding a JS interop annotation.
  external int type;
               ^

: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12224
Try removing the 'external' keyword or adding a JS interop annotation.
  external int version;
               ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12227
Try removing the 'external' keyword or adding a JS interop annotation.
  external int index;
               ^

: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12261
Try removing the 'external' keyword or adding a JS interop annotation.

  external ffi.Pointer<ffi.Char> address;
                                 ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12264
Try removing the 'external' keyword or adding a JS interop annotation.
  external int port;
               ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12266
Try removing the 'external' keyword or adding a JS interop annotation.
  external ffi.Pointer<ffi.Char> path;
                                 ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12268
Try removing the 'external' keyword or adding a JS interop annotation.
  external ffi.Pointer<ffi.Pointer<ffi.Char>> protocols;
                                              ^

: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12271
Try removing the 'external' keyword or adding a JS interop annotation.
  external int num_protocols;
               ^
: Error: Only JS interop members may be 'external'.
realm_bindings.dart:12274
Try removing the 'external' keyword or adding a JS interop annotation.
  external bool is_ssl;
                ^

Waiting for connection from debug se
```

**Comment by nirinchev** [comment]
The Realm dart SDK doesn't support web targets for now. See https://github.com/realm/realm-dart/issues/26 for more details.
