### ISSUE TITLE
Unable to use realm_dart for flutter

### ISSUE THREAD

**Issue by arunspacek** [realm/realm-dart#1432]
### Problem

Why can't I use realm_dart package in my flutter app?
In pub.dev, it shows that both flutter and dart are supported.
I want to use models generated with realm_dart package in flutter app and dart server app. Otherwise I have to duplicate the models with different imports.
Please help.

### How important is this improvement for you?

Dealbreaker

### Feature would mainly be used with

Atlas Device Sync

**Comment by nirinchev** [comment]
This is not currently possible. While we do hope to be able to unify the realm and realm_dart packages at some point, it's not in our immediate plans. As a workaround, you can probably symlink the models between your server and flutter apps and create a file in each that exports the types from the correct package. Then your models would consume the re-exported types and wouldn't care which package they came from.

**Comment by arunspacek** [comment]
I understand. There is another package named 'realm_common'. I tried using it, but it doesn't work. How do I make it work?
