### ISSUE TITLE
Cannot change from Local database to Flexible Sync

### ISSUE THREAD

**Issue by atkinsonline** [realm/realm-dart#1436]
### What happened?

I've been following the YouTube demo given by Kasper Nielsen where he adds realm to the skeleton flutter template as shown here
https://www.youtube.com/live/9Pwi5eQOmZo?si=Kv9Lsnx50DaWrKli

It all goes fine until changing the model so it supports flexible sync.  At that point the watcher thows an unexpected error

in: package:me35realmtest4/src/sample_feature/sample_item.dart:6:7
  ╷
5 │ @RealmModel()
6 │ class _SampleItem {
  │       ^^^^^^^^^^^
  ╵
Unexpected error. Please open an issue on: https://github.com/realm/realm-dart

I have now gone through the demo twice and the problem happened both times.  On the second run through I saved my project folder prior to changing the model so it is now very reproducible.

### Repro steps

Follow the video until about 1 hour 6 minutes.  When the id field is renamed to no or to _id, the watcher shows the error above and the sample_item.g.dart file is deleted.  I assume it was being regenerated when it crashed.

### Version

3.16.0

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

Windows 11

### Code snippets

When I change 
//--------------------
import 'package:realm/realm.dart';
part 'sample_item.g.dart';

@RealmModel()
class _SampleItem {
  late int id;
}
//--------------------

to be as in the video

//--------------------
import 'package:realm/realm.dart';
part 'sample_item.g.dart';

@RealmModel()
class _SampleItem {
  @PrimaryKey()
  @MapTo('_id');
  late ObjectId id;
  late int no;
}
//--------------------

The watcher behaves as described above and I lose the  'sample_item.g.dart' file

I find the same happens if I just rename the id field to be _id

### Stacktrace of the exception/crash you're getting

```shell
This is not at app run time.  It is the watcher that throws an error
```

### Relevant log output

```shell
This is the log from the watcher

[INFO] Starting Build

[INFO] Updating asset graph...
[INFO] Updating asset graph completed, took 1ms

[INFO] Running build...
[INFO] realm:realm_generator on lib/main.dart:[generate (0)] completed, took 12ms
[INFO] realm:realm_generator on lib/src/sample_feature/sample_item_list_view.dart:[generate (0)] completed, took 11ms
[INFO] realm:realm_generator on lib/src/app.dart:[generate (0)] completed, took 11ms
[INFO] realm:realm_generator on lib/src/sample_feature/sample_item.dart:[generate (0)] completed, took 3ms
[SEVERE] realm:realm_generator on lib/src/sample_feature/sample_item.dart:

line 1, column 71 of package:me35realmtest4/src/sample_feature/sample_item.dart: Could not resolve annotation for `class _SampleItem`.
  ╷
1 │ @RealmModel()
  │ ^^^^^^^^^^^^^
  ╵
#0      TypeChecker._computeConstantValue (package:source_gen/src/type_checker.dart:114:7)
#1      TypeChecker._annotationsWhere (package:source_gen/src/type_checker.dart:139:21)
#2      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:558:14)
#3      SetBase.addAll (dart:collection/set.dart:58:23)
#4      _Set.addAll (dart:collection-patch/compact_hash.dart:986:11)
#5      new LinkedHashSet.of (dart:collection/linked_hash_set.dart:192:27)
#6      Iterable.toSet (dart:core/iterable.dart:512:21)
#7      ElementEx._annotationsInfoOfExact (package:realm_generator/src/element.dart:77:53)
#8      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:558:14)
#9      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#10     new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#11     new List.of (dart:core-patch/array_patch.dart:39:18)
#12     Iterable.toList (dart:core/iterable.dart:497:7)
#13     ElementEx.annotationInfoOfExact (package:realm_generator/src/element.dart:88:58)
#14     ClassElementEx.realmModelInfo (package:realm_generator/src/class_element_ex.dart:64:42)
#15     ClassElementEx.realmInfo (package:realm_generator/src/class_element_ex.dart:68:25)
#16     _extension#0.realmInfo.<anonymous closure> (package:realm_generator/src/realm_object_generator.dart:71:58)
#17     MappedIterator.moveNext (dart:_internal/iterable.dart:403:20)
#18     WhereIterator.moveNext (dart:_internal/iterable.dart:450:22)
#19     CastIterator.moveNext (dart:_internal/cast.dart:61:30)
#20     ExpandIterator.moveNext (dart:_internal/iterable.dart:489:21)
#21     Iterable.join (dart:core/iterable.dart:446:19)
#22     RealmObjectGenerator.generate.<anonymous closure>.<anonymous closure> (package:realm_generator/src/realm_object_generator.dart:61:69)
#23     _rootRun (dart:async/zone.dart:1399:13)
#24     _CustomZone.run (dart:async/zone.dart:1301:19)
#25     _runZoned (dart:async/zone.dart:1804:10)
#26     runZonedGuarded (dart:async/zone.dart:1792:12)
#27     scopeSession (package:realm_generator/src/session.dart:44:16)
#28     RealmObjectGenerator.generate.<anonymous closure> (package:realm_generator/src/realm_object_generator.dart:59:16)
<asynchronous suspension>
#29     measure.<anonymous closure> (package:realm_generator/src/measure.dart:50:18)
<asynchronous suspension>
#30     measure (package:realm_generator/src/measure.dart:47:7)
<asynchronous suspension>
#31     RealmObjectGenerator.generate (package:realm_generator/src/realm_object_generator.dart:56:12)
<asynchronous suspension>
#32     _generate (package:source_gen/src/builder.dart:355:23)
<asynchronous suspension>
#33     Stream.toList.<anonymous closure> (dart:async/stream.dart:1351:9)
<asynchronous suspension>


in: package:me35realmtest4/src/sample_feature/sample_item.dart:6:7
  ╷
5 │ @RealmModel()
6 │ class _SampleItem {
  │       ^^^^^^^^^^^
  ╵
Unexpected error. Please open an issue on: https://github.com/realm/realm-dart

[INFO] Running build completed, took 38ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 39ms

[SEVERE] Failed after 79ms

```

**Comment by atkinsonline** [comment]
I just decided to try this on a Mac as the above was on a Windows PC.

The result is the same.  The watcher crashes and I lose the generated file.

**Comment by nirinchev** [comment]
Can you try to fix the casing of the `MapTo` annotation? In the code snippet you've posted you're using all lowercase while it's PascalCase. Obviously the generator shouldn't crash, but it might fix things in the short term.

**Comment by atkinsonline** [comment]
Really sorry, I stupidly typed MapTo wrong here.  It is correct in my source code.  I had been trying some other tests where I found that all I needed to do was (refactor) rename the id field to no as explained in the video and it fails immediately in the watcher so if I just go from

import 'package:realm/realm.dart';
part 'sample_item.g.dart';

@RealmModel()
class _SampleItem {
  late int id;
}

to 

import 'package:realm/realm.dart';
part 'sample_item.g.dart';

@RealmModel()
class _SampleItem {
  late int no;
}

the watcher crashes and I lose the g.dart file.

I also just tried stopping the watcher while I made all the changes so I have

import 'package:realm/realm.dart';
part 'sample_item.g.dart';

@RealmModel()
class _SampleItem {
  @PrimaryKey()
  @MapTo('_id')
  late ObjectId id;
  late int no;
}

and then started the watcher and it then gave the same error. I'm lucky I have a saved folder so I can get back to a good version and try things but I can't think what else to try.

**Comment by atkinsonline** [comment]
I also see now that it is when I copy / paste that code to here that it changes MapTo to mapto.  This is what I have

`import 'package:realm/realm.dart';

part 'sample_item.g.dart';

@RealmModel()
class _SampleItem {
  @PrimaryKey()
  @MapTo('_id')
  late ObjectId id;
  late int no;
}
`

**Comment by atkinsonline** [comment]
`import 'package:realm/realm.dart';

part 'sample_item.g.dart';

@RealmModel()
class _SampleItem {
  @PrimaryKey()
  @MapTo('_id')
  late ObjectId id;
  late int no;
}
`

**Comment by atkinsonline** [comment]
I give up!  I put it in a code block and it still changes the case here

**Comment by nirinchev** [comment]
Oh, okay, I updated your comment to have a code block (triple ` at the top and the bottom) and it shows it correctly. I'll try to repro and see what happens.

**Comment by atkinsonline** [comment]
Thank you. That is very good of you.  I'd be happy to send you my complete folder zipped up but it is about 0.5MB in total so I'd need to drop it somewhere. I'm new here so not suer if I can drop that size of file here.  I'd have to remove my atlas appId but the rest of it is just code I typed from the Realm video.

**Comment by nirinchev** [comment]
Yeah, if you can zip it, you should be able to upload it without problems.

**Comment by atkinsonline** [comment]
[me35realmtest4.zip](https://github.com/realm/realm-dart/files/13465336/me35realmtest4.zip)

Thank you. It said there is a 25MB limit here, so I deleted the build folder, which I assume will be recreated.  

I renamed my api key to have abcde at the end

**Comment by nirinchev** [comment]
Looks like this is an issue with outdated packages - running `flutter packages upgrade` resolves it for me. Ideally, we should enforce that in the pubspec.yaml, but the PR that does it is on hold currently as it will force users to upgrade to a dart version that is a bit too new (see this comment for context: https://github.com/realm/realm-dart/pull/1365#issuecomment-1798858073).

**Comment by atkinsonline** [comment]
I tried "flutter packages upgrade2 and, as below, it tells me 7 packages are incompatible. It tells me to run flutter pub outdated and that does basically nothing so I don't know how to proceed.

D:\Dev\Flutter>cd D:\Dev\Flutter\me35realmtest4

D:\Dev\Flutter\me35realmtest4>flutter packages upgrade
Resolving dependencies... (2.2s)
  _fe_analyzer_shared 61.0.0 (65.0.0 available)
  analyzer 5.13.0 (6.3.0 available)
  dart_style 2.3.2 (2.3.4 available)
  http 1.1.0 (1.1.1 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.10.0 (1.11.0 available)
  web 0.3.0 (0.4.0 available)
No dependencies changed.
7 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

D:\Dev\Flutter\me35realmtest4>flutter pub outdated
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name  Current  Upgradable  Resolvable  Latest

direct dependencies: all up-to-date.

dev_dependencies: all up-to-date.
all dependencies are up-to-date.

**Comment by nirinchev** [comment]
What version of flutter are you using?

**Comment by atkinsonline** [comment]
Flutter t is 3.16.0

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.22631.2715], locale en-GB)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.84.2)
[√] Connected device (5 available)
[√] Network resources

• No issues found!

I also have a problem with a Realm sample.  The Flexible sync sample found here

[Flexible Sync ](https://github.com/realm/realm-dart-samples/tree/main/flutter_flexible_sync)

In this case, it builds fine but does not seem to sync as it should.  Perhaps this is also due to version problems.  I described it in this way at the community forum.

I’m using the sample app straight out of the box with the Altas AppId given in the sample but I get the same result if I use my own AppId.

If I add a record in the MongoDB collection in the back end, none of the connected devices update to show the change. If I add a new record in one of the connected devices, the back end does update but again, no other device updates in real time. When I add a record on one device, the UI then updates to show the correct number of records at the server collection. The devices only sync when I add a record on that device. Or perhaps they do sync but the UI does not update until that device does something to cause the UI to update?

I know this is not how device sync works, having previously used device sync in a MAUI app to great effect.
Can anyone confirm that this sample app should update the UI in realtime and if so why it is not working? The least I’d expect from a flexible sync demo app is for devices’ UI to update in real time.

**Comment by atkinsonline** [comment]
The above was from my windows PC but I get the same result from "flutter packages upgrade" and then "flutter pub outdated"  The Mac is also on Flutter 3.16.0.

**Comment by nirinchev** [comment]
Okay, this is kind of weird. Let's try another thing. In your pubspec.yaml, can you add the following section:

```yaml
dependency_overrides:
  meta: ^1.11.0
  analyzer: ^6.3.0
```

Essentially, this will override the necessary dependencies so we can pull analyzer 6.3.0.

**Comment by atkinsonline** [comment]
Afraid it was the same.  After I added those lines to pubspec.yaml, the output window showed this

[me35realmtest4] flutter pub get --no-example
Resolving dependencies...
> _fe_analyzer_shared 65.0.0 (was 61.0.0)
! analyzer 6.3.0 (overridden)
  dart_style 2.3.2 (2.3.4 available)
! flutter_lints 3.0.1 (from dev dependency to transitive dependency) (overridden)
  http 1.1.0 (1.1.1 available)
  material_color_utilities 0.5.0 (0.8.0 available)
! meta 1.11.0 (overridden)
  web 0.3.0 (0.4.0 available)
Changed 2 dependencies!
4 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
exit code 0

I then ran the usual 

flutter pub run realm generate --watch

in the cmd window and then renamed late int id to late into no as before and as in the video.  As soon as I saved that model file, the watcher gave the same failed message as before.

**Comment by nirinchev** [comment]
Hm... this is super peculiar and it's not exactly clear to me what's causing the behavior observed. It's also the only app so far where I've been able to reproduce the behavior - it doesn't happen to me on a brand new project. While investigating, here are a few things that I've seen help get the system in a good state:

1. Run `dart run realm generate` without `--watch`. This means you'll need to re-run the command manually whenever you make changes to the file, but so far it seems to have worked better for me.
2. Make changes to the model - e.g. add properties or change the `@RealmModel` annotation to e.g. `@RealmMode(ObjectType.RealmObject)`.
3. As mentioned, overriding the version of the dependencies and running `flutter pub get`.

By doing one or more of these actions, I'm eventually able to get the generator to succeed. I'll spend some more time on it later this week.

**Comment by atkinsonline** [comment]
Thank you for continuing to look into this.
I've just tried a few things.  I was able to add a new String field to the model and then generate but if I delete the id field or rename it, I get the same problem no matter what I do .

To be honest, I'm not too worried about solving this for the sake of the demo from the YouTube video.  I was only trying that because I'm new to Realm with Flutter and wanted to start somewhere.

What concerns me, perhaps more, is that the flexible sync sample I tried (as mentioned a few messages back) does not seem to sync as it should.  I don't know if that is due to a problem with the sample in Realm 1.60 or a problem with my system.  I did use that sample, completely unchanged and with the provided Atlas back end.  All I did was build and deploy to a few android devices and emulators.

**Comment by nielsenko** [comment]
@atkinsonline Did you try:
```sh
flutter clean
dart run realm generate
```
?

**Comment by nielsenko** [comment]
@atkinsonline Did the issue resolve for you?

If the above doesn't help could you try running:
```sh
flutter pub cache repair
```
as well, and then try again?

**Comment by atkinsonline** [comment]
Very sorry for the enormous delay in responding.  I've only just returned to the project where I'm going to use Realm. I decided to try an exercise having watched a recent YouTube video from MongoDB entitled Go Offline with Flutter and MongoDB Realm. It was an interview with Markandy Pathak who was demonstrating Flutter and Realm.

I have now upgraded to the latest Realm (1.9.0).  and just started the above sample from here

https://github.com/markandeyp/checkmate

I created a new flutter project, added realm and that worked fine.  I then added the item.dart schema and generated the realm and was pleased to see that worked fine.  I then did the same for the account.dart schema and saw the same problem as reported before.

in: package:shoppinglist/schemas/account.dart:7:7
  ╷
5 │ @RealmModel()
@MapTo("Users")
6 │ class _Account {
   │         ^^^^^^
  ╵
Unexpected error. Please open an issue on: https://github.com/realm/realm-dart

However, the good news is I then ran the first 2 commands you mentioned above

flutter clean
dart run realm generate

and that seems to have fixed it.  

I'll report back if I see further problems and more importantly, when I try to do the same in my real project.

Thank you for your help.

**Comment by atkinsonline** [comment]
I just ran 

flutter clean
dart run realm generate

on my real project and that can now generate as well so it looks like this is solved.  Thank you.
