### ISSUE TITLE
Expose RealmObjectBase.schema

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-dart#1449]

**Comment by mpobrien** [comment]
I started poking at this one to get acquainted with the codebase but I may need a little more context on the motivation and desired changes - the generated code for each model already has a `static SchemaObject get schema` method which returns the `SchemaObject` for the generated class, so from any model it should already be possible to get the schema?

**Comment by nirinchev** [comment]
The motivation is threefold:
1. When storing an object in a mixed field, having the schema on the object makes the code much easier to write code that inspects the schema. Using the generated schema, you would need to do something like:
    ```dart
    final myObj = obj.mixedValue;
    late Schema myObjSchema;
    if (myObj is Foo) {
       myObjSchema = Foo.schema;
    } else if (myObj is Bar) {
       myObjSchema = Bar.schema
    } ...
    ```
2. For generated classes, the generated schema will always reflect the schema that was known at compile time, even the server made changes to it, making it difficult to evaluate new properties using the dynamic API. For example, if a user has a `CustomMetadata` embedded class that has `Date created, updated` fields initially and then the user adds more fields at runtime, the generated schema would not know of the existence of these new fields and one would never be able to introspect the schema and access them using the dynamic API. Note that this may not work immediately, as I don't believe the flutter SDK registers a schema update callback to update its cached Realm schema, but that'd be a separate project.
3. Finally, for fully dynamic Realm usage, where the schema is read from disk, there'd be no generated schema, meaning the object schema will need to be read through `Realm.schema`, which is keyed on the class name, but with dynamic classes, we don't have a way to introspect the name to look up the schema. This means the developers need to always pass both the object and its schema as a tuple to be able to access any data in it.
