### ISSUE TITLE
Cannot use realm.add with an AsymetricObject

### ISSUE THREAD

**Issue by rsanford-hh2** [realm/realm-dart#1450]
### What happened?

I created an AsymetricObject expecting to get a one-way sync and I get a compiler error instead... 

### Repro steps

I have a model that I want to add as an Asymetric Object.

I declare it as

@RealmModel(ObjectType.asymmetricObject)
class _MyModel {
  @PrimaryKey()
  @MapTo('_id')
  late ObjectId id;
}
When I write the code to attempt to write it…
await realm.writeAsync(() => realm.add(myObject));

… I get a compiler error…

MyModel' doesn't conform to the bound 'RealmObject' of the type parameter 'T'.
Try using a type that is or is a subclass of 'RealmObject'.
When I look at the .g.dart file for the model I see that it is (correctly I think) generated as an AsymetricObject and not a RealmObject.

class MyModel extends _MyModel
    with RealmEntity, RealmObjectBase, AsymmetricObject {
Models that I do not have marked as asymmetric have RealmObject instead of AsymmetricObject.

The .NET client works great w/ AsymmetricObjects… what’s up w/ the Dart SDK?

rjsjr

### Version

Dart SDK version: 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "macos_arm64"

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Dart standalone application

### Client OS and version

MacOS Sonoma 14.2

### Code snippets

I have a model that I want to add as an Asymetric Object.

I declare it as

@RealmModel(ObjectType.asymmetricObject)
class _MyModel {
  @PrimaryKey()
  @MapTo('_id')
  late ObjectId id;
}
When I write the code to attempt to write it…
await realm.writeAsync(() => realm.add(myObject));

… I get a compiler error…

MyModel' doesn't conform to the bound 'RealmObject' of the type parameter 'T'.
Try using a type that is or is a subclass of 'RealmObject'.
When I look at the .g.dart file for the model I see that it is (correctly I think) generated as an AsymetricObject and not a RealmObject.

class MyModel extends _RealmFileRecordLinkChunk
    with RealmEntity, RealmObjectBase, AsymmetricObject {
Models that I do not have marked as asymmetric have RealmObject instead of AsymmetricObject.

The .NET client works great w/ AsymmetricObjects… what’s up w/ the Dart SDK?

rjsjr

**Comment by nirinchev** [comment]
The equivalent to `realm.add` that takes asymmetric object is called [`realm.ingest`](https://pub.dev/documentation/realm/latest/realm/Realm/ingest.html).

**Comment by nirinchev** [comment]
Oh... missed your 2nd question. The reason why this is a separate method in dart is because dart doesn't allow overloads - they're separate methods in .NET as well (`Add<T>(T) where T : IAsymmetricObject` and `Add<T>(T, bool) where T : IRealmObject`), but are named the same way because this is something the language supports. The reason why they cannot be the same method is because it would be semantically incorrect to have an `update` parameter for the asymmetric object API.

**Comment by rsanford-hh2** [comment]
Thank you very much! 

Copying code from one language to another to test out multi-platform support and I get tied up every so often... This is a huge help.

**Comment by nielsenko** [comment]
@nirinchev Actually, I left a branch [kn/asymmetric-add-instead-of-ingest](https://github.com/realm/realm-dart/tree/kn/asymmetric-add-instead-of-ingest) that "renames" `ingest` to `add` if this becomes a common request. It was spun-off from the original [PR](https://github.com/realm/realm-dart/pull/1400#issuecomment-1722953234).

**Comment by nirinchev** [comment]
Yeah, I'm not a huge fan of this approach as it's generally a design smell when we have an API that ignores certain arguments in some cases. I think the current API is fine and the cases of users porting code between SDKs have historically been few and far between, so we shouldn't sacrifice expressiveness for confirmity. We can probably improve the docs though.
