### ISSUE TITLE
Conflict with built_value generator

### ISSUE THREAD

**Issue by airychkov** [realm/realm-dart#1453]
### What happened?
I have Realm model
Try to use built_value package. Use code from example
Realm try to generate built_value g.dart file  Instead of generate 
result
// GENERATED CODE - DO NOT MODIFY BY HAND

part of '../value.dart';

// **************************************************************************
// RealmObjectGenerator
// **************************************************************************

// ignore_for_file: type=lint

### Repro steps
create file for built_value
run command: dart run build_runner build

sample from package
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'generated/value.g.dart';

abstract class SimpleValue implements Built<SimpleValue, SimpleValueBuilder> {
  /// Example of how to make a built_value type serializable.
  ///
  /// Declare a static final [Serializer] field called `serializer`.
  /// The built_value code generator will provide the implementation. You need
  /// to do this for every type you want to serialize.
  static Serializer<SimpleValue> get serializer => _$simpleValueSerializer;

int get anInt;

String? get aString;

/// The recommended factory exposes the generated builder interface. This
  /// works well for classes with many fields, or for classes that might be
  /// changed to have more fields later. For very simple classes, you might
  /// want something simpler. See [VerySimpleValue].
  factory SimpleValue([void Function(SimpleValueBuilder) updates]) = _$SimpleValue;
  SimpleValue._();
}

### Version
Flutter 3.16.4

### What Atlas Services are you using?
Local Database only

### What type of application is this?
Flutter Application

### Client OS and version
macOS 14.1.1 23B81 darwin-arm64

**Comment by nirinchev** [comment]
This is a known issue that will be addressed by https://github.com/realm/realm-dart/pull/1310 - it was put on the backburner for a while but we hope to get back to it soon - no clear estimate for when though.
