### ISSUE TITLE
Warnings to include part files for non-realm models

### ISSUE THREAD

**Issue by dannyglover** [realm/realm-dart#1456]
### What happened?
I get this output for every single file that doesn't include any realm models:

`[WARNING] source_gen:combining_builder on lib/main.dart:
generated/main.g.dart must be included as a part directive in the input library with:
    part 'generated/main.g.dart';`

This started happening after I updated realm from 1.6.0 to 1.6.1

### Repro steps
* Use realm 1.6.1
* Run `dart run build_runner clean && dart run build_runner build --delete-conflicting-outputs`
* Observe the warnings stated above

### Version
1.6.1

### What Atlas Services are you using?
Local Database only

### What type of application is this?
Flutter Application

### Client OS and version
Fedora 39

### Relevant log output
```shell
[WARNING] source_gen:combining_builder on lib/main.dart:
generated/main.g.dart must be included as a part directive in the input library with:
    part 'generated/main.g.dart';
```

**Comment by nirinchev** [comment]
This is a duplicate of https://github.com/realm/realm-dart/issues/1452
