### ISSUE TITLE
Add a linkingObjects method to RealmObject in the Flutter SDK

### ISSUE THREAD

**Issue by jcalven** [realm/realm-dart#1480]
### Problem

In the React Native SDK, objects have a [`linkingObjects`](https://www.mongodb.com/docs/realm-sdks/js/latest/classes/Object.html#linkingObjects) method that returns all objects that link to a given object. This is incredibly helpful when needing to do a cascading operation on the linked objects when the object changes (e.g. cascading deletes). For complex schemas it can be error prone and difficult to maintain such cascading operations manually.

### Solution

I propose to implement a `linkingObjects` method for RealmObjects in the Realm Flutter SDK that returns all objects that link to a given object.

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by nielsenko** [comment]
If you want to delete all objects of a given type that has no backlinks, ie. a one-level cascading delete, then you can achieve that today with:
```dart
realm.write(() => realm.deleteMany(realm.query<X>('@links.@count == 0')));
```
You can repeat that in a loop until the query doesn't find anything new to delete.
```dart
var count = 0;
do {
  final toDie = realm.query<X>('@links.@count == 0');
  count = toDie.length;
  realm.write(() => realm.deleteMany(toDie));
} while (count > 0) 
```
In _real-life_ you probably have multiple interconnected realm models, but the idea is the same

Be aware that the current number of links is the number known to the local client. Fever or more links may exists on some other node in the system - assuming you use sync. Cascading deletes are not really safe in a distributed setting.
