### ISSUE TITLE
Avoid nested packages

### ISSUE THREAD

**Issue by nielsenko** [realm/realm-dart#1485]
Instead if nesting `realm_common`, `realm_generator`, and `realm` package directories within the `realm_dart` package directory, I suggest moving to a setup like:
```
realm-dart/
  realm/
    packages/
      realm_common/
      realm_generator/
      realm_dart/
      realm/
  ejson/
    packages/
      ...
  atlas/
    packages/
      ...   
```
This way no packages exists within the directory structure of another package.

**Comment by nirinchev** [comment]
As part of this, we should try and remove the src symlink in flutter ios.

**Comment by nielsenko** [comment]
> As part of this, we should try and remove the src symlink in flutter ios.

Many(/most) symlinks will die, but the symlinks in the flutter platform plugins will remain until we complete #1515.

**Comment by nielsenko** [comment]
> > As part of this, we should try and remove the src symlink in flutter ios.
> 
> Many(/most) symlinks will die, but the symlinks in the flutter platform plugins will remain until we complete #1515.

Here I'm referring to the symlinks to the binary folder, ie:
```
realm_dart.xcframework@ -> ../../../binary/ios/realm_dart.xcframework
```
I realise now, that is not what you are asking about 🤦

**Comment by nirinchev** [comment]
Oh, great! Yeah, I was surprised this had to stay so created a quick PR to see what happens if I remove it 😄 Apparently, it can be removed, which makes me happy - it always irked me that we ship the entire Core with our flutter package.
