### ISSUE TITLE
Has any plan to change Uuid package from sane_uuid to ohters?

### ISSUE THREAD

**Issue by barqui** [realm/realm-dart#1489]
### Problem

Realm dart seems to using https://github.com/BjoernPetersen/sane_uuid for UUID.

However, this package is not list on pub.dev and noted as alpha stage.

There is reason to use that 'alpha' package?

It doesn't seem desirable to have me continue to use the alpha package for Uuid when I configure other packages.

### How important is this improvement for you?

-- select --

### Feature would mainly be used with

-- select --

**Comment by nirinchev** [comment]
No, we don't plan to offer the ability to use other UUID packages. When we implemented support, we researched the available options and concluded that, even though it's in alpha stage, it is the best one available.

While I understand your concern, the alpha/beta/stable designation is something the maintainer themselves chooses, so there's no guarantee that a "stable" package is of higher quality or has fewer bugs than an alpha one.
