### ISSUE TITLE
Bluethooth data sync

### ISSUE THREAD

**Issue by richard457** [realm/realm-dart#1508]
### Problem
There are many cases in a big shop where I want to share data across devices but not necessary connecting the app to wifi for the devices to synchronize.

### Solution
Enable Bluetooth to all devices so Bluetooth is used to share data across devices

### Alternatives
WIFI- standard mode I guess

### How important is this improvement for you?
Would be a major improvement

### Feature would mainly be used with
Atlas Device Sync

**Comment by nielsenko** [comment]
Realm does not support peer-to-peer sync - we require a hub-and-spoke topology. This is unlikely to change in any foreseeable time-frame.

**Comment by nirinchev** [comment]
Hey Richard, we don't have immediate plans to support bluetooth sync, but we do have a product, called [Atlas Edge Server](https://www.mongodb.com/products/platform/atlas-edge-server) which is intended to support scenarios where you have multiple devices that want to synchronize between one another, but don't have internet connectivity. This still goes through wifi/some other network, so not sure it addresses your use case, but it is successfully used in environments such as warehouses/stores where internet connectivity may be spotty but there's a central network the devices connect to.

**Comment by richard457** [comment]
I have requested private access to it, waiting, though it will be good to have a peer-to-peer sync with minimal configuration and use something like Bluetooth, etc... thank you.

**Comment by nirinchev** [comment]
Totally understand - it's a case that we've heard from other customers as well. However, we do believe in focusing on one thing and doing it really well vs trying to solve every problem. Right now, bluetooth-based peer-to-peer sync is not something we're comfortable investing in, so if this is critical for you, it's probably best to look into alternative synchronization frameworks. I'll close this ticket for now, but feel free to discuss this further with the account executive for your company.
