### ISSUE TITLE
[ERROR] Realm: App: log_in_with_credentials failed: 401 message: invalid API key

### ISSUE THREAD

**Issue by richard457** [realm/realm-dart#1512]
### What happened?
[ERROR] Realm: App: log_in_with_credentials failed: 401 message: invalid API key

### Repro steps
Create API key from atlas, use the API key

```dart
final app = App(AppConfiguration(AppSecrets.appId,
        baseUrl: Uri.parse("https://services.cloud.mongodb.com")));
    final user = app.currentUser ??
        await app.logIn(Credentials.apiKey(AppSecrets.mongoApiSecret));
```

deploy the app to production and later run the app in debug mode with the same API key

### Version
realm: ^1.9.0

### What Atlas Services are you using?
Atlas Device Sync

### What type of application is this?
Flutter Application

### Client OS and version
android, windows

### Code snippets
```dart
@override
  Future<Realm> configure() async {
    log(ProxyService.box.encryptionKey(), name: 'encriptionKey');
    int? branchId = ProxyService.box.getBranchId();
    if (realm != null) {
      return realm!;
    }

    //NOTE: https://www.mongodb.com/docs/atlas/app-services/domain-migration/
    final app = App(AppConfiguration(AppSecrets.appId,
        baseUrl: Uri.parse("https://services.cloud.mongodb.com")));
    final user = app.currentUser ??
        await app.logIn(Credentials.apiKey(AppSecrets.mongoApiSecret));
}
```

### Stacktrace of the exception/crash you're getting
```shell
I/flutter (26382): 2024-02-05T09:02:38.668477: [ERROR] Realm: App: log_in_with_credentials failed: 401 message: invalid API key
```

### Relevant log output
```shell
I/flutter (26382): 2024-02-05T09:02:38.668477: [ERROR] Realm: App: log_in_with_credentials failed: 401 message: invalid API key
```

**Comment by nielsenko** [comment]
[401](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#401) is an authentication error. Either the key is simply not valid as the error message states, or you mangle it somehow, so the server cannot recognise it.

**Comment by nielsenko** [comment]
I will need to know a lot of details that you may not be comfortable sharing in a public forum, such as:

- `AppSecrets.appId`, 
- `AppSecrets.mongoApiSecret` (as they look just before being used in the code snippets above), as well as 
- see the code that reads and writes these to storage, 

to have a chance to spot your error. Otherwise, I recommend that you a [support ticket](https://www.mongodb.com/docs/manual/support/).
