### ISSUE TITLE
Allow enforcing to-one relationships using backlinks in the opposite direction

### ISSUE THREAD

**Issue by abhi204** [realm/realm-dart#1514]
### Problem

I want to create two objects `Tag` and `TagCategory` such that each `Tag` must belong to one `TagCategory` and the latter can have multiple tags associated to itself.
As per the docs, we can use backlinks to define the required inverse relationship.

```dart
@RealmModel()
class _TagCategory {
  @PrimaryKey()
  late String name;
  late String description;

  late List<_Tag> tags;
}

@RealmModel()
class _Tag {
  @PrimaryKey()
  late String id;
  late String name;
  
  @Backlink(#tags)
  late Iterable<_TagCategory> category;
}
```

However, doing so allows `Tag` to be associated with multiple TagCategories and the `Tag.category` returns the list of all TagCategories instead of just the one category it belongs to.

### Solution

The present solution as per my knowledge is to enforce this at user level code. 

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by nielsenko** [comment]
Why not invert the relation:
```dart
@RealmModel()
class _TagCategory {
  @PrimaryKey()
  late String name;
  late String description;

  @Backlink(#category)
  late Iterable<_TagCategory> tags;
}

@RealmModel()
class _Tag {
  @PrimaryKey()
  late String id;
  late String name;
  
  _TagCategory? category;
}
```

**Comment by abhi204** [comment]
@nielsenko I initially thought of doing it but dropped the idea because it didn't fit my db design schema and would also require a lot of code refactors.
Anyways, I am now proceeding with this as I have come to realize some of the drawbacks of my previous design choices 😅

**Comment by nielsenko** [comment]
@abhi204 _Embedded_ objects can also come in handy, as these naturally have a single parent, and don't require the relation to be inverted.
