### ISSUE TITLE
AppException: could not find PEM formatted data in the provided public key

### ISSUE THREAD

**Issue by zohaib304** [realm/realm-dart#1529]
### What happened?

I encountered an issue while using the MongoDB Realm SDK in my Flutter application for authentication using JWT tokens. When attempting to authenticate using
`credentials.jwt(token)`

### Repro steps

I consistently receive the following error message: “AppException: could not find PEM formatted data in the provided public key”.

### Version

1.9.0

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

Android 9

### Code snippets

```
User loggedInUser =
        await app.logIn(Credentials.jwt(token));
```

### Stacktrace of the exception/crash you're getting

```shell
AppException: could not find PEM formatted data in the provided public key, status code: 401
```

**Comment by nirinchev** [comment]
Per the error message, it looks like the public key you configured in the Apo Services dashboard is invalid.

**Comment by zohaib304** [comment]
Thanks for pointing. I have resolved the above issue, and now there is a new exception.

I/flutter ( 9627): 2024-02-28T16:40:44.368788: [ERROR] Realm: App: log_in_with_credentials failed: 401 message: crypto/rsa: verification error
I/flutter ( 9627): AppException: crypto/rsa: verification error, status code: 401

**Comment by nirinchev** [comment]
This appears to be a server side exception - is there anything in the server logs related to it?

**Comment by zohaib304** [comment]
Received an `AuthError `with the message "`crypto/rsa: verification error`".

**Comment by nirinchev** [comment]
Looks like a misconfiguration of the JWT auth provider. If you file a ticket on https://support.mongodb.com, the team should be able to assist you with it.

I'm closing this as we don't believe this is an issue with the flutter SDK.
