### ISSUE TITLE
[Bug]: Unable to install on MacOS

### ISSUE THREAD

**Issue by tuphampro** [realm/realm-dart#1530]
### What happened?

I tried to run pod install on my Flutter project with realm: 1.9.0, but it failed with an error message:

![image](https://github.com/realm/realm-dart/assets/19162524/21fab204-2581-43c7-b6b0-ceb57632c316)

### Repro steps

Add realm: 1.9.0 to pubspec.yaml dependencies.
Try to build / debug the Flutter project with the target set to an MacOS device (Note that building a Flutter project calls pod install in its process)
It says pod install failed

### Version

Flutter v3.19.0 
Xcode 15.2

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

macOS 14.3.1

**Comment by vtharmalingam** [comment]
I am facing this issue as well. Kindly fix this.

**Comment by nielsenko** [comment]
@tuphampro and @vtharmalingam 

It is working fine on my macs, so I got a few questions.

1. Did you add realm for the first time to a project, or did you upgrade from a previous version?
1. What version of pod are you using? (I'm on 1.15.2)
1. Running ` pod install --repo-update --verbose` in the macos platform directory, do you get any errors?
1. Did you try `flutter clean`?
1. Did you try recreating the platform project? Ie.
```shell
rm -rf macos
flutter create . --platforms=macos
```
