### ISSUE TITLE
Requiring a newer version of CMake than Flutter requires is going to cause issues

### ISSUE THREAD

**Issue by AleixUltramar** [realm/realm-dart#1553]
### What happened?

I'm getting this error when compiling my app for Linux platform:
```
CMake Error at flutter/ephemeral/.plugin_symlinks/realm/linux/CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.19 or higher is required.  You are running version 3.16.3
```

I've found this issue flutter/flutter/issues/86852 that states that: 

> requiring a newer version of CMake than Flutter requires is going to cause issues for a lot of people.

Related to: #266

### Repro steps

1. Try to compile my app for Linux platform using Android Studio
2. Error:
```
CMake Error at flutter/ephemeral/.plugin_symlinks/realm/linux/CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.19 or higher is required.  You are running version 3.16.3


Error: Unable to generate build files
```

### Version

Dart 3.3.0, Flutter 3.19.1 

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

Ubuntu

**Comment by blagoev** [comment]
Hi, 
In general Flutter requires a very low version for compatibility reasons. Realm uses advanced CMake features that require a newer version of CMake. If you install a newer version of CMake locally it will be able to work with Flutter because it is backwards compatible.
