### ISSUE TITLE
Can not import from github

### ISSUE THREAD

**Issue by fu89-team** [realm/realm-dart#1556]
### What happened?

I want to get this commit but it is not released.
https://github.com/realm/realm-dart/pull/1524
I try to install from github but it does not work.
`  my-project-workspace:
    git:
      url: https://github.com/realm/realm-dart.git
      ref: main`
      
    I can run `flutter pub get` successfully but can not import into my dart file.

### Repro steps

I try to install from github but it does not work.
`  my-project-workspace:
    git:
      url: https://github.com/realm/realm-dart.git
      ref: main`
      
    I can run `flutter pub get` successfully but can not import into my dart file.

### Version

1.9.0

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

Android 14

**Comment by nielsenko** [comment]
That is correct. Currently you cannot use github refs to import realm.

There are a couple of reasons. 

- For one we use relative paths between projects on github until just before release. We will soon switch to using `dependency_overrides.yaml` (maintained with melos).
- The binary build on S3 may not match a particular commit. You really need to build the native binaries locally.

**Comment by nielsenko** [comment]
If it is any comfort, the next release is closing up.

**Comment by nirinchev** [comment]
Closing this as we don't plan to focus on this in the near future. While we do want to eventually be able to build from github directly, as Kasper said, the challenges around ensuring we have native binaries for every commit or having those automatically get built on developers' machines are not trivial.

**Comment by fu89-team** [comment]
Hope to release a new version soon.
It affects my entire project.

**Comment by nirinchev** [comment]
Can you elaborate on this? How does the new version affect your project and what is the issue with the current stable release?
