### ISSUE TITLE
Rare bug on array link

### ISSUE THREAD

**Issue by geosebas** [realm/realm-dart#1559]
### What happened?

Hi, my customer reported to me a rare and very weird bug. 
I did manage to see it in production, but never managed to reproduce it unfortunately. 

I don't know from where the problem is coming so I'm asking for help here. 

Below is the code I use.
So we have 3 realm object, a Match, a Player and a PlayerCredit. 
Here I'm adding a player to a match, create a PlayerCredit, and then add it to the match. 

```dart
await realm.writeAsync(() {
  // Add player
  match.players.add(player);

  // Create credit
  final credit = PlayerCredit(
    const Uuid().v4(),
    realmService.accountId,
    DateTime.now().toUtc(),
    0.0,
    match: match,
    offer: offer,
    player: player,
    type: PlayerCreditType.fromOffer(offer).name,
  );
  
  // Add credit to the realm
  realm.add(credit);
  
  // Add credit to the match
  match.playersCredits.add(credit);
  
});
```

The bug is that the PlayerCredit isn't added to the match but correctly added in the realm. 
So both of these line work well `match.players.add(player);` ` realm.add(credit);` but here it stop working without any error  `match.playersCredits.add(credit);`

It work well in 99 % of cases, but sometimes it fail without any error. 
Do you any issues or race conditions that may be responsible for this ? 

### Repro steps

Unfortunately, I cannot reproduce this issue

### Version

Flutter 3.16.0

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### What type of application is this?

Flutter Application

### Client OS and version

With realm 1.5.0 on both android and ios. 

### Code snippets
Added realm object schema
```dart
class $Match {
  @MapTo('_id')
  @PrimaryKey()
  late String id;
  late String accountId;
  late bool deleted;
  late bool disabled;
  late String name;

  late DateTime? createdAt;

  [...]

  /// From matchSystem information. This information will not be updated on match system change.
  late int playerCount;
  late int slotIndex;
  @MapTo('courtId')
  late $Court? court;
  @MapTo('ownerId')
  late $Player? owner;
  @MapTo('playerIds')
  late List<$Player> players;
  @MapTo('creditIds')
  late List<$PlayerCredit> playersCredits;
}

@RealmModel()
class $Player {
  @MapTo('_id')
  @PrimaryKey()
  late String id;

  late String accountId;
  late bool disabled;
  late bool deleted;
  late String email;
  late String role;
   
  [...]
  
  late DateTime createdAt;
  late DateTime lastConnection;

  @MapTo('favoriteClubIds')
  late List<$Club> favoriteClubs;
  @MapTo('favoriteSportIds')
  late List<$Sport> favoriteSports;
  late List<$PlayerLevelBySport> levels;
  @MapTo('friendIds')
  late List<$Player> friends;

  // Properties used in datatable source

  /// Only for datatable source
  @Ignored()
  int? numberOfCredit;

  /// Only for datatable source
  @Ignored()
  bool? hasSub;
}

@RealmModel()
class $PlayerCredit {
  @MapTo('_id')
  @PrimaryKey()
  late String id;
  late String accountId;
  late DateTime usedAt;
  late double price;

  late String? type;

  /// If it's a credit coming from subs, stripeId will be null.
  ///
  /// More than one PlayerCredit can have the same stripeId (with one payment paid more credit )
  late String? stripeId;
  @MapTo('playerId')
  late $Player? player;
  @MapTo('paidById')
  late $Player? paidBy;
  @MapTo('matchId')
  late $Match? match;
  @MapTo('offerId')
  late $PlayerSubscription? offer;
}

```

**Comment by nielsenko** [comment]
This line looks odd:
```dart
const Uuid().v4(),
```
Are you using the `uuid` package? Realm come bundled with `sane_uuid`. If you use that instead, you can also use `Uuid` instead of `String` as primary key on `$PlayerCredit`.

My bet would be that some code-path is removing the player credit from the match again later. 

The transaction guarantees that `credit` is added to `match.playerCredits` or not added to the realm at all, at the end of that transaction. Actually you don't need `realm.add(credit);` as that is implied by `match.playersCredits.add(credit);` What happens after I cannot attest to.

**Comment by geosebas** [comment]
> Are there any errors in the server logs related to the match or the credit document? I'm wondering if it's possible that the player credit got removed from the match either due to a validation error or due to a change somewhere.

I got no error for this, both on server and Sentry.

> Are you using the `uuid` package? Realm come bundled with `sane_uuid`. If you use that instead, you can also use `Uuid` instead of `String` as primary key on `$PlayerCredit`.

I do use `uuid`, but I don't think it's related. I started using it before `realm` so I kept it. 

> My bet would be that some code-path is removing the player credit from the match again later.

I do remove it somewhere in my code, but it's too in an transaction. 
I agree I assumed that my problem came from the add function, but it may come from this one when I remove it. 
Here the code : 
```
      final credits = match.playersCredits.where((element) => element.player?.id == oldPlayer.id).toList();

      if (credits.isNotEmpty) {
        match.playersCredits.removeWhere((element) => element.player?.id == oldPlayer.id);
        realm.deleteMany(credits);
      }
      await transaction.commitAsync();
      await realm.syncSession.waitForUpload();
```

> The transaction guarantees that `credit` is added to `match.playerCredits` or not added to the realm at all, at the end of that transaction. 

I agree that since in transaction it should be ok. 

> Actually you don't need `realm.add(credit);` as that is implied by `match.playersCredits.add(credit);` What happens after I cannot attest to.

Oh I didn't know about this, thanks for the tip !

**Comment by nirinchev** [comment]
If you're able to reproduce this while collecting trace level logs on the client, that would help a lot to try and identify the root cause.

**Comment by geosebas** [comment]
Unfortunately, I never managed to get any log on this issue. 
I posted here more in hope that you know about some issue like a race condition on array or anything that may be linked to this. 
If u don't, I think I will just re-design this part to avoid this problem !
