### ISSUE TITLE
New Model added to config are not working in isolate when syncing

### ISSUE THREAD

**Issue by richard457** [realm/realm-dart#1596]
### What happened?

Object type RealmCounter not configured in the current Realm's schema. Add type RealmCounter to your config before opening the Realm

### Repro steps

create a project then do sync in isolate then after create new model add it, then add code to sync same model in isolate, it will complain that the model is not added into config yet it is added in main isolate

### Version

3.19.3

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

Windows

### Code snippets

```dart
  final config = Configuration.flexibleSync(
      user,
      [
        RealmCounter.schema,
      ],
```

### Stacktrace of the exception/crash you're getting
```
[ERROR:flutter/runtime/dart_isolate.cc(1107)] Unhandled exception:
Realm error : Object type RealmCounter not configured in the current Realm's schema. Add type RealmCounter to your config before opening the Realm
#0      RealmMetadata.getByType (package:realm_dart/src/realm_class.dart:945:7)
```

**Comment by nielsenko** [comment]
Could you please create a small reproduction project of this?

**Comment by richard457** [comment]
I tried to reproduce same issue outside the project with no luck

**Comment by richard457** [comment]
something is wrong when attempt to sync the new model in isolate when there is existing model synced before

**Comment by richard457** [comment]
The root cause I believe lies within the fact that the first model added tothe config has encryption applied to them before thenew model is added I think??

**Comment by nirinchev** [comment]
How does the `realmConfig` function look like?

**Comment by richard457** [comment]
> How does the `realmConfig` function look like?

It looks like 
```dart
List<int> key = ProxyService.box.encryptionKey().toIntList();
    final config = Configuration.flexibleSync(
      user,
      [
        A.schema
        B.schema,
        C.schema, ---> This model was added later
      ],
      encryptionKey: key,
      path: path,
      clientResetHandler: RecoverUnsyncedChangesHandler(
        onBeforeReset: (beforeResetRealm) {
          log("reset requested here..");

          ///which the SDK invokes prior to the client reset.
          ///You can use this callback to notify the user before the reset begins.
        },
      ),
      shouldCompactCallback: ((totalSize, usedSize) {
        // Compact if the file is over 10MB in size and less than 50% 'used'
        const tenMB = 10 * 1048576;
        return (totalSize > tenMB) &&
            (usedSize.toDouble() / totalSize.toDouble()) < 0.5;
      }),
    );
```

**Comment by richard457** [comment]
Update on this @nirinchev @nielsenko ?

**Comment by richard457** [comment]
an update on this is highly appreciated.

**Comment by nirinchev** [comment]
Hey @richard457, it's Easter holidays here in Europe, which is why the eng team which monitors and responds to Github issues hasn't been available. We'll take a look next week when people come back, but if this is urgent and a blocker for you, you could file a support ticket which will be routed to the support team, which provides 24/7 coverage.

**Comment by richard457** [comment]
Hi @nirinchev Yes this has been a blocker for a month now, but I think we can wait until next week. Thank you.

**Comment by richard457** [comment]
Hi @nirinchev and the team update on this?

**Comment by nielsenko** [comment]
@richard457 No, no update yet. @nirinchev is currently on vacation, and neither @astigsen or @mpobrien are the right persons to contact for this. 

I think we do a fairly good job at keeping up with the issues here on github, but if you have an urgent need it is always better to contact support. We don't have any SLA on github issues.

That said, I'll divert my attention to this issue now.

**Comment by nielsenko** [comment]
@richard457 I tried to re-create the steps you outlined, and ended up with:
```dart
import 'dart:isolate';
import 'dart:math';

import 'package:realm_dart/realm.dart';

part 'issue1596.realm.dart';

@RealmModel()
class _Point {
  @PrimaryKey()
  @MapTo('_id')
  late String id;
  late int x;
  late int y;
  // late int z; // uncomment to try to trigger the issue

  @override
  String toString() => 'Point($id, $x, $y)'; // , $z)';
}

const appId = String.fromEnvironment('APP_ID');
final encryptionKey = List.generate(64, (index) => index);

final initRealm = () async {
  var app = App.getById(appId);
  final first = app == null;
  app ??= App(AppConfiguration(appId));

  var user = app.currentUser;
  assert(user != null || first);
  user ??= await app.logIn(Credentials.anonymous());

  final realm = await Realm.open(Configuration.flexibleSync(
    user,
    [Point.schema],
    encryptionKey: encryptionKey,
  ));

  if (first) {
    realm.subscriptions.update((mutableSubscriptions) {
      mutableSubscriptions.add(realm.all<Point>());
    });
  }

  return realm;
}();

Future<void> main(List<String> arguments) async {
  Realm.logger.setLogLevel(LogLevel.trace);

  final realm = await initRealm; // intialize realm first in main isolate
  const max = 25;

  Isolate.run(() async {
    final realm = await initRealm;
    final rnd = Random();
    while (true) {
      realm.write(() {
        realm.add(
          Point(
            String.fromCharCode(rnd.nextInt(25) + 65),
            rnd.nextInt(max),
            rnd.nextInt(max),
            // rnd.nextInt(max), // uncomment on schema update
          ),
          update: true,
        );
      });
      await Future.delayed(Duration(seconds: 1));
    }
  });

  await for (final c in realm.all<Point>().changes) {
    print(c.results);
  }
}
```
But it works just as expected. Can you point to something I have missed?

BTW, Just to be absolutely sure, you did enable development mode on the backend? Otherwise the server will not allow schema updates from the clients.

If you did enable development mode. Are you certain that you don't have different clients competing on what the schema should be. Ie. one updated, and one not?

**Comment by nielsenko** [comment]
I also tried adding a new realm model instead of a new property.

**Comment by richard457** [comment]
I can see in isolate you are calling initRealm again and in my example I only got instance of realm in isolate using appId and another difference is that I am using APi key instead of anonymous but I don't know if it is rerevant ...

**Comment by nielsenko** [comment]
Notice that on the 2nd call, inside the spawned isolate I'm also using `App.getById` because at that point it will return non-null.

Authentication method shouldn't matter.

What about my question regarding dev mode?

**Comment by richard457** [comment]
final app = lia.App.getById(AppSecrets.appId);
     user = app?.currentUser!;
    lia.FlexibleSyncConfiguration config =
        realmConfig(user, encryptionKey, dbPatch);

    final realm = lia.Realm(config);
