### ISSUE TITLE
 has duplicate values after migration

### ISSUE THREAD

**Issue by victorcode1** [realm/realm-dart#1615]
### What happened?

Primary key property 'Entity.id' has duplicate values after migration.. Error code: 2020.

### Repro steps

#0      _RealmCore.throwLastError.<anonymous closure> (package:realm_dart/src/native/realm_core.dart:142:11)
#1      using (package:ffi/src/arena.dart:124:31)
#2      _RealmCore.throwLastError (package:realm_dart/src/native/realm_core.dart:131:5)
#3      _RealmLibraryEx.invokeGetPointer (package:realm_dart/src/native/realm_core.dart:3415:17)
#4      _RealmCore.openRealm (package:realm_dart/src/native/realm_core.dart:653:32)
#5      Realm._openRealm (package:realm_dart/src/realm_class.dart:200:22)
#6      new Realm._ (package:realm_dart/src/realm_class.dart:134:98)
#7      new Realm (package:realm_dart/src/realm_class.dart:132:38)

### Version

last

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

ios

### Code snippets

  static final List<SchemaObject> schemes = [
    Entity.schema,

  ]; 

 RealmConfigSertvice() {
    _realmLocal = Realm(Configuration.local(
      schemaVersion: _realmnversion,
      migrationCallback: ((migration, oldSchemaVersion) {
        if (oldSchemaVersion < 1) {
          migration.renameProperty(
              'ConteoCrearStatusProductoUnidad', '_id', 'id');
        }
       
      schemes,
    ));
  }

### Relevant log output

```shell
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RealmException: Error opening realm at path /var/mobile/Containers/Data/Application/C450B357-B02A-4A86-8454-F089BE603521/Documents/default.realm. Primary key property 'Entity.id' has duplicate values after migration.. Error code: 2020.
#0      _RealmCore.throwLastError.<anonymous closure> (package:realm_dart/src/native/realm_core.dart:142:11)
#1      using (package:ffi/src/arena.dart:124:31)
#2      _RealmCore.throwLastError (package:realm_dart/src/native/realm_core.dart:131:5)
#3      _RealmLibraryEx.invokeGetPointer (package:realm_dart/src/native/realm_core.dart:3415:17)
#4      _RealmCore.openRealm (package:realm_dart/src/native/realm_core.dart:653:32)
#5      Realm._openRealm (package:realm_dart/src/realm_class.dart:200:22)
#6      new Realm._ (package:realm_dart/src/realm_class.dart:134:98)
#7      new Realm (package:realm_dart/src/realm_class.dart:132:38)
#8      new RealmConfigSertvice (package:invu_supply/config/utilities/realm_conf_service.dart:63:19)
#9      GetItInjectableX.init.<anonymous closure> (package:invu_supply/config/utilities/injectable.config.dart:96:46)
#10     GetItHelper.singleton (package:injectable/src/get_it_helper.dart:196:20)
#11     GetItInjectableX.init (package:invu_supply/config/utilities/injectable.config.dart:96:8)
#12     configureDependencies (package:invu_supply/config/utilities/injectable.dart:15:39)
#13     main (package:invu_supply/main.dart:45:3)
#14     _runMain.<anonymous closure> (dart:ui/hooks.dart:301:23)
#15     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#16     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by nielsenko** [comment]
Did you make `Entity.id` a primary key, when updating the schema?

**Comment by victorcode1** [comment]
@nielsenko yes

**Comment by victorcode1** [comment]
@nielsenko 
@RealmModel()
class _Entity {
  @PrimaryKey()
  ObjectId? id;
  late int? idproducto;
  late int? unitSelected;
  late int? idunidadFk;
  late String? codigo;
  late String? nameUnirSelected;
  late String? nombre;
  late double? cantidad;
  late List<_ConversioneR> conversiones = [];
  late int? unidad;
}

**Comment by nielsenko** [comment]
Realm is complaining that there are multiple objects with the same `id` after the migration, which is now illegal since it has become a primary key.

You need to remove all duplicates. The simplest thing is probably to just delete the realm entirely, if you can afford to loose the content.

**Comment by victorcode1** [comment]
That does not affect previous users who have a version and downloaded

**Comment by nielsenko** [comment]
Yes, it would affect any user who updates. You should only delete the realm, if you can afford to loose the data in it.

If you have customer data you need to preserve, then you need to either drop making `id` unique, or remove duplicates explicitly in your migration callback to avoid the issue. 

Is it by any chance all `id` values are `null`? If you added the `id` column as part of the schema change, then it needs to be populated for all existing entries as part of the migration.

**Comment by victorcode1** [comment]
How to remove duplicates

**Comment by nielsenko** [comment]
Read up on: https://www.mongodb.com/docs/realm/sdk/flutter/realm-database/model-data/update-realm-object-schema/#other-migration-tasks.

If you sort `Entity` from `oldRealm` on `_id` you can find the duplicates.

**Comment by victorcode1** [comment]
ok this is what i did


` if (oldSchemaVersion < 20) {
          final old = migration.oldRealm.all("ConteoCrearStatus");
          for (final oldVal in old) {
            // Find Person instance in the updated realm
            final newPerson =
                migration.findInNewRealm<ConteoCrearStatus>(oldVal);

            if (newPerson == null) {
              continue;
            } else {
              print('oldP ${oldVal.dynamic.get("id")}');
            }
          }
        }
'
and one more query stopped coming out. when I synchronize an object with flexibleSync
and inside I have a list I must make that object with
@RealmModel(ObjectType.embeddedObject)

**Comment by nielsenko** [comment]
Migration is currently only for local realms. See https://www.mongodb.com/docs/realm/sdk/flutter/realm-database/model-data/update-realm-object-schema/#updating-the-schema-of-a-synced-realm

Embedded objects are used for aggregate types. One advantage is that you don't have to setup dedicated subscriptions for embedded objects. They always follow their parent.

**Comment by nirinchev** [comment]
Can you post the error message with the full stack trace?

**Comment by victorcode1** [comment]
Hello,  @nirinchev   you have already resolved in a convenient way, I hope the documentation with reference to migrations really improves.
