### ISSUE TITLE
: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RealmException: An exception occurred while executing a user-provided callback. See userException for more details: RealmException: Property '_id' does not exist on class 'AlmacenRealm'

### ISSUE THREAD

**Issue by victorcode1** [realm/realm-dart#1618]
### What happened?

A bug happened!: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RealmException: An exception occurred while executing a user-provided callback. See userException for more details: RealmException: Property '_id' does not exist on class 'AlmacenRealm'

### Repro steps

 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RealmException: An exception occurred while executing a user-provided callback. See userException for more details: RealmException: Property '_id' does not exist on class 'AlmacenRealm'
E/flutter (32234): #0      _RealmCore.throwLastError.<anonymous closure> (package:realm_dart/src/native/realm_core.dart:134:9)
E/flutter (32234): #1      using (package:ffi/src/arena.dart:124:31)
E/flutter (32234): #2      _RealmCore.throwLastError (package:realm_dart/src/native/realm_core.dart:131:5)
E/flutter (32234): #3      _RealmLibraryEx.invokeGetPointer (package:realm_dart/src/native/realm_core.dart:3415:17)
E/flutter (32234): #4      _RealmCore.openRealm (package:realm_dart/src/native/realm_core.dart:653:32)
E/flutter (32234): #5      Realm._openRealm (package:realm_dart/src/realm_class.dart:200:22)
E/flutter (32234): #6      new Realm._ (package:realm_dart/src/realm_class.dart:134:98)
E/flutter (32234): #7      new Realm (package:realm_dart/src/realm_class.dart:132:38)

### Version

2.0.0

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

ios

### Code snippets

    `
      RealmConfigSertvice() {
        _realmLocal = Realm(Configuration.local(
          schemaVersion: _realmnversion,
          migrationCallback: ((migration, oldSchemaVersion) {
            if (oldSchemaVersion < 25) {
              var almacenRealmObjects = migration.oldRealm.all("AlmacenRealm");
    
              for (var obj in almacenRealmObjects) {
                final newPerson = migration.findInNewRealm<AlmacenRealm>(obj);
                if (newPerson == null) {
                  continue;
                }
                log('AlmacenRealm ${obj.dynamic.get("_id")}');
                newPerson.id = obj.dynamic.get("_id");
              }
            }
            if (oldSchemaVersion < 1) {}
          }),
          schemes,
        ));
      }`

### Stacktrace of the exception/crash you're getting

```shell
RealmConfigSertvice() {
    _realmLocal = Realm(Configuration.local(
      schemaVersion: _realmnversion,
      migrationCallback: ((migration, oldSchemaVersion) {
        if (oldSchemaVersion < 25) {
          var almacenRealmObjects = migration.oldRealm.all("AlmacenRealm");

          for (var obj in almacenRealmObjects) {
            final newPerson = migration.findInNewRealm<AlmacenRealm>(obj);
            if (newPerson == null) {
              continue;
            }
            log('AlmacenRealm ${obj.dynamic.get("_id")}');
            newPerson.id = obj.dynamic.get("_id");
          }
        }
        if (oldSchemaVersion < 1) {}
      }),
      schemes,
    ));
  }
```

### Relevant log output

```shell
RealmConfigSertvice() {
    _realmLocal = Realm(Configuration.local(
      schemaVersion: _realmnversion,
      migrationCallback: ((migration, oldSchemaVersion) {
        if (oldSchemaVersion < 25) {
          var almacenRealmObjects = migration.oldRealm.all("AlmacenRealm");

          for (var obj in almacenRealmObjects) {
            final newPerson = migration.findInNewRealm<AlmacenRealm>(obj);
            if (newPerson == null) {
              continue;
            }
            log('AlmacenRealm ${obj.dynamic.get("_id")}');
            newPerson.id = obj.dynamic.get("_id");
          }
        }
        if (oldSchemaVersion < 1) {}
      }),
      schemes,
    ));
  }
```

**Comment by victorcode1** [comment]
I don't know what this line of code does, but it was my solution.


     `shouldDeleteIfMigrationNeeded: true,`
     
     
 ` 
  RealmConfigSertvice() {
    _realmLocal = Realm(Configuration.local(
      shouldDeleteIfMigrationNeeded: true,
      schemaVersion: _realmnversion,
      migrationCallback: ((migration, oldSchemaVersion) {
        if (oldSchemaVersion < _realmnversion) {}
      }),
      schemes,
    ));
  }
`

**Comment by nirinchev** [comment]
What this line is doing is deleting the file whenever a migration is required. This means every time you try and change your data model, you'll wipe out your users' data, which is probably not what is intended unless you're using Realm as a caching solution and the source of truth is some other system.

**Comment by victorcode1** [comment]
@nirinchev Hello, thank you for explaining to me that's not exactly what I want to do but it was the solution to the step that I found, I can't figure out the migrations in flutter

**Comment by nirinchev** [comment]
I'm not sure what other migration issues you're facing, but the problem with the above snippet is - as @nielsenko said - due to trying to access the `_id` property on an object that doesn't have such a property. This is typically caused by creating a version of the object that didn't have `_id` and trying to migrate from it. Since you only have a single migration callback regardless of the original version, you have to be careful to only access properties that existed at the version supplied by `oldSchemaVersion`. Consider the following example:

```dart
// V1
class Person {
  late String name;
}

// V2
class Person {
  late int agge; // Typo
  late String name;
}

// V3
class Person {
  late int age;
  late String name;
}
```

If you migrate from v2->v3, you'd want to copy the value of `agge` into `age`. But if a user never upgraded to v2 and are migrating all the way from v1, they'd never get a property `agge`, so trying to copy the value from it would fail. So you'd need to do something more clever like:

```dart
migrationCallback: (migration, oldSchemaVersion) {
  final foos = migration.oldRealm.all("Foo");
  for (final foo in foos) {
    final newFoo = migration.findInNewRealm<Foo>(foo);
    if (newFoo == null) {
      continue;
    }

    if (oldSchemaVersion == 1) {
      // No agge property - just set the age to 0
      newFoo.age = 0;
    } else if (oldSchemaVersion == 2) {
      newFoo.age = foo.dynamic.get('agge');
    }
  }
}
```

Now, I don't know how your schema looked like in all 25 earlier versions, but my guess is that somewhere you didn't have `_id`, so you'd need to do something similar:

```dart
if (oldSchemaVersion < 13) {
  // We didn't have _id before 13, so just generate something
  newPerson.id = ObjectId();
} else if (oldSchemaVersion < 25) {
  // id was called _id before 25
  newPerson.id = obj.dynamic.get("_id");
}
```

**Comment by victorcode1** [comment]
@nirinchev I understand you perfectly and I appreciate your time. Basically what happened to me was the following: I have a project that I started with local realm, then I added synchronization but I still have the local version, when I added synchronization to one of the models I added a _id field with @MapTo("_id") and I started having problems

**Comment by victorcode1** [comment]
`  RealmConfigSertvice() {
    _realmLocal = Realm(Configuration.local(
      //shouldDeleteIfMigrationNeeded: true,
      schemaVersion: _realmnversion,
      migrationCallback: ((migration, oldSchemaVersion) {
        if (oldSchemaVersion < _realmnversion) {
          final foos = migration.oldRealm.all("AlmacenRealm");
          final cate = migration.oldRealm.all("CategoriasR");
          final permi = migration.oldRealm.all("PermisosRealm");
          final pro = migration.oldRealm.all("ProductoUnidadReam");
          final prove = migration.oldRealm.all("ProveedorRealm");
          final uni = migration.oldRealm.all("UnidadRealm");

          for (final foo in foos) {
            final newFoo = migration.findInNewRealm<AlmacenRealm>(foo);
            if (newFoo == null) {
              continue;
            }
            if (oldSchemaVersion < _realmnversion) {
              // newFoo.id = foo.dynamic.get("_id");
              newFoo.id = ObjectId();
            }
          }
          for (final ca in cate) {
            final category = migration.findInNewRealm<CategoriasR>(ca);
            if (category == null) {
              continue;
            }
            if (oldSchemaVersion < _realmnversion) {
              // newFoo.id = foo.dynamic.get("_id");
              category.id = ca.dynamic.get("id");
            }
          }
          for (final perm in permi) {
            final permisos = migration.findInNewRealm<PermisosRealm>(perm);
            if (permisos == null) {
              continue;
            }
            if (oldSchemaVersion < _realmnversion) {
              // newFoo.id = foo.dynamic.get("_id");
              permisos.id = ObjectId();
            }
          }
          for (final pro in pro) {
            final producto = migration.findInNewRealm<ProductoUnidadReam>(pro);
            if (producto == null) {
              continue;
            }
            if (oldSchemaVersion < _realmnversion) {
              // newFoo.id = foo.dynamic.get("_id");
              producto.id = ObjectId();
            }
          }
          for (final prov in prove) {
            final proveedor = migration.findInNewRealm<ProveedorRealm>(prov);
            if (proveedor == null) {
              continue;
            }
            if (oldSchemaVersion < _realmnversion) {
              // newFoo.id = foo.dynamic.get("_id");
              proveedor.i = ObjectId();
            }
          }
          for (final un in uni) {
            final unidad = migration.findInNewRealm<UnidadRealm>(un);
            if (unidad == null) {
              continue;
            }
            if (oldSchemaVersion < _realmnversion) {
              // newFoo.id = foo.dynamic.get("_id");
              unidad.i = ObjectId();
            }
          }
        }
      }),
      schemes,
    ));
  }`
  I don't know what I did but that's how I solved it

**Comment by nirinchev** [comment]
Happy to hear you were able to find a solution!

**Comment by victorcode1** [comment]
Tnk @nirinchev @nielsenko
