### ISSUE TITLE
 Add a privacy manifest in realm-dart for iOS

### ISSUE THREAD

**Issue by jssuthahar** [realm/realm-dart#1630]
### What happened?

We recently became aware that, according to the new Apple privacy regulations, third-party SDKs will also be required to provide a [Privacy Manifest ](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) , Pls help us to add this 

### Repro steps

I can see its done [RealmSwift](https://github.com/realm/realm-swift/issues/8428), Could you please provide fix for Flutter

### Version

1622

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

iOS and Android

**Comment by nirinchev** [comment]
This is a duplicate of https://github.com/realm/realm-dart/issues/1551.
