### ISSUE TITLE
version (2.1.0 != 2.0.0)

### ISSUE THREAD

**Issue by victorcode1** [realm/realm-dart#1644]
### What happened?

Update realm to 2.1.0[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RealmException: Realm SDK package version does not match the native library version (2.1.0 != 2.0.0). This is likely a bug in the Realm SDK - please file an issue at https://github.com/realm/realm-dart/issues
#0      _realmLib.<anonymous closure> (package:realm_dart/src/native/realm_core.dart:52:5)
#1      _realmLib (package:realm_dart/src/native/realm_core.dart:55:2)
#2      _realmLib (package:realm_dart/src/native/realm_core.dart)
#3      new _RealmCore (package:realm_dart/src/native/realm_core.dart:104:5)
#4      realmCore (package:realm_dart/src/native/realm_core.dart:81:24)
#5      realmCore (package:realm_dart/src/native/realm_core.dart)
#6      Configuration.defaultStoragePath (package:realm_dart/src/configuration.dart:85:14)
#7      Configuration.defaultRealmPath (package:realm_dart/src/configuration.dart:95:47)
#8      Configuration.defaultRealmPath (package:realm_dart/src/configuration.dart)
#9      Configuration._defau<…>

### Repro steps

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RealmException: Realm SDK package version does not match the native library version (2.1.0 != 2.0.0). This is likely a bug in the Realm SDK - please file an issue at https://github.com/realm/realm-dart/issues
#0      _realmLib.<anonymous closure> (package:realm_dart/src/native/realm_core.dart:52:5)
#1      _realmLib (package:realm_dart/src/native/realm_core.dart:55:2)
#2      _realmLib (package:realm_dart/src/native/realm_core.dart)
#3      new _RealmCore (package:realm_dart/src/native/realm_core.dart:104:5)
#4      realmCore (package:realm_dart/src/native/realm_core.dart:81:24)
#5      realmCore (package:realm_dart/src/native/realm_core.dart)
#6      Configuration.defaultStoragePath (package:realm_dart/src/configuration.dart:85:14)
#7      Configuration.defaultRealmPath (package:realm_dart/src/configuration.dart:95:47)
#8      Configuration.defaultRealmPath (package:realm_dart/src/configuration.dart)
#9      Configuration._defau<…>

### Version

2.10.

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

ios

### Stacktrace of the exception/crash you're getting

```shell
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RealmException: Realm SDK package version does not match the native library version (2.1.0 != 2.0.0). This is likely a bug in the Realm SDK - please file an issue at https://github.com/realm/realm-dart/issues
#0      _realmLib.<anonymous closure> (package:realm_dart/src/native/realm_core.dart:52:5)
#1      _realmLib (package:realm_dart/src/native/realm_core.dart:55:2)
#2      _realmLib (package:realm_dart/src/native/realm_core.dart)
#3      new _RealmCore (package:realm_dart/src/native/realm_core.dart:104:5)
#4      realmCore (package:realm_dart/src/native/realm_core.dart:81:24)
#5      realmCore (package:realm_dart/src/native/realm_core.dart)
#6      Configuration.defaultStoragePath (package:realm_dart/src/configuration.dart:85:14)
#7      Configuration.defaultRealmPath (package:realm_dart/src/configuration.dart:95:47)
#8      Configuration.defaultRealmPath (package:realm_dart/src/configuration.dart)
#9      Configuration._defau<…>
```

**Comment by nielsenko** [comment]
@victorcode1 Could you please run `flutter clean` and try again?

**Comment by victorcode1** [comment]
Real instaló tnk @nielsenko
