### ISSUE TITLE
Apple Privacy Manifest Error after 2.2.0

### ISSUE THREAD

**Issue by Bilonik** [realm/realm-dart#1656]
### What happened?

HI @nirinchev and @nielsenko

This was release with update 2.2.0 but its failing when uploading to the app store with this error:

Invalid bundle structure. The “Runner.app/Frameworks/realm.framework/realm_privacy.bundle/realm_privacy” binary file is not permitted. Your app cannot contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. For details, visit: https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle

### Repro steps

Upload to App Store Connect

### Version

2.2.0

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

ios

**Comment by nielsenko** [comment]
Could you open the `ios/Runner.xcworkspace` in xcode and check how Mach-O type looks for `realm-realm_privacy` target?

<img width="1039" alt="image" src="https://github.com/realm/realm-dart/assets/22237677/f8b5fef9-49c5-4637-9cb8-542d7fdc5db3">

**Comment by rouuuge** [comment]
i have the same problem. The Mach-O Type looks the same like the screenshot above

**Comment by nirinchev** [comment]
Hey folks, I think we have a fix for this, but would appreciate if you can verify it before we cut a release. Can you download these packages: https://static.realm.io/downloads/dart/2.2.0-7ff9130187a186a7cd9b90e0375a00d371ebacd6/packages.tar.gz and replace your realm dependency in your pubspec with a path one like this:

```yaml
dependencies
  realm:
    path: ../realm
```

(assuming the packages are located a folder above your app's pubspec.yaml). The packages are identical to what's released in 2.2.0, with minor modifications of the podspec to try and place the privacy manifest in the correct resource location rather than in a resource bundle.

**Comment by rouuuge** [comment]
Seems to work!

**Comment by nirinchev** [comment]
Great, we'll double check that the approach is the correct one with our iOS engineers but expect to have a hotfix for this by the end of the week.

**Comment by Bilonik** [comment]
@nirinchev i am getting this error, when using the package with the workaround fix.

![Simulator Screenshot - iPhone 15 Pro Max - 2024-05-02 at 11 21 39](https://github.com/realm/realm-dart/assets/8235588/c288f472-2091-4820-ab92-7457681a60f2)

**Comment by nirinchev** [comment]
Can you try running `flutter clean`?

**Comment by rouuuge** [comment]
oh same here 🤦🏽‍♂️
sorry i just checked the upload to testflight

**Comment by nielsenko** [comment]
@Bilonik & @rouuuge This concept of creating staging packages is a bit rough in the edges still.

Can I ask you to add `pubspec_overrides.yaml` file to your project, that looks like this:
```yaml
dependency_overrides:
  realm_common:
    path: ../realm_common
  realm_dart:
    path: ../realm_dart
  realm_generator:
    path: ../realm_generator
  realm:
    path: ../realm
```
Assuming that matches the location of the downloaded packages relative to your project.

Then run:
```shell
dart run realm install -t macos # or what platform you are using
flutter clean
flutter run -d macos
```

**Comment by Bilonik** [comment]
Hi @nielsenko and @rouuuge 

I made this change #1657 locally and it worked.

**Comment by nielsenko** [comment]
@Bilonik Good to hear, and that I would expect as well. However, setting `resources` directly as opposed to adding a `resource_bundle` is not recommend due to potential conflicts (see the [Podspec Syntax Reference](https://guides.cocoapods.org/syntax/podspec.html)). Though, as long as you don't have other pods conflicting on resources you should be fine.

**Comment by Bilonik** [comment]
Hi @nielsenko 

i can confirm with this new PR #1658  everything works good.

Thanks

**Comment by nielsenko** [comment]
@Bilonik and @rouuuge 

If you have time for it, could I ask you to download and test the packages here https://static.realm.io/downloads/dart/2.2.0-7e968e330ab7a76bbd5c76a9b28c4013ec1cb3c2/packages.tar.gz. 

Same procedure as above.

**Comment by rouuuge** [comment]
done! can confirm that it works now

**Comment by stevenosse** [comment]
Hi
I'm still having the issue with realm 2.2.1

**Comment by nirinchev** [comment]
What issue are you having?

**Comment by stevenosse** [comment]
Hi

Here is the error i'm getting after uploading the build on AppstoreConnect

> ITMS-90288: Invalid Code Signing Entitlements - The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. According to the provisioning profile, the bundle contains a key value that is not allowed: '' for the key 'com.apple.application-identifier' in 'Paper.app/Contents/Frameworks/librealm_dart.dylib'

> ITMS-90286: Invalid Code Signing Entitlements - Your application bundle's signature contains code signing entitlements that are not supported on macOS. Specifically, value '' for key 'com.apple.application-identifier' in 'Paper.app/Contents/Frameworks/librealm_dart.dylib' is not supported. This value should be a string starting with your TEAMID, followed by a dot '.', followed by the bundle identifier .

> Apple Developer Relations

Realm version: `realm: ^2.2.1`

Pubspec.lock
<img width="626" alt="Capture d’écran 2024-05-22 à 09 26 07" src="https://github.com/realm/realm-dart/assets/33069233/1e9f3648-53b9-4d74-94b7-3ec62d92aa3a">

**Comment by nielsenko** [comment]
@stevenosse This is not the same issue as this, but instead https://github.com/realm/realm-dart/issues/1679

**Comment by stevenosse** [comment]
Yes, my apologies, I should have been more careful.
