### ISSUE TITLE
Realm binary files take a lot of space in apk file, and include binary files for non-target platform.

### ISSUE THREAD

**Issue by zhxst** [realm/realm-dart#1670]
### What happened?

My previous Flutter app takes about 63 MB in apk release build.
After import Realm, the apk file size become 131 MB, which is double from before.

By unpack the release package. It turns out that Realm include binary files for all the target platform.
By default, flutter only build for `android-arm`, `android-arm64` and `android-x64`. But realm also include `android-x86` binary files. Which takes 18.6MB extra space.

Here is another example , which only target `android-arm64` when build:
![image](https://github.com/realm/realm-dart/assets/11647836/bacb02e4-e3e2-481a-9fd1-0e5671a34845)

So please make realm package follow the `flutter --target-platform`, this will save a lot of space for release build apks.

Thank you.

### Repro steps

1.  Use any Flutter project which import realm.
2. Build android apk, use `--target-platform` or `--split-per-abi`.
3. Unpack the generate apks. Check the realm binary files inside apk.

### Version

3.19.5

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

macOS 13.6

**Comment by nirinchev** [comment]
@nielsenko do you know if Google Play repackages flutter apps to remove binaries for architectures that don't match the install device? I remember this used to work for .NET apps but I'm not sure if there's anything in Flutter that would prevent this mechanism from working.

**Comment by nielsenko** [comment]
I'm not sure where you get the 161MB from. If I do `flutter build apk` on a basic project using realm, I get an apk size of 36.8MB. 
```sh
flutter build apk

Directory: '/Users/kasper/.puro/shared/pub_cache/hosted/pub.dev/realm-2.2.1/android/src/main/cpp/lib'
Realm binaries for 2.2.1 already downloaded
Realm install command finished.
Running Gradle task 'assembleRelease'...                            5.6s
✓ Built build/app/outputs/flutter-apk/app-release.apk (36.8MB)
```
If I use `flutter build apk --split-per-abi` I get:
```sh
flutter build apk --split-per-abi

Directory: '/Users/kasper/.puro/shared/pub_cache/hosted/pub.dev/realm-2.2.1/android/src/main/cpp/lib'
Realm binaries for 2.2.1 already downloaded
Realm install command finished.
Running Gradle task 'assembleRelease'...                            7.8s
✓ Built build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk (9.8MB)
✓ Built build/app/outputs/flutter-apk/app-arm64-v8a-release.apk (11.7MB)
✓ Built build/app/outputs/flutter-apk/app-x86_64-release.apk (11.6MB)
```

However. In general you should avoid using `apk`s and instead build an [app bundle](https://docs.flutter.dev/deployment/android#build-an-app-bundle) by invoking `flutter build appbundle`. If you upload a full bundle to Google Play it should split correctly, and your users should only download for the target platform.
The only reason to use `apk`s is if you distribute your app by some other mean that doesn't support Android app bundles.

When I do that I get:
```sh
flutter build appbundle

Directory: '/Users/kasper/.puro/shared/pub_cache/hosted/pub.dev/realm-2.2.1/android/src/main/cpp/lib'
Realm binaries for 2.2.1 already downloaded
Realm install command finished.
Running Gradle task 'bundleRelease'...                              8.5s
✓ Built build/app/outputs/bundle/release/app-release.aab (36.9MB)
```
but notice that the play store will split this up for you, before the user download the app

@zhxst Have you tried opening a bundle retrieved from Google play?

**Comment by zhxst** [comment]
I know that Play Store will generate smaller apk.
But some time I have to send universal apk file to my colleague or customer for test.
So `--split-per-abi` works correct but `--target-platform` not I guess.
I will try to use --split-per-abi as workaround.

**Comment by nielsenko** [comment]
@zhxst `--split-per-abi` is not a work-around. If you insist on creating apks, then that is the recommended approach. See https://docs.flutter.dev/deployment/android#build-an-apk.

**Comment by nielsenko** [comment]
> ... But some time I have to send universal apk file to my colleague or customer for test.

@zhxst If you insist on sending a [fat-apk](https://docs.flutter.dev/deployment/android#what-is-a-fat-apk) then yes realm will currently cost 36.8MB, but I'm dropping the x86 slice in #1682, so that should strip it down a bit (to ~30MB).

**Comment by zhxst** [comment]
@nielsenko Thank you for your response. `--split-per-abi` is a good idea. Remove the x86 slice also helps.
I guess it's a bug of `--split-per-abi` from Flutter side. Because I found another plugin also have this issue.
Maybe I will file an issue to the flutter team.
