### ISSUE TITLE
Error deleting realm file

### ISSUE THREAD

**Issue by Bilonik** [realm/realm-dart#1674]
### What happened?

Cant Delete realm file after close.

### Repro steps

1.Close the realm.
2.Try to delete the file.
3.Boom

### Version

2.2.1

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

iOS 

### Code snippets

   //Get realm's file path
    final path = realmSource.realm.config.path;

    realmSource.realm.close();
    await config.closeConfiguration();
    print("Realm is closed: ${realmSource.realm.isClosed}"); // Prints TRUE
    // Delete the realm
    try {
      Realm.deleteRealm(path);
    } catch (e) {
      if (kDebugMode) {
        print(e);
      }
    }

### Stacktrace of the exception/crash you're getting

```shell
flutter: Realm is closed: true
flutter: RealmException: Error deleting realm at path /Users/XXX/Library/Containers/XXX/Data/Library/Application Support/mongodb-realm/XXXX/XXXX/default.realm. Cannot delete files of an open Realm: '/Users/XXX/Library/Containers/XXX/Data/Library/Application Support/mongodb-realm/XXXX/XXXX/default.realm' is still in use.. Error code: 2012.
```

**Comment by nirinchev** [comment]
When sync is being used, the Realm file is not necessarily released immediately after closing it. The sync process will release it asynchronously and may continue using it if there's data to be uploaded.

**Comment by Bilonik** [comment]
@nirinchev 
Do you have a workaround?

**Comment by nirinchev** [comment]
Depends on what is your use case - is this for a test project or part of your app's functionality? One approach would be to retry the deletion with a delay. If you don't care about the changes being uploaded you could also pause the sync session before that:

```dart
realm.syncSession.pause();
realm.close();

for (var i = 0; i < 100; i++) {
  try {
    Realm.deleteRealm(path);
  } catch (e) {
    await Future.delayed(Duration(seconds: 1))
  }
}
```

**Comment by Dararii** [comment]
I got the same error. But when I wait for the sync process to be done, it took forever.

```
db.syncSession.waitForDownload();
db.syncSession.waitForUpload();
```

I tried it on empty database, but the code above wait forever. any solution?

**Comment by nielsenko** [comment]
@Dararii The code above will wait until it actually contacts the server. Try adding trace, it will tell you a lot about what is happening.

Here is a very simplistic and verbose trace setup, but you can elaborate from there:
```dart
  Realm.logger.setLogLevel(LogLevel.detail);
  Realm.logger.onRecord.listen(print);
```
