### ISSUE TITLE
Not able to create `Realm` object with different `schemaObjects` which uses `writeAsync()` method

### ISSUE THREAD

**Issue by shivanuj13** [realm/realm-dart#1675]
### What happened?

I encounter an issue when attempting to instantiate a `Realm` object with different `schemaObjects` while utilizing the `writeAsync()` method. I've created two distinct functions to write data, each internally invoking `realm.writeAsync()`. Both functions initialize a `Realm` object by invoking its constructor with a specific configuration. Notably, each function has a different `schemaObject` specified in its `configuration`.

When these two functions are called within my code, the debugger becomes unresponsive during the initialization step of the Realm object within these functions. No exceptions are thrown, and the issue remains unresolved. However, if I precede these function calls with `await`, the code behaves as expected. Additionally, replacing `realm.writeAsync()` with `realm.write()` results in expected behavior.

Note: on modifying the code as described (replacing `writeAsync()` with `write()` or preceding function calls with `await`), it is necessary to clear the application data and uninstall the application to reproduce this issue.

### Repro steps

1. Create 2 different RealmModel
2. Create 2 different function to utilize `writeAsync()` method
3. call these 2 function without putting `await` in main code

NOTE: i have added full code snippet to reproduce this issue

### Version

Flutter 3.19.3 Dart 3.3.1

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

Android SDK version - 33

### Code snippets

//car.dart
```Dart
import 'package:realm/realm.dart';

part 'car.realm.dart'; 

@RealmModel()
class _Car {
  late String make;

  late String model;

  int? kilometers = 500;
}
}
```
//hotel.dart
```Dart
import 'package:realm/realm.dart';  

part 'hotel.realm.dart'; 

@RealmModel() 
class _Hotel {

  late String city;
  late int price;

}
```

//main.dart
```Dart
import 'package:flutter/material.dart';
import 'package:flutter_application_1/car.dart';
import 'package:flutter_application_1/hotel.dart';
import 'package:realm/realm.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              ElevatedButton(
                onPressed: () {
                  debugPrint("Hello World");
                },
                child: const Text("Click me"),
              ),
              ElevatedButton(
                  onPressed: () {
                    // add await here to get expected result
                    writeCarData().then((value) => debugPrint("Car data written"));
                    writeHotelData().then((value) => debugPrint("Hotel data written"));
                  },
                  child: const Text("Click me")),
            ],
          ),
        ),
      ),
    );
  }
}

Future<void> writeCarData() async {
  var config = Configuration.local([Car.schema]);
  var realm = Realm(config);

  var car = Car("Tesla", "Model Y", kilometers: 5);
  await realm.writeAsync(() {
    realm.add(car);
  });
}

Future<void> writeHotelData() async {
  var config = Configuration.local([Hotel.schema]);
  var realm = Realm(config);

  var hotel = Hotel(
    "abc",
    1000,
  );
  await realm.writeAsync(() {
    realm.add(hotel);
  });
}
```

**Comment by MachariaK** [comment]
I experienced this and was debugging over the last 24 hours. There are no exceptions thrown. I have replaced all realm.writeAsync with realm.write and my app now works. It was freezing with no exceptions in the console.

**Comment by nielsenko** [comment]
I can confirm this deadlocks when trying to open the realm the second time around with the different schema.

**Comment by nielsenko** [comment]
@shivanuj13  If you downgrade to realm 1.9.0 you can avoid this deadlock.

**Comment by nielsenko** [comment]
Another way to avoid this is to avoid the different schemas altogether. I general I would recommend opening a single realm per isolate, using a fully combined schema like this:
```dart
final config = Configuration.local([Car.schema, Hotel.schema]);
final realm = Realm(config);

Future<void> writeCarData() async {
  var car = Car("Tesla", "Model Y", kilometers: 5);
  await realm.writeAsync(() {
    realm.add(car);
  });
}

Future<void> writeHotelData() async {
  var hotel = Hotel(
    "abc",u 
  );
  await realm.writeAsync(() {
    realm.add(hotel);
  });
}
```
Hence you avoid updating the schema of the realm file when opening the realm the second time around. It is also more efficient to keep a single `Realm` instance around.

**Comment by nirinchev** [comment]
Opening the same Realm with a different schema without bumping the schema version should not work and if it did in the past it was an accidental mistake. We're going to investigate the locking there, but it's still unsupported scenario and as @nielsenko suggested, you could either reuse the Realm instance or make sure that the configs you use to open the two instances are identical.

**Comment by nirinchev** [comment]
The deadlock is related to a synchronous write being scheduled while the async write holds the lock - thus the sync write blocking the thread that the async write is trying to schedule the continuation on.

**Comment by nirinchev** [comment]
This is tracked by https://github.com/realm/realm-core/issues/7693.
