### ISSUE TITLE
The generated *.realm.dart file has lot of compile issues

### ISSUE THREAD

**Issue by abhinovpankaj** [realm/realm-dart#1677]
### What happened?

Recently I updated the realm package to the latest version realm: ^2.2.1. Also updated the flutter SDK

Post upgrade, I removed the old *.g.dart file and then ran the **_dart run realm generate_** command.
The file was created but with lot of issues not sure what is wrong is it my realm model file?

### Repro steps

1.  Update the flutter SDK
2. Update the realm package to the latest version realm: ^2.2.1. 
3. Run dart run realm geenrate command.

### Version

3.22.0

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

macOS 14.4.1 23E224 darwin-arm64

### Code snippets

```dart
@RealmModel()
class _Project {
  @MapTo('_id')
  @PrimaryKey()
  late ObjectId id;

  late String? name;
  late String? projecttype;
  late String? description;
  late String? address;
  late String? createdby;
  late String? createdat;
  late String? url;
  late String? editedat;
  late String? companyIdentifier;
  String? lasteditedby;
  late Set<String> assignedto;
  List<_Child> children = [];
  bool iscomplete = false;
  // List<_Child> invasiveChildren = [];
  bool isInvasive = false;
  List<_Section> sections = [];
  // List<_Section> invasiveSections = [];
}
```
Output generated:
```dart
@override
Project freeze() => RealmObjectBase.freezeObject<Project>(this);

EJsonValue toEJson() {
return <String, dynamic>{
'_id': id.toEJson(),
'name': name.toEJson(),
'projecttype': projecttype.toEJson(),
'description': description.toEJson(),
'address': address.toEJson(),
'createdby': createdby.toEJson(),
'createdat': createdat.toEJson(),
'url': url.toEJson(),
'editedat': editedat.toEJson(),
'companyIdentifier': companyIdentifier.toEJson(),
'lasteditedby': lasteditedby.toEJson(),
'assignedto': assignedto.toEJson(),
'children': children.toEJson(),
'iscomplete': iscomplete.toEJson(),
'isInvasive': isInvasive.toEJson(),
'sections': sections.toEJson(),
};
}
static EJsonValue _toEJson(Project value) => value.toEJson();
static Project _fromEJson(EJsonValue ejson) {
return switch (ejson) {
{
'_id': EJsonValue id,
'name': EJsonValue name,
'projecttype': EJsonValue projecttype,
'description': EJsonValue description,
'address': EJsonValue address,
'createdby': EJsonValue createdby,
'createdat': EJsonValue createdat,
'url': EJsonValue url,
'editedat': EJsonValue editedat,
'companyIdentifier': EJsonValue companyIdentifier,
'lasteditedby': EJsonValue lasteditedby,
'assignedto': EJsonValue assignedto,
'children': EJsonValue children,
'iscomplete': EJsonValue iscomplete,
'isInvasive': EJsonValue isInvasive,
'sections': EJsonValue sections,
} => Project(
fromEJson(id),
name: fromEJson(name),
projecttype: fromEJson(projecttype),
description: fromEJson(description),
address: fromEJson(address),
createdby: fromEJson(createdby),
createdat: fromEJson(createdat),
url: fromEJson(url),
editedat: fromEJson(editedat),
companyIdentifier: fromEJson(companyIdentifier),
lasteditedby: fromEJson(lasteditedby),
assignedto: fromEJson(assignedto),
children: fromEJson(children),
iscomplete: fromEJson(iscomplete),
isInvasive: fromEJson(isInvasive),
sections: fromEJson(sections),
),
_ => raiseInvalidEJson(ejson),
};
}
```

**Comment by bbrockit** [comment]
I have the same issue after upgrading to Realm 2.2.1.   The generator is producing a switch syntax which isn't valid Dart.  The way it's accessing fields in Object? may not be correct either.  You can either downgrade Realm or manually fix the schemas.realm.dart file while waiting for a fix to the generator. 

I had to upgrade Realm to 2.2.1 because I had upgraded Flutter/Dart, which raised other issues with the code generated by Realm (It didn't like the const on the object return statements), so I don't have a choice but to stick with this Realm version and manually fix the generated schema file even though we're not supposed to.

My project runs fine after making these changes.  Here's an example using one of my Realm classes where I changed the generated code from this:

```
return switch (ejson) {
      {
        'id': EJsonValue id,
      } =>
        SettingsRealm(
          fromEJson(id),
        ),
      _ => raiseInvalidEJson(ejson),
    };
```
To this: 
```
if (ejson is Map<String, dynamic>) {
    final id = ejson['id'];
    if (id != null && id != null) {
      return SettingsRealm(
          fromEJson(id),
      );
    }
  }
return raiseInvalidEJson(ejson);
```
Be sure to make a backup copy so your edited version doesn't get overwritten by the generator.

**Comment by nirinchev** [comment]
What's your dart version? This is most definitely valid dart, but it's possible that it requires a newer version than what you have.

**Comment by bbrockit** [comment]
I'm running the lastest stable version, Dart 3.4.0

**Comment by bbrockit** [comment]
My mistake, I wasn't familiar with the dart 3 switch statement.  

I able to use the generated schema file now with the switch syntax.  I had upgraded to Dart 3.4, but the min SDK version in the environment field of my pubspec.yaml was still set below 3, which was the root problem.

**Comment by abhinovpankaj** [comment]
For now I have downgraded to older realm version as I have other different libraries which are failing on the latest flutter sdk.
