### ISSUE TITLE
Add To Map/Json

### ISSUE THREAD

**Issue by akashefrath** [realm/realm-dart#1688]
### Problem

Hey kindly add toJson or toMap for realm model its allow developer to see the data and use it if even realm is close.

### How important is this improvement for you?

I would like to have it but have a workaround

### Feature would mainly be used with

Local Database only

**Comment by nirinchev** [comment]
Realm objects already provide `.toEJson` method - does that not fit your needs?

**Comment by nickolasdeluca** [comment]
I managed to workaround this "issue" with Flutter's [extensions](https://dart.dev/language/extension-methods).

Sample:

```dart
import 'package:realm/realm.dart';

part 'user.realm.dart';

@RealmModel()
class _User {
  @PrimaryKey()
  late int? id;
  late String? name;
}

extension UserExtension on User {
  fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];

    return this;
  }

  Map<String, dynamic> toJson() {
    Map<String, dynamic> data = {};

    data['id'] = id;
    data['name'] = name;

    return json;
  }
}
```

And then, to create your object:

```dart
User user = User(null).fromJson(json['user']);
```

The only downside so far is having to create the object with a null only to instantiate it, I can't find out how to make the identifier nullable. If anyone knows how to make it optional feel free to contribute.

**Comment by Shreedhar73** [comment]
@nirinchev 
Since `dynamic` is not a RealmType, I cannot define the type of a field as Map<String,dynamic>  , so it needs to be defined as Map<String,RealmValue>. 

So while using .toEJSON() on RealmMap, it is throwing 

```MissingEncoder (Missing encoder for type RealmValue (RealmValue(In elementary algebra, 0 is the additive identity and the product of 0 and any number is 0.)))``` 

On the ejson-0.3.0 , i think parsing is yet to be handled for 'RealmMap' 

```
EJsonValue _encodeAny(Object? value) {
  return switch (value) {
    null => null,
    bool b => _encodeBool(b),
    DateTime d => _encodeDate(d),
    Defined<dynamic> d => _encodeDefined(d),
    double d => _encodeDouble(d),
    int i => _encodeInt(i),
    BsonKey k => _encodeKey(k),
    Uint8List b => _encodeBinary(b, subtype: '00'),
    Iterable<dynamic> l => _encodeArray(l),
    Map<dynamic, dynamic> m => _encodeDocument(m),
    ObjectId o => _encodeObjectId(o),
    String s => _encodeString(s),
    Symbol s => _encodeSymbol(s),
    Undefined<dynamic> u => _encodeUndefined(u),
    Uuid u => _encodeUuid(u),
    _ => _encodeCustom(value),
  };
} 
```

**Comment by nielsenko** [comment]
@Shreedhar73 You have hit a bug.

However, if you want to store fully dynamic json, you can use `RealmValue.fromJson` and have a `RealmValue` on your model instead of a `Map<String, RealmValue>>`.

**Comment by nielsenko** [comment]
We don't have a corresponding `RealmValue.toJson`, but you can easily add one yourself like:
```dart
import 'dart:convert';

import 'package:realm_dart/realm.dart';

part 'json_roundtrip.realm.dart';

@RealmModel()
class _Doc {
  late RealmValue content;
}

final realm = Realm(Configuration.inMemory([Doc.schema]));

final input = '{"list": [1, 2, 3], "key": {"nested": "value"}}';

void main(List<String> arguments) {
  realm.write(() {
    realm.add(Doc(content: RealmValue.from(jsonDecode(input))));
  });

  final doc = realm.all<Doc>().first;
  final content = doc.content;
  
  // convert back to JSON
  final contentAsJson = content.toJson();

  // print it
  final output = jsonEncode(contentAsJson);
  print(output);

  Realm.shutdown(); // only needed in Dart cli apps
}

extension on RealmValue {
  dynamic toJson() {
    return switch (value) {
      List<RealmValue> list => list.map((e) => e.toJson()).toList(),
      Map<String, RealmValue> map => map.map((k, v) => MapEntry(k, v.toJson())),
      // sets are not used in JSON, but we can convert them to lists
      Set<RealmValue> set => set.map((e) => e.toJson()).toList(),
      Set set => set.toList(), // set of primitives
      _ => value, // primitives
    };
  }
}
```
The important part is just the extension method, the rest is just for illustration.

**Comment by Shreedhar73** [comment]
@nielsenko Thanks, works perfectly for my usecase
