### ISSUE TITLE
Can Realm be called inside native code?

### ISSUE THREAD

**Issue by gamestap99** [realm/realm-dart#1690]
### Problem

Hello, I need to find a storage synchronization solution that runs both flutter and swift. And I see that realm also has a swift 1 package. I wonder if they can really synchronize

### How important is this improvement for you?

-- select --

### Feature would mainly be used with

-- select --

**Comment by nielsenko** [comment]
Realm support both Flutter and Swift, but not (currently) in the same process. (see https://github.com/realm/realm-dart/issues/1195).

You can sync between apps written with different frameworks, as long as you ensure they agree on the schema.

**Comment by gamestap99** [comment]
@nielsenko THANKS FOR INFORMATION
