### ISSUE TITLE
Make auto download and install during builds optional

### ISSUE THREAD

**Issue by proswdev** [realm/realm-dart#1703]
### Problem

Realm for Flutter requires a new install on every build through the downloadRealmBinaries task. Not only will builds fail if internet is not available, it also assumes Realm has the liberty to download and install whatever it thinks it needs at that moment. Both factors are huge issues for many CI/CD pipelines. Based on my experience working in large companies like Amazon, internet connectivity and downloads during CI/CD will be rejected by infosec teams in many companies of reasonable size. 

### Solution

Most flutter packages don't require downloads during builds but can rely on an offline preinstalled cache. Please make the reinstall during builds optional. Since it's not normal flutter package behavior, I would highly recommend turning auto installs during builds off by default. This will enable offline builds and allow a manual Realm installation and cache preload after approval and acceptance by development and security teams.

### Alternatives

I'm not sure there is one. Unless someone can suggest a work-around I cannot use Realm in projects for my current employer. 

### How important is this improvement for you?

Dealbreaker

### Feature would mainly be used with

Local Database only

**Comment by nirinchev** [comment]
You can run `dart run realm_dart install -t android|ios|linux|macos|windows` - it will print out some information, including where the binary needs to be downloaded to. If you manually copy the binary to the target location prior to building your flutter app, Realm will not attempt to download it.

There's no way to avoid downloading the binary assets at this point as dart doesn't have support for native assets yet. Once they ship that, we'll be able to include all the native binaries in the package.

**Comment by nielsenko** [comment]
@proswdev Realm only require a download on the first build per platform. The native binaries are cached after that. True, if you start from scratch on every build on a CI/CD pipeline, then every build is the first build, but the same argument can be said against `dart pub get` - it will also require internet access.
