### ISSUE TITLE
Sync support for Nested maps.  

### ISSUE THREAD

**Issue by Shreedhar73** [realm/realm-dart#1709]
### Problem

I am using realm with device sync and have been waiting for MAP support for long. 
Currently I am able to sync simple (single level maps) . 

For Example : 
  ```

@RealmModel()
class _TodoModel {
  @PrimaryKey()
  @MapTo('_id')
  late ObjectId id;
  late String title;
  late String description;
  late String userId;
  late List<$Notes> notes;
  late Map<String, RealmValue> metaData;
}

 final metaData = RealmMap(
    {  
         'title' :  RealmValue.from("title string"),
         'description' : RealmValue.from("description)'
    };
);

  final newTodo =
      TodoModel(
        ObjectId(), 
        todo.title, 
        todo.description,
        todo.userId,
          metaData: metaData
  );

  RealmConfig.instance.realm.write(() {
    RealmConfig.instance.realm.add(newTodo);
  });
```

I am able to write this and the sync is working properly . 

I am not able to figure out how to handle the nexted maps,  like 

```
  final mapData = {
  "title" : 'xyz',
  "age",: 12,
  "dob" : DateTime.now(),
  'metaData' : {
     "a": 'a',
     "b" : 'b'
   }
}
```

The write operation is successful on local realm initially, but is removed with a log on atlas 
`received a collection value on primitive-only mixed field`. 

Am I doing something wrong or is it the expected behavior ??

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Atlas Device Sync

**Comment by Shreedhar73** [comment]
https://github.com/realm/realm-dart/issues/685

**Comment by nielsenko** [comment]
See @nirinchev's comment https://github.com/realm/realm-dart/issues/685#issuecomment-2012861972

Or create a new app on MongoDB Atlas. _Collections in mixed_ (as we historically have called this feature internally) is only supported for App Services Apps created after May 5 2024 using Flexible sync

**Comment by Shreedhar73** [comment]
> See @nirinchev's comment [#685 (comment)](https://github.com/realm/realm-dart/issues/685#issuecomment-2012861972)
> 
> Or create a new app on MongoDB Atlas. _Collections in mixed_ (as we historically have called this feature internally) is only supported for App Services Apps created after May 5 2024 using Flexible sync

Will it be only supported for apps created after May 5th or are there plans for extending the support for older apps as well ?

**Comment by nirinchev** [comment]
You can enable the feature on older apps by contacting support. One thing to note though is that old versions of your client app won't be able to sync so users will need to update their app to restore functionality.

**Comment by Shreedhar73** [comment]
Ok thanks 
Will do that. 
Closing this for now.

**Comment by Shreedhar73** [comment]
> @Shreedhar73 Just to follow up.
> 
> Even though you _can_ have this feature enabled for an old app, turning it on in production without testing is not something I would recommend. It will require terminating sync and restarting, and will require clients to be updated to a version supporting the newest sync protocol version.
> 
> Instead consider setting up a new App Services App, and have new updated clients contact this instead.

We are still not on open prod .  
I am testing this since last night, and I think the syncing part is working well.

I will reach out if any complications occurs. 
Thanks
