### ISSUE TITLE
FlexibleSync Problem

### ISSUE THREAD

**Issue by tuphampro** [realm/realm-dart#1723]
### What happened?

Realm always loads data from the server when opening the application even though there are no changes. Meanwhile, version 1.9.0 did not have that problem.

![image](https://github.com/realm/realm-dart/assets/19162524/5fd1ed31-6c5f-4a89-a55b-87691949357a)

### Repro steps

      final currentUser = await app.logIn(Credentials.anonymous());
          final config = Configuration.flexibleSync(
            currentUser,
            schemaObjects,
            path: customPath,
          );

      realm = Realm(config);
      realm?.subscriptions.update((mutableSubscriptions) {
        mutableSubscriptions.add(realm!.all<Category>());
      });

      realm?.subscriptions.waitForSynchronization();

### Version

3.0.0

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

Windows 11

**Comment by nirinchev** [comment]
This report is insufficient to determine what the problem or what your question is.
