### ISSUE TITLE
Flutter realm iOS Invalid Binary

### ISSUE THREAD

**Issue by CodeRedDev** [realm/realm-dart#1725]
### What happened?

When distributing a Flutter app that depends on the `realm` package to App Store Connect the distributed build will lead to a notification by Apple:

ITMS-90755: Invalid Binary - The following binaries in your app contains prohibited instructions: Runner.app/Frameworks/App.framework/App. Remove the instructions from the binaries, rebuild and resubmit.

### Repro steps

1. Create minimal Flutter app with `realm` package
2. Run `dart run realm install`
3. Run `flutter build ipa --release --no-tree-shake-icons` to build archive
4. Distribute archive through xcode or CD pipeline

### Version

3.0.0

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

iOS

**Comment by nirinchev** [comment]
This binary is not produced by Realm - what makes you think this is caused by the Realm SDK?

**Comment by CodeRedDev** [comment]
When I remove Realm from the project I'm not getting the Invalid Binary notification.

A guess I can't confirm yet is that the dynamic library in `realm-3.0.0/macos` is causing this.

**Comment by nirinchev** [comment]
I'm not sure why would the macOS binary be included in the iOS build. Do you see the dylib in the final packaged version of your app?

**Comment by CodeRedDev** [comment]
I have to say the aforementioned guess was probably wrong. I checked the archive and the application in it and could not find a trace of the dynamic library.


To confirm my claim on Realm being the cause of the build not being accepted by App Store Connect I have cleaned  and rebuild the app again.

A build without the `realm` package was accepted by App Store Connect.

The second build with `realm` installed, a standard configuration applied and without installing test binaries (`dart run realm install`) was rejected with the Invalid Binary reason.

To get more to the actual project configuration I want to add the info that I'm using flavors, so the real command for building is:
`flutter build ipa -t lib/main_dev.dart --flavor dev --release --no-tree-shake-icons`

Flavors were configured as it is described in the [Flutter documentation](https://docs.flutter.dev/deployment/flavors).

Also I'm using Flutter 3.22.1

Here a screenshot from the resulting archives `Runner.app/Frameworks/` realm folders if it is any help.
![Bildschirmfoto 2024-06-20 um 11 13 57](https://github.com/realm/realm-dart/assets/27018054/0939a904-4739-4a2f-8f5e-ca5f817bf33b)

Is there any way I can check these for corruption or the like?

**Comment by nirinchev** [comment]
This looks reasonable to me - is there any information what the prohibited instructions are?

**Comment by CodeRedDev** [comment]
Unfortunately Apple did not send any more information with the mail about Invalid Binary.

Interestingly my coworker does not have problems to build a archive thats accepted by Apple.

We identified some differences like Cocoapods versions that unfortunately did not fix the problem.

One we found though was the checksum in `Podfile.lock` being different:

His working: `7d6eb317b0f9509a2aef00f38452bb8dcd8e0c35`

**Comment by CodeRedDev** [comment]
It's a little bit embarrasing but we were able to fix it by using my coworkers branch. After building the checksum was c667. So this maybe wasn't the problem too.

On the site of our Dart code the Realm specific changes were:

```dart
  var realm = Realm(
    Configuration.local([LocalUserProfile.schema]),
  );
```

to

```dart
    var config = Configuration.local(
      [LocalUserProfile.schema],
      encryptionKey: service.getRealmKey(),
    );
    
    var realm = Realm(config: config);
```

which I doubt to make such a big change because the app was running fine on emulators and real devices but just didnt get accepted into app store.

At the end I really can't tell what made the difference.

**Comment by nirinchev** [comment]
Hm... my best guess is that something may have gotten corrupted when downloading the Realm binaries for iOS. I'll see if we can add some checksum validation, but in any case, glad to hear that this is working now!
