### ISSUE TITLE
MongoDB Atlas Conditional Schema

### ISSUE THREAD

**Issue by ghost** [realm/realm-dart#1743]
### What happened?

May we ask if MongoDB Atlas Conditional Schema https://www.mongodb.com/community/forums/t/validate-schema-with-conditions/121759/2 is supported? We want to basically have a model with 2 x sets of DB schema which 'are identical' except for the 'required fields' in MongoDB Atlas (i.e. the same field may be required and not required in the MongoDB Atlas schema). In this instance we assume Realm Device sync will support this as long as we make the field in Realm as 'not required'.

example MongoDB Atlas schema validation:

```
let schemaType0Or2 =  {
      required: [ "type"  ], //  some fields are required
      properties: {
            type: {
                bsonType: "string",
            },
            baseClxName: {
                bsonType: "string",
            },
      }
}

let schemaType1 =  {
      required: [ "type", "baseClxName"  ], //  all fields are required
      properties: {
            type: {
                bsonType: "string",
            },
            baseClxName: {
                bsonType: "string",
            },
      }
}

db.createCollection( 
    "testCollection", 
    { validator: 
        { $jsonSchema: 
            { oneOf: [ schemaType0Or2, schemaType1 ] } 
        } 
    } 
)
```

Example desired Flutter Realm Schema:

```
class _TestCollection {

  late String bsonType; // all documents have this field as 'required' in MongoDB Atlas schema validation

  String baseClxName; // some documents are 'required', others 'not required' in MongoDB Atlas schema validation

}
```

### Repro steps

na

### Version

na

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### What type of application is this?

Flutter Application

### Client OS and version

na

### Code snippets

na

### Stacktrace of the exception/crash you're getting

```shell
na
```

### Relevant log output

```shell
na
```

**Comment by nirinchev** [comment]
No, conditional schema is not supported on the server.

**Comment by nirinchev** [comment]
It's a combination of limitations - `oneOf` is not supported as a json schema expression by the server. Then, the type of json schema conditions is not expressible by the dart type system. Finally, the Realm Core database doesn't have conditional schema support either.

**Comment by nirinchev** [comment]
I see - yes, that should work. If a write comes in from Realm/Device Sync that seems to pass the Device Sync schema validation, but fails the Atlas schema validation, a compensating write will be synthesized that reverts it on the client. E.g. if you have a rule where `baseClxName` is optional only if `type` is `Foo` and you insert a `Bar` without `baseClxName`, you'd see that change reverted by the server.
