### ISSUE TITLE
No change notification about a child RealmObject change.

### ISSUE THREAD

**Issue by serhii-k** [realm/realm-dart#1754]
### What happened?

I've encountered this bug with a device synced realm but replicated it in a simple local-only example.

Let's say our schema contains three RealmModels:
- **B**, which has an integer `value`
- **A**, which holds an instance of **B** `b`
- **Folder**, which contains a **List&lt;A&gt;** `list`

In our realm, we have one instance of each:
- We've added an instance of A (with its B instance).
- And we've put this A instance into the list inside a Folder instance.

Also, we are listening to the following changes:
- folder.changes
- folder.list.changes
- a.changes

Now, when we modify the `value` inside `a.b`:
- only folder.list.changes is triggered 😞
- but **NOT** a.changes

Please see the full example to understand the problem more clearly.

## 1. schemas.dart
```
import 'package:realm/realm.dart';

part 'schemas.realm.dart';

@RealmModel()
class _Folder {
  @PrimaryKey()
  @MapTo('_id')
  late ObjectId id;

  late List<_A> list;
}

@RealmModel()
class _A {
  @PrimaryKey()
  @MapTo('_id')
  late ObjectId id;

  late _B? b;
}

@RealmModel()
class _B {
  @PrimaryKey()
  @MapTo('_id')
  late ObjectId id;

  late int value;
}
```

## 2. main.dart
```
// ignore_for_file: avoid_print

import 'package:buggy/schemas.dart';
import 'package:flutter/material.dart';
import 'package:realm/realm.dart';

Future<void> main() async {
  final config = Configuration.local([
    A.schema,
    B.schema,
    Folder.schema,
  ]);
  Realm.deleteRealm(config.path); // Just to clear all data
  final realm = Realm(config);

  realm.write(() {
    final a = realm.add(A(
      ObjectId.fromValues(0, 0, 0),
      b: B(ObjectId.fromValues(0, 0, 1), 0),
    ));
    realm.add(Folder(ObjectId.fromValues(0, 0, 2), list: [a]));
  });

  // Find the objects.
  final a = realm.find<A>(ObjectId.fromValues(0, 0, 0))!;
  final b = a.b!;
  final folder = realm.find<Folder>(ObjectId.fromValues(0, 0, 2))!;

  // Subscribe to the changes.
  folder.changes.listen((_) => print('Folder changed'));
  folder.list.changes.listen((_) => print('Folder.list changed'));
  a.changes.listen((_) => print('A changed'));

  await Future.delayed(const Duration(milliseconds: 1000));
  print('* b.value = 1');
  realm.write(() => b.value = 1);

  await Future.delayed(const Duration(milliseconds: 1000));
  print('* b.value = 2');
  realm.write(() => b.value = 2);

  await Future.delayed(const Duration(milliseconds: 1000));
  print('* Done.');
  print('---------');
  print('Problem');
  print('??? Where is "A changed" after its b was modified ???');
  print('??? If the Folder.list was triggered, why A was not ???');

  realm.close();

  runApp(const MaterialApp(home: Scaffold()));
}
```

## The output

```
I/flutter (26316): Folder changed
I/flutter (26316): Folder.list changed
I/flutter (26316): A changed
I/flutter (26316): * b.value = 1
I/flutter (26316): Folder.list changed
I/flutter (26316): * b.value = 2
I/flutter (26316): Folder.list changed
I/flutter (26316): * Done.
I/flutter (26316): ---------
I/flutter (26316): Problem
I/flutter (26316): ??? Where is "A changed" after its b was modified ???
I/flutter (26316): ??? If the Folder.list was triggered, why A was not ???
```

### Version

3.3.0

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

Android 14 (SDK 34)

**Comment by serhii-k** [comment]
It turns out that it was implemented this way to optimize performance.

And there is another method, changesFor([keyPaths]), which takes into account how deep you want to observe changes. So it's possible to specify the following keyPaths:
- `b.value` to trigger changes if `b.value` was changed
- `b.*` if any property of `b` was changed
- `*.*` if any property of any linked object was changed
- etc.

```
a.changesFor(['*', 'b.value']).listen((changes) => print('B changed ${changes.properties}'));
```

**Comment by serhii-k** [comment]
So, the only request about this ticket is to please mention the correct way to register a RealmObject Change Listener here:

[https://www.mongodb.com/docs/atlas/device-sdks/sdk/flutter/realm-database/react-to-changes/#register-a-realmobject-change-listener](https://www.mongodb.com/docs/atlas/device-sdks/sdk/flutter/realm-database/react-to-changes/#register-a-realmobject-change-listener)

There is no any bug here. Realm is soooooo COOL! 🤩

**Comment by nielsenko** [comment]
@serhii-k Just back from vacation. Happy you worked it out 👍
