### ISSUE TITLE
Running testing with realm work on local machine but not in CI/CD

### ISSUE THREAD

**Issue by richard457** [realm/realm-dart#1771]
### What happened?

Run unit/integration testing locally with realm but in CI/CD github action does not work

### Repro steps

https://github.com/realm/realm-dart/issues/1619

### Version

3.24.0

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

Windows

### Code snippets

https://github.com/yegobox/flipper/actions/runs/10332144404/job/28603071678

### Stacktrace of the exception/crash you're getting

```shell
- "C:\Users\runneradmin\AppData\Local\Pub\Cache\hosted\pub.dev\realm-3.3.0\windows\binary\windows\realm_dart.dll"
```

**Comment by nielsenko** [comment]
@richard457 Add a `dart run realm install` before the `flutter test ..` call. 

Unlike `flutter drive ..` or `flutter test integration_test/..`,  `flutter test` doesn't actually create and run an app bundle. In particular there is no way (currently - we are eagerly awaiting the _native assets_ feature) to hook into the build process and ensure that the binaries are downloaded during `flutter test`.

The reason you didn't have to do this on your developer machine is (most likely) that you have actually tried running an actual flutter app dependent on `realm 3.3.0` (probably the app you are developing) in which case we can do the download during build. For iOS and macOS this happens via cocoa pods, for Android via gradle, and for Linux and WIndows via cmake.

On CI you are starting setup more or less from scratch on each run, so the pub cache won't be primed, and something needs to trigger the download explicitly.

Anyway, you are not the first to have trouble with `flutter test` and packages with native dependencies, such as `realm`. I hope this helps.
