### ISSUE TITLE
I/flutter ( 7604): Failed to initialize SharedPreferences: PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.shared_preferences_android.SharedPreferencesApi.getAll"., null, null)

### ISSUE THREAD

**Issue by awodefeng** [realm/realm-dart#1787]
realm: ^1.9.0版本以上和shared_preferences冲突，无法初始化shared_preferences，报错I/flutter ( 7604): Failed to initialize SharedPreferences: PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.shared_preferences_android.SharedPreferencesApi.getAll"., null, null)
请给出解决方案，谢谢！

**Comment by nirinchev** [comment]
It's not obvious why this would be a realm issue. If you can update your bug report in English we'll be able to take a look.

**Comment by cliff-rono** [comment]
`flutter clean`
Run your app again, worked for me.
