### ISSUE TITLE
Realm error : Realm SDK package version does not match the native library version (3.4.1 != 3.3.0).

### ISSUE THREAD

**Issue by Comanx** [realm/realm-dart#1788]
### What happened?

My `pubspec.yaml` is set to realm: 3.3.0, but the issue description mentions version 3.4.1. I thought it might have been accidentally upgraded to 3.4.1, but the pubspec.yaml modification history does not show this. When I updated pubspec.yaml to realm: ^3.4.1 and compiled the APK, print:
```
Directory: 'D:\Cache\Pub\hosted\pub.flutter-io.cn\realm-3.4.1\android\src\main\cpp\lib'
Downloading Realm binaries for 3.4.1 to C:\Users\lica\AppData\Local\Temp\realm-binary-91226881\android.tar.gz
Extracting Realm binaries to D:\Cache\Pub\hosted\pub.flutter-io.cn\realm-3.4.1\android\src\main\cpp\lib
extracting x86_64/librealm_dart.so
extracting arm64-v8a/librealm_dart.so
extracting armeabi-v7a/librealm_dart.so

Archive C:\Users\lica\AppData\Local\Temp\realm-binary-91226881\android.tar.gz extracted to D:\Cache\Pub\hosted\pub.flutter-io.cn\realm-3.4.1\android\src\main\cpp\lib
Realm install command finished.
```
it seems to indicate that this is the first time downloading the so. I recall this happening before, and at that time, I thought it was an accidental version change. I’m frustrated as this prevents my clients from accessing data, and I am even considering using another  database.

Of course I can't be sure that this is a realm issue

### Repro steps

I dont Know

### Version

3.22.3->3.24.1->3.22.3

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

Android

**Comment by nirinchev** [comment]
It appears you updated your dependency but didn't install the native binaries. How that happened is not clear to me, but the first version is the version of the dart package while the latter is the version of the native binary.

**Comment by Comanx** [comment]
I cannot reproduce the issue，I will update to the latest version to avoid this issue.
