### ISSUE TITLE
Add JSON encoding support for ObjectId 

### ISSUE THREAD

**Issue by ganwumeng** [realm/realm-dart#1791]
### Problem

While trying to use 
```dart
List<ObjectId> objectIdList = [...];
jsonEncode(objectIdList);
```
, throw an exception:
> Converting object to an encodable object failed: Instance of 'ObjectId'

### Solution

Add tojson and fromjson function

### How important is this improvement for you?

Fairly niche but nice to have anyway

### Feature would mainly be used with

Local Database only

**Comment by nirinchev** [comment]
`ObjectId` comes from https://pub.dev/packages/objectid and is not a type we maintain ourselves. Might be worth asking in https://github.com/gonuit/dart_objectid or submitting a PR to the library.
