### ISSUE TITLE
Atlas Services

### ISSUE THREAD

**Issue by Rob-Biemans** [realm/realm-dart#1794]
### What happened?

Because of sunsetting the Device SDKs for Atlas, does this mean we can no longer use Atlas Services like Functions/Authentication/Atlas Search all together? Why not make the SDK still work with Atlas Services and make Query of databases/collections still possible?

### Repro steps

Because of sunsetting the Device SDKs for Atlas, does this mean we can no longer use Atlas Services like Functions/Authentication/Atlas Search all together? Why not make the SDK still work with Atlas Services and make Query of databases/collections still possible?

### Version

Latest

### What Atlas Services are you using?

Both Atlas Device Sync and Atlas App Services

### What type of application is this?

Flutter Application

### Client OS and version

Microsoft

**Comment by nirinchev** [comment]
That is correct. The API to query the database go through App Services functionality that is also being sunset, so it wouldn't improve the situation. If you need to read/write data to your Atlas data directly, you probably need a MongoDB driver. Currently, we don't have one for dart, but feel free to upvote the official [Official Dart Driver](https://feedback.mongodb.com/forums/924286-drivers/suggestions/39953854-official-dart-driver) feedback item and watch it for updates.

**Comment by Shreedhar73** [comment]
This has caught us off guard, literally invested  more than a year, developing a product, and  then this . Not even a proper explanation . 
This will be a lesson to never work with mongo ever again.

**Comment by scris** [comment]
> This has caught us off guard, literally invested more than a year, developing a product, and then this . Not even a proper explanation . This will be a lesson to never work with mongo ever again.

Yes, they have the right to sunset something, but they'd better provide a proper explanation. SaaS tools provided by some middle-sized companies like MongoDB should be considered suspect and should not be used :(
