### ISSUE TITLE
有时候会出现这个问题,请看一下

### ISSUE THREAD

**Issue by YangSmallline** [realm/realm-dart#1808]
### What happened?

Realm.SDK - ERROR: CompensatingWriteError: Client attempted a write that is not allowed; it has been reverted Logs: https://services.cloud.mongodb.com/groups/6660151e6daee1483cc4eefd/apps/6683a9dfc9361a1f67a2a97d/logs?co_id=673466a4b0dc4d592592bfcc. [CompensatingWriteInfo: objectType: 'Tree' reason: 'write to ObjectID("67346793a09ce9fbca439bbf") in table "Tree" not allowed; object is outside of the current query view' primaryKey: 'RealmValue(67346793a09ce9fbca439bbf)']

### Repro steps

List<SchemaObject> _getSchemas() {
    return [
      // 在这里添加所有需要同步的Schema
      Project.schema,
      ProjectList.schema,
      Files.schema,
      MapInfo.schema,
      AuxSupport.schema,
      Classes.schema,
      UseClasses.schema,
      Survey.schema,
      Tree.schema,
      TreeTypeDetailEntityMap.schema,
      Design.schema,
      DesignTreeType.schema,
      Models.schema,
      ModelTreeType.schema,
      Charge.schema,
      Fertilizer.schema,
      FosterCareData.schema,
      AuxData.schema,
      AuxDataItem.schema,
      ForestCertificate.schema,
      NoUploadFile.schema
    ];
  }
  
schema已经添加,有时候可以正确添加，有时候添加不了,就报错

Realm.SDK - ERROR: CompensatingWriteError: Client attempted a write that is not allowed; it has been reverted Logs: https://services.cloud.mongodb.com/groups/6660151e6daee1483cc4eefd/apps/6683a9dfc9361a1f67a2a97d/logs?co_id=673466a4b0dc4d592592bfcc. [CompensatingWriteInfo: objectType: 'Tree' reason: 'write to ObjectID("67346793a09ce9fbca439bbf") in table "Tree" not allowed; object is outside of the current query view' primaryKey: 'RealmValue(67346793a09ce9fbca439bbf)']

### Version

3.4.1

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Flutter Application

### Client OS and version

Windows build Android APk

### Code snippets

List<SchemaObject> _getSchemas() {
    return [
      // 在这里添加所有需要同步的Schema
      Project.schema,
      ProjectList.schema,
      Files.schema,
      MapInfo.schema,
      AuxSupport.schema,
      Classes.schema,
      UseClasses.schema,
      Survey.schema,
      Tree.schema,
      TreeTypeDetailEntityMap.schema,
      Design.schema,
      DesignTreeType.schema,
      Models.schema,
      ModelTreeType.schema,
      Charge.schema,
      Fertilizer.schema,
      FosterCareData.schema,
      AuxData.schema,
      AuxDataItem.schema,
      ForestCertificate.schema,
      NoUploadFile.schema
    ];
  }

      var projId = homeController.infoEntity.id;
      var surveyId = surveyEntities.firstWhere((e) => e.class_id == polygonsMain[currentSubIndex].class_id).id;
      var detailList = RealmService.to.query<Tree>(customQuery: 'projectId == \$0 AND type == \$1 AND surveyId == \$2 AND index == \$3 ', args: [projId, type, surveyId, index]).toList();
      var typeDetail = Tree(ObjectId(), projId, CosService.userId, surveyId);
      typeDetail.id= ObjectId();
      typeDetail.index = index;
      typeDetail.type = type;
      typeDetail.treeName = "";
      typeDetail.treeAge = "";
      typeDetail.treeHigh = "";
      typeDetail.treeDiameter = "";
      typeDetail.remark = "";

      if (isOnlyAddNew) {
        RealmService.to.add<Tree>(typeDetail);
      } else {
        if (detailList.isEmpty) {
          print(typeDetail.id);
          typeDetail.addToRealm();
        }
      }
    } on Exception catch (e) {
      toast("发生错误,请重新登录");
      homeController.logOut();
    }
   
  late Realm _syncRealm;

  Future<void> _setupSyncRealm() async {
    final config = Configuration.flexibleSync(_app.currentUser!, _getSchemas());
    _syncRealm = _isCurrentOnline ? await Realm.open(config) : Realm(config);
    print("在线 syncRealm 初始成功");
  }

  void add<T extends RealmObject>(T object) {
    _syncRealm.write(() => _syncRealm.add<T>(object, update: true));
  }

**Comment by nirinchev** [comment]
This error is expected when you write an object that you don't have permissions to or create one outside of the subscriptions for this client. If this is not expected, please file a support ticket so that the team can investigate.

**Comment by YangSmallline** [comment]
我确保订阅了
