### ISSUE TITLE
How long will this project take to stabilize the API

### ISSUE THREAD

**Issue by chentianxin** [realm/realm-dart#247]
How long does it take for this project to stabilize the API, I'd rather use it in the project than sqlite3

**Comment by bmunkholm** [comment]
@chentianxin As we make improvements to the API based on user feedback, the sooner you want to use it and give feedback the better :-). So if you are ok with some breaking changes (that are communicated clearly in release notes), I wouldn't hesitate to start using it. That's also the best way to help shape the product to everyone's liking ;-)
