### ISSUE TITLE
Id not final

### ISSUE THREAD

**Issue by darrinps** [realm/realm-dart#250]
Followed the build instructions and this is being output to the cmd line.

Primary key field is not final

in: package:flutter_realm/_Item.dart:6:12
  ╷
3 │ @RealmModel()
4 │ class _Item {
  │       ━━━━━ in realm model for 'Item'
5 │   @PrimaryKey()
6 │   late int id;
  │            ^^ is not final
  ╵
Add a final keyword to the definition of 'id', or remove the @PrimaryKey annotation.

[SEVERE] Failed after 6.9s

Note that _Item.dart looks like this:

import 'package:realm/realm.dart';

@RealmModel()
class _Item {
  @PrimaryKey()
  late int id;

  late String name;

  int price = 42;
}

**Comment by blagoev** [comment]
@darrinps This message shows that you need to declare your primary key a final field. We will be removing this requirement in the next versions, but now it is needed. So just change your model to 
```dart
@RealmModel()
class _Item {
@PrimaryKey()
late final int id;
```
