### ISSUE TITLE
When run the Flutter project:    Invalid execution position value `before_headers` in shell script `Download Realm Flutter iOS Binaries`

### ISSUE THREAD

**Issue by IsuruCTS** [realm/realm-dart#251]
When I run the Flutter project I got this issue, do you have any idea about this?

`Launching lib[/main.dart]() on iPod touch (7th generation) in debug mode...
lib/main.dart:1
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Finding Podfile changes
      A realm
      - Flutter
      - connectivity
      - flutter_secure_storage
      - path_provider_ios
      - shared_preferences_ios
    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `connectivity` from `.symlinks[/plugins/connectivity/ios]()`
    -> Fetching podspec for `flutter_secure_storage` from `.symlinks[/plugins/flutter_secure_storage/ios]()`
    -> Fetching podspec for `path_provider_ios` from `.symlinks[/plugins/path_provider_ios/ios]()`
    -> Fetching podspec for `realm` from `.symlinks[/plugins/realm/ios]()`
    [!] The `realm` pod failed to validate due to 1 error:
        - WARN  | license: Missing license type.
        - ERROR | [iOS] script_phases: Invalid execution position value `before_headers` in shell script `Download Realm Flutter iOS Binaries`. Available options are `before_compile, after_compile, any`.
        - WARN  | [iOS] keys: Missing primary key for `source` attribute. The acceptable ones are: `git, hg, http, svn`.
    [/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/external_sources/abstract_external_source.rb:194]():in `validate_podspec'
    [/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/external_sources/abstract_external_source.rb:178]():in `store_podspec'
    [/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/external_sources/path_source.rb:17]():in `block in fetch'
    [/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/user_interface.rb:64]():in `section'
    [/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/external_sources/path_source.rb:11]():in `fetch'
    [/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer/analyzer.rb:989]():in `fetch_external_source'
    [/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer/analyzer.rb:968]():in `block (2 levels) in fetch_external_sources'
    [/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer/analyzer.rb:967]():in `each'
    [/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer/analyzer.rb:967]():in `block in fetch_external_sources'
    [/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/user_interface.rb:64]():in `section'
    [/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer/analyzer.rb:966]():in `fetch_external_sources'
    [/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer/analyzer.rb:117]():in `analyze'
    [/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:414]():in `analyze'
    [/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:239]():in `block in resolve_dependencies'
    [/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/user_interface.rb:64]():in `section'
    [/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:238]():in `resolve_dependencies'
    [/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:160]():in `install!'
    [/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/command/install.rb:52]():in `run'
    [/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334]():in `run'
    [/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/command.rb:52]():in `run'
    [/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/bin/pod:55]():in `<top (required)>'
    [/usr/local/bin/pod:23]():in `load'
    [/usr/local/bin/pod:23]():in `<main>'
Error running pod install
Error launching application on iPod touch (7th generation).
Exited (sigterm)`

**Comment by blagoev** [comment]
@IsuruCTS What is your cocoapods version. Seems you are using a very old one.  I suggest you update your cocoapods.

**Comment by IsuruCTS** [comment]
After updating cocoapods version ( pod --version: 1.11.2), now I am getting this error:

`...
[/Users/isuru/Home/Project/Testing/Testing-Mobile/Testing-Mobile/ios/.symlinks/plugins/realm/ios/src/dart-include/dart_api.h:3280:11](): warning: parameter 'buffer_size' not found in the function declaration [-Wdocumentation]
     * \param buffer_size Length of the passed in buffer.
              ^~~~~~~~~~~
    [/Users/isuru/Home/Project/Testing/Testing-Mobile/Testing-Mobile/ios/.symlinks/plugins/realm/ios/src/dart-include/dart_api.h:3447:11](): warning: parameter 'buffer' not found in the function declaration [-Wdocumentation]
     * \param buffer A buffer which contains a kernel binary (see
              ^~~~~~
    [/Users/isuru/Home/Project/Testing/Testing-Mobile/Testing-Mobile/ios/.symlinks/plugins/realm/ios/src/dart-include/dart_api.h:3449:11](): warning: parameter 'buffer_size' not found in the function declaration [-Wdocumentation]
     * \param buffer_size Length of the passed in buffer.
              ^~~~~~~~~~~
    [/Users/isuru/Home/Project/Testing/Testing-Mobile/Testing-Mobile/ios/.symlinks/plugins/realm/ios/src/dart-include/dart_api.h:3638:23](): warning: empty paragraph passed to '\param' command [-Wdocumentation]
     * \param snapshot_data
       ~~~~~~~~~~~~~~~~~~~^
    [/Users/isuru/Home/Project/Testing/Testing-Mobile/Testing-Mobile/ios/.symlinks/plugins/realm/ios/src/dart-include/dart_api.h:3644:23](): warning: empty paragraph passed to '\param' command [-Wdocumentation]
     * \param kernel_buffer
       ~~~~~~~~~~~~~~~~~~~^
    50 warnings generated.
    104 warnings generated.
: Error: Member not found: '_'.
lib/testRealm/task.g.dart:40
        RealmObject.registerFactory(Task._);
                                         ^
    Failed to package [/Users/isuru/Home/Project/Testing/Testing-Mobile/Testing-Mobile.]()
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
    Result bundle written to path:
    	[/var/folders/d_/zmwt93qx48g5qjkzszq___sh0000gp/T/flutter_tools.JYnj1W/flutter_ios_build_temp_dirYfWlaP/temporary_xcresult_bundle]()
Could not build the application for the simulator.
Error launching application on iPod touch (7th generation).
Exited (sigterm)`

**Comment by IsuruCTS** [comment]
@blagoev 
I fixed this issue after updating pubspec.yaml to set the minimum SDK constraint to 2.15 or higher, and running 'pub get'.
