### ISSUE TITLE
Can we use native platform SDKs (iOS and Android SDKs) to connect to MongoDB Realm application services and use Realm Sync. features

### ISSUE THREAD

**Issue by IsuruCTS** [realm/realm-dart#252]
While Flutter Realm SDK is used for CRUD operation, can we use native platform SDKs (iOS and Android SDKs) to connect to MongoDB Realm application services and use Realm Sync. ?

**Comment by blagoev** [comment]
Hi, we don't recommend doing that and it is something we are not supporting.
