### ISSUE TITLE
No "catalog.g.dart" file is generated

### ISSUE THREAD

**Issue by darrinps** [realm/realm-dart#255]
Followed the instructions and did a realm generate:

_C:\GitProjects\flutter_realm>flutter pub run realm generate
[INFO] Generating build script...
[INFO] Generating build script completed, took 260ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 38ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 373ms

[INFO] Running build...
[INFO] 1.7s elapsed, 0/1 actions completed.
[INFO] realm:realm_generator on lib/_Item.dart:[generate (0)] completed, took 18ms
[WARNING] source_gen:combining_builder on lib/_Item.dart:
_Item.g.dart must be included as a part directive in the input library with:
    part '_Item.g.dart';
[INFO] Running build completed, took 1.8s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 19ms

[INFO] Succeeded after 1.8s with 1 outputs (3 actions)_

Looked to find the catalog.g.dart file mentioned in the directions but no such file was generated. Only the following files exists:

  _item.dart
 catalog.dart
 main.dart

**Comment by blagoev** [comment]
@darrinps This is the error
```
_Item.g.dart must be included as a part directive in the input library with:
part '_Item.g.dart';
```


you need to declare a part file in your `_Item.dart`. 

First I suggest you rename your file without the underscore. So lets make this `item.dart`
Then in your `item.dart` file you declare a `part file` after the all dart imports

```dart
import .....
import....

part 'item.g.dart'; //<----- part file declaration

@RealmModel()
class _Item {   // <-- realm model should be named with underscore, not the dart file
late int x,
late in y,
}
```

Cheers

**Comment by darrinps** [comment]
I was trying to follow the directions verbatim I found on the main page. I'm thinking maybe they could be rewritten with what you mentioned?

Anyway, following your instructions (and ignoring some of the ones from the main page) worked. Thanks,
