### ISSUE TITLE
Deleting items in a Realm not reliable 

### ISSUE THREAD

**Issue by darrinps** [realm/realm-dart#268]
I have a test run where a realm is read then each item is deleted (as the Realm.deleteRealm() does not seem to be supported yet) then the same primary keys are used again to create new entries.

Here is the code:

`
    void _conductTest() {
    var config = Configuration([Item.schema]);

    Realm realm = Realm(config);

    var items = realm.all<Item>();
    var index = 0;
    final log = Logger('RealmLogger');

    if(items.isNotEmpty) {
      log.info("Total objects to delete from realm: " + items.length.toString());

      for(index = 0; index < items.length; index++) {
        log.info("Deleting realm item at index: " + index.toString());
        realm.write(() { realm.delete(items[index]);});
      }

      realm.close();
      realm = Realm(config);
    }

    var timeStart = DateTime.now();

    log.info("Time of start: " + timeStart.toString());

    for(index = 0; index < 1000; index++) {
      realm.write(() {
        var myItem = Item(index, 'Item_' + index.toString(), index * 10);

        try {
          realm.add(myItem);
        }
        catch(e) {
          log.warning("Realm error writing for index: " + index.toString());
        }
      });
    }

    // Get all objects of type...read them back
    items = realm.all<Item>();

    var timeEnd = DateTime.now();
    var elapsedTime = timeEnd.difference(timeStart);

    log.info("Time at finish: " + timeEnd.toString());
    log.info("Elapsed time: " + elapsedTime.toString());

    realm.close();
  }
`

Looking at the output you see this:

I/flutter (29132): INFO: 2022-02-21 14:17:03.135936: Total objects to delete from realm: 1000
I/flutter (29132): INFO: 2022-02-21 14:17:03.139225: Deleting realm item at index: 0
I/flutter (29132): INFO: 2022-02-21 14:17:03.145426: Deleting realm item at index: 1
I/flutter (29132): INFO: 2022-02-21 14:17:03.147498: Deleting realm item at index: 2
I/flutter (29132): INFO: 2022-02-21 14:17:03.148857: Deleting realm item at index: 3
I/flutter (29132): INFO: 2022-02-21 14:17:03.150243: Deleting realm item at index: 4
I/flutter (29132): INFO: 2022-02-21 14:17:03.151472: Deleting realm item at index: 5
I/flutter (29132): INFO: 2022-02-21 14:17:03.153252: Deleting realm item at index: 6
I/flutter (29132): INFO: 2022-02-21 14:17:03.154531: Deleting realm item at index: 7
...
I/flutter (29132): INFO: 2022-02-21 14:17:03.748052: Deleting realm item at index: 496
I/flutter (29132): INFO: 2022-02-21 14:17:03.749219: Deleting realm item at index: 497
I/flutter (29132): INFO: 2022-02-21 14:17:03.750363: Deleting realm item at index: 498
I/flutter (29132): INFO: 2022-02-21 14:17:03.752114: Deleting realm item at index: 499

Note that is stops at 500 total and does not go to the full 1000.

The logging continues:
I/flutter (29132): INFO: 2022-02-21 14:17:03.757482: Time of start: 2022-02-21 14:17:03.757429
I/flutter (29132): WARNING: 2022-02-21 14:17:03.764375: Realm error writing for index: 0
I/flutter (29132): WARNING: 2022-02-21 14:17:03.773875: Realm error writing for index: 2
I/flutter (29132): WARNING: 2022-02-21 14:17:03.775851: Realm error writing for index: 3
I/flutter (29132): WARNING: 2022-02-21 14:17:03.778211: Realm error writing for index: 5
I/flutter (29132): WARNING: 2022-02-21 14:17:03.781980: Realm error writing for index: 8
I/flutter (29132): WARNING: 2022-02-21 14:17:03.784257: Realm error writing for index: 10
I/flutter (29132): WARNING: 2022-02-21 14:17:03.786111: Realm error writing for index: 12
I/flutter (29132): WARNING: 2022-02-21 14:17:03.787514: Realm error writing for index: 14
I/flutter (29132): WARNING: 2022-02-21 14:17:03.790160: Realm error writing for index: 16
I/flutter (29132): WARNING: 2022-02-21 14:17:03.792267: Realm error writing for index: 18

Note that approximately every other item in the realm didn't get deleted.

**Comment by nielsenko** [comment]
You are deleting every second element. Note that `items` is a live query. When you delete an element you shift all the indexes.

**Comment by nielsenko** [comment]
If all you want to do is delete `Item`s in the realm, then do `realm.write(() => realm.deleteMany(realm.all<Item>())`

**Comment by darrinps** [comment]
Thanks. I'll try that and close this.

**Comment by nielsenko** [comment]
Good luck! Thrilled to see you try it out.
