### ISSUE TITLE
.delete<T>(.find<T>(X)) no longer work since .delete<T>() do not accept nullable argument

### ISSUE THREAD

**Issue by calvintam236** [realm/realm-dart#293]
Since alpha has changed `.delete<T>()` to not allowing nullable argument, the nested `.delete<T>(.find<T>(X))` can no longer be single line.

Can you have a better way to handle this action? I can see that is a pretty common use case.
For now, please allow nullable argument in `.delete<T>()` until there is one.

**Comment by nielsenko** [comment]
Hi Calvin

Appreciate your interest in our new SDK.

You can do `realm.delete(realm.find<T>(key)!)` if you know the object with `key` exists. If you don't, then do
```
final toDie = realm.find<T>(key);
if (toDie != null) {
  realm.delete(toDie);
}
```
Wrap that up as a couple of extension methods, and you have your one-liner:
```
extension RealmEx on Realm {
  void deleteNullable<T extends RealmObject>(T? toDie) {
    if (toDie != null) {
      delete(toDie);
    }
  }

  // extra convenience
  void deleteByKey<T extends RealmObject>(Object key) {
    deleteNullable(find<T>(key));
  } 
}
```
