### ISSUE TITLE
What about User authentication?

### ISSUE THREAD

**Issue by LeonManolo** [realm/realm-dart#315]
Currently im trying to implement Google OAuth together with Mongodb realm. Is there any plans to support user authentication for the flutter sdk? The react native library has it already integrated I saw. And is there a recommended way in the meantime on who to ingredate user authentication with mongodb realm for flutter (maybe without implementing both native sdk's on ios and android)?

**Comment by blagoev** [comment]
@LeonManolo There are plans to support MongoDB Realm APIs. Unfortunately the current Realm Flutter SDK implementation does not support that but I must assure you we are working on it.

**Comment by blagoev** [comment]
In general we can not comment on possible release dates, but we are actively working on it.
