### ISSUE TITLE
Consider using path_provider or similar for the defaultPath

### ISSUE THREAD

**Issue by NotAgentBilly** [realm/realm-dart#316]
Perhaps this on the app developer to implement, but the issue I ran into was as follows:

Package my app with https://pub.dev/packages/msix to create an msix file for windows.

The resulting msix installs my app to a directory with admin rights e.g. `C:\Program Files\WindowsApps`

The regular defaultPath for realm on windows is the application’s directory (code below), therefore you need to run the app as admin for realm to create a database.

```
static String _initDefaultPath() {
  var path = "default.realm";
  if (Platform.isAndroid || Platform.isIOS) {
    path = _path.join(realmCore.getFilesPath(), path);
  }
  return path;
}
```

My solution was setting defaultPath myself with path_provider

```
import 'package:realm/realm.dart';
import 'package:path/path.dart' as path;
import 'package:path_provider/path_provider.dart';

Configuration.defaultPath = path.join(
      (await getApplicationDocumentsDirectory()).path, 'filename.realm');
```

I can't/haven't tested whether this works for other platforms and I don't have an idea of how this effects other use cases. My goal was simply to resolve my problem specific to windows and msix packaging.

**Comment by blagoev** [comment]
@NotAgentBilly Thanks for the feedback. We will definitely try to improve it based on your suggestion. I have created this issue and linked it to this one so we keep track of it. https://github.com/realm/realm-dart/issues/450
cheers.
