### ISSUE TITLE
Type io.realm.BuildConfig is defined multiple times

### ISSUE THREAD

**Issue by raphaaugustosilva** [realm/realm-dart#475]
Hi!

I have a Flutter project, with native Android code embedded (using the Flutter Platform View).
These native Android codes already have the realm implementation in the native gradle file.
`classpath "io.realm:realm-gradle-plugin:10.10.1"`

When I add the realm in the Flutter side (inside pubspec.yaml), the pub get command works fine and I`m able to code, but, when I try to compile the code, the following error occurs:

`"Type io.realm.BuildConfig is defined multiple times: /Users/raphael.silva/.gradle/caches/transforms-3/b2afad974a5aa7df17b3cbd993e77770/transformed/jetified-realm-android-library-10.10.1-runtime.jar:io/realm/BuildConfig.class, /Users/raphael.silva/Projetos/ao3/POCs/poc_android_in_flutter/build/realm/intermediates/runtime_library_classes_jar/debug/classes.jar:io/realm/BuildConfig.class"
`

How can I get ride this error, keeping the "two realm" (inside Flutter and native) and compile normaly?

**Comment by nirinchev** [comment]
Hi @raphaaugustosilva,

Running multiple SDKs in the same process is not something we test or attempt to support officially. It may work accidentally, but there are a lot of caveats with it, which may cause things to break in weird ways. For this particular error though, it doesn't appear like it's coming from the Realm Flutter SDK as `BuildConfig` is not something that exists here.
