### ISSUE TITLE
Add software license

### ISSUE THREAD

**Issue by cmedamine** [realm/realm-dart#658]

**Comment by nielsenko** [comment]
License is Apache License version 2.0 as stated in the LICENSE file.

**Comment by nielsenko** [comment]
The LICENSE link on [pub.dev](https://pub.dev/packages/realm) points to the [LICENSE](https://pub.dev/packages/realm/license) file. 

Is it that pub.dev doesn't recognise the license that bothers you? It starts with a table-of-content, which may be the reason the pub.dev license parser is thrown off course.

**Comment by cmedamine** [comment]
oh ok, my bad

**Comment by nielsenko** [comment]
I'll keep this open until we figure why the license isn't recognised correctly, and what (if anything) to do about it. 
Thank you for taking an interest in our new SDK. Looking forward to more feedback.
