### ISSUE TITLE
Problem when using @Ignored keyword

### ISSUE THREAD

**Issue by salithashamood1** [realm/realm-dart#659]
![Model](https://user-images.githubusercontent.com/106074690/172590877-8a959c47-a0aa-4c90-a5e3-e58f4e944889.PNG)

I used this model. 

![Model Ignore](https://user-images.githubusercontent.com/106074690/172591728-6beacd4e-0c12-461a-8d0a-ef02b9086ed3.PNG)

But I can't binding value for String type (number) variable using @Ignored keyword.

How to binding data when using @Ignored keyword?

**Comment by salithashamood1** [comment]
Hi @nielsenko,
Thank you for your answer.
Can I know I can add that number field to mobile realm local database?
Thank you.

> Hi Salitha Shamood
> 
> Thank you for taking an interest in our new Flutter / Dart SDK.
> 
> I assume, you are missing the constructor argument to set `number`. We do not generate this currently, so you will need to set the property after construction, something like
> 
> ```dart
> final item = Item(ObjectId(), 'Salitha Shamood', 'item#2')..number = '2';
> ```
> 
> Be aware that this property will not be persisted when adding the item to the realm, and you will have to set it on all `Item`s you read from realm, including whenever traversing a link to an `Item`.

**Comment by nielsenko** [comment]
I'm not sure I understand your question correctly, but if you remove the `@Ignored()` attribute, the `number` field will be stored in the realm, along with the rest of the fields.

**Comment by salithashamood1** [comment]
Yes. I know it. But I want to that number field store in local database only. I didn't want to add that field in mongoDb database. Can I do it?

**Comment by fealebenpae** [comment]
Only synchronizing a subset of the local database is not supported, unfortunately.

**Comment by ianpward** [comment]
You can have two separates realms, one that is synced, and one that is non-synced and stays local. You can store different data in each
