### ISSUE TITLE
[realm_dart] [macOS] Failed to load dynamic library

### ISSUE THREAD

**Issue by hmbenhaim** [realm/realm-dart#664]
Hi,
I get the error below when trying to run realm on macOS with dart 2.17.1
I tried to find where can I get this binaries but no luck.

Invalid argument(s): Failed to load dynamic library '/Users/username/Documents/GitHub/services/realm_project/binary/macos/librealm_dart.dylib': dlopen(/Users/username/Documents/GitHub/services/realm_project/binary/macos/librealm_dart.dylib, 0x0001): tried: '/Users/username/Documents/GitHub/services/realm_project/binary/macos/librealm_dart.dylib' (no such file)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      initRealm (package:realm_dart/src/init.dart:67:39)
#3      new _RealmCore._ (package:realm_dart/src/native/realm_core.dart:65:17)
#4      new _RealmCore (package:realm_dart/src/native/realm_core.dart:70:37)
#5      realmCore (package:realm_dart/src/native/realm_core.dart:47:30)
#6      realmCore (package:realm_dart/src/native/realm_core.dart)
#7      new Realm._ (package:realm_dart/src/realm_class.dart:97:69)
#8      new Realm (package:realm_dart/src/realm_class.dart:95:38)
#9      main (file:///Users/username/Documents/GitHub/services/realm_project/bin/main.dart:25:15)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

**Comment by hmbenhaim** [comment]
No sorry, I installed the library I thought it was enough, it did the trick 👍 thank you

**Comment by hmbenhaim** [comment]
I see, we build flutter apps and our backend is in dart as well.
We use atlas mongo DB and we are thinking of using realm.
Thank you 🙏

**Comment by desistefanova** [comment]
@demux79 ,
Could you share some more details about the steps that you do to run the app? What do you have in pubspec.yml? Did you have some installation errors similar to described in https://github.com/realm/realm-dart/issues/1023?

**Comment by desistefanova** [comment]
Hm,
Everything looks fine.
Do you have such problem with the other environments?
Did you already try to create a new emulator?
