### ISSUE TITLE
Support Map data types.

### ISSUE THREAD

**Issue by salithashamood1** [realm/realm-dart#685]
Can I use Map data type for realm model in flutter?

Like this one,
**`final Map<String, dynamic> properties;`**

**Comment by nielsenko** [comment]
We do not currently support `Map`, but we will before GA. There will be some restrictions, such as keys must be `String` and the values will have the same restrictions as `Mixed`:
> ... may contain any schema type except for [arrays](https://www.mongodb.com/docs/atlas/app-services/schemas/types/#std-label-schema-type-array), [embedded objects](https://www.mongodb.com/docs/atlas/app-services/schemas/types/#std-label-schema-type-object), [sets](https://www.mongodb.com/docs/atlas/app-services/schemas/types/#std-label-schema-type-set), and [dictionaries](https://www.mongodb.com/docs/atlas/app-services/schemas/types/#std-label-schema-type-dictionary). App Services does not enforce a consistent type across documents, so two different documents may have values of different types.

In particular realm maps are not directly suitable for storing json.

**Comment by toshiossada** [comment]
Is this already works?

**Comment by nirinchev** [comment]
No, this didn't make it into the 1.0 release, but the team is looking to add support for maps in the near future.

**Comment by nirinchev** [comment]
We have a policy not to communicate timelines publicly. If you're using sync/Atlas App Services and this feature is critical for your application, please reach out to your account executive or support and they should be able to give you more concrete answers.

**Comment by d95sld95** [comment]
Any update on Maps being supported?

**Comment by blagoev** [comment]
Hi, this is high priority on our list for the upcoming features.

**Comment by plotic** [comment]
> Hi, this is high priority on our list for the upcoming features.

Hey @blagoev thanks for the update, is there an ETA ?

**Comment by blagoev** [comment]
@plotic 
As @nirinchev said we have a policy not to discuss timelines, but I can assure you this is on top of our priorities.

**Comment by MICKEY88661** [comment]
What is the suggest work around? Store keys and values in two different list?

**Comment by MICKEY88661** [comment]
Hi @nirinchev .
Thanks for the quick response , I will take it :)

**Comment by nirinchev** [comment]
Not yet, unfortunately.

**Comment by Shreedhar73** [comment]
Has the support for Nested Maps been provided ? 

For eg  : 

I wanted to store the following data  as RealmMap:

```
final mapData = {
  "title" : 'xyz',
  "age",: 12,
  "dob" : DateTime.now(),
  'metaData' : {
     "a": 'a',
     "b" : 'b'
   }
}
```

My parentRealm Objects is as :: 
```
final realmObjec = ParentModel{
_id : ObjectId(),
...

mapData : <String,RealmValue>{...},
}
```


I couldn't figure out how to store , a Map Datatype with in a value of a key in the map .  ( I think i can tackle this issue embedded object inside a map instead of nested map , but that is not my preference )

So is it possible to implement nested maps ?  (If not , are there any plans to implement that ). 


> [!NOTE]
On the RealmValue class , I saw RealmValue.fromString() ..fromDateTime() and all .
Can ..fromMap() be implemented ? 

@nirinchev

**Comment by nielsenko** [comment]
This will land with #1383 (soon)

**Comment by nirinchev** [comment]
This is not supported today, but we're working on it. You can follow this PR: https://github.com/realm/realm-dart/pull/1469, which adds the ability to store collections inside RealmValue.

**Comment by Shreedhar73** [comment]
@nirinchev thanks . Is there any ETA ?

**Comment by nirinchev** [comment]
Not yet - it's fairly close to completion for the local database, but if you're using Sync, you'll need to wait a bit longer for server side support.

**Comment by Shreedhar73** [comment]
> Not yet - it's fairly close to completion for the local database, but if you're using Sync, you'll need to wait a bit longer for server side support.

@nirinchev Hii, any updates on this?

**Comment by nirinchev** [comment]
This has been implemented for the local database and we're close to being done for sync. We expect to release it in the next couple of weeks.

**Comment by Shreedhar73** [comment]
@nirinchev Seems like, sync for maps has arrived on the stable 2.0. 

Still Couldnt figure out how to handle sync for nested Maps . 

For Something like :  
final mapData = {
  "title" : 'xyz',
  "age",: 12,
  "dob" : DateTime.now(),
  'metaData' : {
     "a": 'a',
     "b" : 'b'
   }
} .
