### ISSUE TITLE
Importing other realm object to be part of other object is impossible

### ISSUE THREAD

**Issue by hmbenhaim** [realm/realm-dart#686]
Hi I ran into an issue when I started to structure my project.
basically, if i want to create RealmModel and inside this mode including a RealmModel from a different file is impossible because RealmModel has to start with _ which makes it private in dart.
For example, i have this model

```
@RealmModel()
class _Person {
  late String name;
  int age = 1;
  @PrimaryKey()
  @MapTo('_id')
  late ObjectId id;
}
```

and this model
```

@RealmModel()
class _Car {
  late String make;
  String? model;
  int? kilometers = 500;
  _Person? owner;
  @PrimaryKey()
  @MapTo('_id')
  late ObjectId id;
}
```

and they are in two different files i can't import _Person into car file

i got this error 
```
[SEVERE] realm_dart:realm_generator on lib/models/car_model/car_model.dart (cached):

Not a realm type

in: package:realm_data_manager/models/car_model/car_model.dart:11:3
    ╷
6   │ @RealmModel()
7   │ class _Car {
    │       ━━━━ in realm model for 'Car'
... │
11  │   _Person? owner;
    │   ^^^^^^^^ _Person? is not a realm model type
    ```
if I'm importing the generated class i get this error 
```
[SEVERE] realm_dart:realm_generator on lib/models/car_model/car_model.dart:

Not a realm type

in: package:realm_data_manager/models/car_model/car_model.dart:12:3
    ╷
7   │ @RealmModel()
8   │ class _Car {
    │       ━━━━ in realm model for 'Car'
... │
12  │   Person? owner;
    │   ^^^^^^^ Person? is not a realm model type
    ╵
Did you intend to use _Person? as type for 'owner'?
```

thank you

**Comment by nielsenko** [comment]
You need to use the `$` prefix instead of `_`. We allow both, and if your models are defined in different files you need to use `$`.

**Comment by hmbenhaim** [comment]
i'll try that, sorry i just followed the example, in the example, all relations are in the same file

**Comment by hmbenhaim** [comment]
it's working perfectly fine with the ```$``` sign
Thanks
