### ISSUE TITLE
Automatic conversion of keys to snake_case

### ISSUE THREAD

**Issue by dotjon0** [realm/realm-dart#703]
Within MongoDB Atlas support documentation (not Realm), example model schema usually features snake_case for model properties, for example:

```
{
    title: `Apples`,
    bsonType: `object`,
    properties: {
      _id: {
        title: `Document ID`,
        bsonType: `objectId`
      },
      apple_type: {
        title: `Apple Type`,
        bsonType: `string`
      },
}
```

Within flutter, model/class properties are usually camelCase, for example:

```
@RealmModel()
class _Apples {

  @PrimaryKey()
  @MapTo("_id")
  ObjectId id;
  String appleType;
}
```

When using Realm Sync for Flutter this of course causes issues as `_id` does not map to `id` and `appleType` does not map to `apple_type`...  Obviously the 'id' scenario would need custom mapping i.e. `@MapTo("_id")`, but there should be an automatic way to resolve `apple_type`.

Would the Realm team consider implementing a similar approach to Google's json_serializable package https://pub.dev/packages/json_serializable to get around this? Essentially Google's json_serializable package has a configurable setting 'field_rename' (build.yaml  file), which when populated ('snake' for the above example) converts the Flutter class/model to the desired case (in the above example snake_case). Please see an example build.yaml file below:

```
targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
```

We look forward to your feedback. Best Wishes

**Comment by nielsenko** [comment]
That sounds like a good idea to me.

**Comment by dotjon0** [comment]
Thanks @nielsenko - I wish it was my idea but must give credit to Google! It may be worth looking at the other Build Options Google's package offers (see https://pub.dev/packages/json_serializable#build-configuration) as there may be some other good use cases - although beyond the scope of this issue suggestion as we just need the above...

**Comment by blagoev** [comment]
Hi, we have discussed this internally and we think the best way to handle this is through our Dart model generation on the server. When you have an existing snake case named schema on Atlas it will output the correct idiomatic Dart names for the models using the `MapTo ` attributes where needed.

Thanks for the suggestion.
