### ISSUE TITLE
@RealmModel using shared 'classes/models' in other files

### ISSUE THREAD

**Issue by dotjon0** [realm/realm-dart#704]
Essentially we have a range of `@RealmModel`'s, for example:

**file 1 - `_Car` Model/Class**

```
import 'package:app/models/vehicle_dimension.dart';

@RealmModel() 
class _Car {
  late String make;

  late String model;

  late List<VehicleDimension> dimensions;
}
```

file 2 - `_Van` Model/Class

```
import 'package:app/models/vehicle_dimension.dart';

@RealmModel()
class _Van {
  late String make;

  late String model;

  late List<VehicleDimension> dimensions;
}
```

You will notice the `VehicleDimension` class referenced in the `_Can` (file 1) and `_Van` (file 2) models/classes above is in another file (file 3), in order to centralise the class/model so there is no duplicate code + it makes maintenance easier and less prone to bugs (i.e. `VehicleDimension` is updated in 1 file rather than in multiple files so less prone to human error).

**file 3 ('package:app/models/vehicle_dimension.dart') - the 'shared' sub class/model**

```
@RealmModel()
class VehicleDimension {

  late int width;

 late int height;

 late int length;
}
```

Currently when you try to build the Realm models in Flutter via `flutter pub run realm generate` we get the error below:

```
in: package:app/models/car.dart:**XX:X**
    ╷
9   │ @RealmModel()
10  │ class _Car {
    │       ━━━━━━━━━━━━━ in realm model for 'AppCar'
... │
53  │   late List<VehicleDimension> dimensions;
    │        ^^^^^^^^^^^^^^^^^^^^^^^^^^ List<dynamic> is not a realm model type
    ╵
Remove the invalid field or add an @Ignored annotation on 'dimensions'.
```

So the only way is to copy `VehicleDimension` class/model into both `_Car` & `_Van` files **(files 1 & 2)** which is not ideal - support of the above scenario where **file 3** model `VehicleDimension` can be referenced in **files 1 & 2** (as above) would centralise things and remove the boiler plate duplicate code....

We are interested in the Realm's team's thoughts and perhaps this will be considered to be supported? FYI we feature this use case all over our Flutter app, so this would reduce a lot of boiler plate duplicate code for us.

Thank you!

**Comment by nielsenko** [comment]
Hi @dotjon0 

Composition is possible - also across files. Models should be named with either with a `_` or `$` as prefix. In this case you should name `VehicleDimension` as `$VehicleDimension` as it needs to be visible in another file, and refer to that in the `dimensions` list (ie. `late List<$VehicleDimension> dimensions;` or `final dimensions = <$VehicleDimension>[];`). Remember to import the file.

The reason the error message mentions `dynamic` is that `VehicleDimensions` is unresolved at this point. We are aware that the error messages you get in these cases are not the most informative, and we are contemplating how to better detect the nuances of the situation.

**Comment by dotjon0** [comment]
@nielsenko what fantastic news! We have put this in place and it works like a dream! Thank you so much and for the super fast help on this!

**Comment by jimisola** [comment]
@dotjon0 I took me some time to find that I could use $. It would be very useful if the examples in the documentation ([here](https://www.mongodb.com/docs/realm/sdk/flutter/realm-database/define-realm-object-schema/)) where a bit more advanced (or perhaps both a simple and an advanced one).
