### ISSUE TITLE
realm_generator should not be a realm's dependency (optional repo's dev_dependencies)

### ISSUE THREAD

**Issue by calvintam236** [realm/realm-dart#707]
`realm_generator` can be added to repo `pubspec`'s `dev_dependencies` instead of making it a dependency of `realm`.

This approach is used by `stacked` and [`stacked_generator`](https://pub.dev/packages/stacked_generator).

It is a development dependency and not needed for release build. (This saves build time as well.)
Some developers probably include the generated file in the source code already.

Occasionally, I have to comment `realm` out of `pubspec` in order to re-generate as `realm_generator` will conflict with another generator based on `build_runner` / extreme long generate time.

Not making `realm_generator` a realm's dependency provides flexibility on when to include `realm_generator` in the repo.

**Comment by nielsenko** [comment]
Hi @calvintam236 
This is something we have discussed in the team. As you mention, It would require the user to take a dev dependency on `realm_generator`. For now, we have decided on avoiding the dev dependency, but it is great to hear your feedback. Could you share what other generator is causing conflicts, and the exact generation times you see?
