### ISSUE TITLE
Documentation states ObjectId is not supported by Flutter SDK

### ISSUE THREAD

**Issue by dotjon0** [realm/realm-dart#716]
Evening. We have noticed at https://www.mongodb.com/docs/realm/reference/realm-query-language/ it states  "// Flutter SDK does not yet support ObjectId". Pretty sure ObjectId's are supported (we use them) so just wanted to give you the heads up the documentation may out outdated ;-)

**Comment by dotjon0** [comment]
Thanks @blagoev and pleased we could help - feel free to keep this issue open or close it

**Comment by mongodben** [comment]
@dotjon0, thank you for bringing this error to our attention. The docs have been updated to use `ObjectId` in the Flutter example on the [Realm Query Language page](https://www.mongodb.com/docs/realm/reference/realm-query-language/).

@blagoev you can close this issue out.
