### ISSUE TITLE
Failed to load dynamic library "realm_dart.dll" on server side

### ISSUE THREAD

**Issue by djx-y-z** [realm/realm-dart#720]
I have a local dart-package "db" that works with the realm database.

When I add this local package to my application (dart server), I get the error "Failed to load dynamic library'binary/windows/realm_dart.dll '"

There is an assumption that dart_realm can only work with Flutter application, since only Flutter application supports plugin loading, but I may be wrong.

**Comment by blagoev** [comment]
Hi, 
if you want to use Realm with Dart you need the `realm_dart` package. For Flutter you need the `realm` package. 

For Dart there is one additional step you need to do after you add the `realm_dart` package as dependency. You need to invoke the command `dart run realm_dart install` from the root dir of your app/package. This will copy the needed native binary in the root dir of your app/package so it can be loaded on startup of the app. 

This is captured in our readme.md

Cheers.

**Comment by djx-y-z** [comment]
> 

I skipped this step. Thanks!
