### ISSUE TITLE
cannot generate model in new flutter project

### ISSUE THREAD

**Issue by WingCH** [realm/realm-dart#721]
Reproduce step:

1. create new project
2. the preset sdk version in `pubspec.yaml` is `sdk: ">=2.17.6 <3.0.0"`
3. follow official [doc](https://pub.dev/packages/realm#usage)
4.  `flutter pub add realm`
5. Import Realm in a dart file , name `catalog.dart`
```
import 'package:realm/realm.dart';
part 'catalog.g.dart';

@RealmModel()
class _Item {
  @PrimaryKey()
  late int id;

  late String name;

  int price = 42;
}
```

6. run `  flutter pub run realm generate`
7. no any result
```dart
❯ flutter pub run realm generate


```

**Comment by blagoev** [comment]
Hi, 
you need to declare `part of` at the top of that file. Check our readme.md for that.

**Comment by WingCH** [comment]
i have declare `part of` at the top of that file , just missing in step...
