### ISSUE TITLE
Firebase Auth Authentication via Custom JWT

### ISSUE THREAD

**Issue by dotjon0** [realm/realm-dart#722]
Evening, does Realm Flutter support 'Custom JWT' authentication? I.e. so our users can log in via Firebase Auth https://www.mongodb.com/docs/atlas/app-services/authentication/custom-jwt/#firebase-jwt-authentication

**Comment by blagoev** [comment]
Hi, 
 That's not supported yet, but its high on out list for the next versions. Stay tuned.

**Comment by dotjon0** [comment]
Amazing @blagoev - cant wait!

**Comment by elhe26** [comment]
Where can we follow this implementation? Is there a roadmap?

**Comment by jimisola** [comment]
I found this [article "How to use Firebase Authentication with MongoDB Realm the Easy Way"](https://levelup.gitconnected.com/how-to-use-firebase-authentication-with-mongodb-realm-the-easy-way-5b85c8532000) can it be of help?

**Comment by dotjon0** [comment]
Thank you for this, however issue #722 is around support for custom JWT / Firebase Auth within the Realm SDK for Flutter™ and Dart™ - @blagoev has kindly covered this off above. 

Believe the general configuration of custom JWT and Firebase Auth within Realm / MongoDB Device Sync is outside of the Realm SDK for Flutter™ and Dart™ repo - official docs for this can however be found at https://www.mongodb.com/docs/atlas/app-services/authentication/custom-jwt/#firebase-jwt-authentication

**Comment by nielsenko** [comment]
Resolved in [0.3.2+beta](https://pub.dev/packages/realm/versions/0.3.2+beta)

**Comment by dotjon0** [comment]
Thanks so much @nielsenko, really appreciated! Hope you have a great rest of week!
