### ISSUE TITLE
 How do I upgrade my database and save the migrated data

### ISSUE THREAD

**Issue by zhouxin1233** [realm/realm-dart#724]
In Flutter App ,How do I upgrade my database and save the migrated data

**Comment by ChangJoo-Park** [comment]
+1 here.

**Comment by nielsenko** [comment]
We do not support migrations yet (it is on our backlog https://github.com/realm/realm-dart/issues/70)

**Comment by ChangJoo-Park** [comment]
Hello @nielsenko, How can I update schema with data already exists?

**Comment by nielsenko** [comment]
Until we have proper migration support you need to generate both the old and the new model, and manually read the old objects, convert them, and store them in the new schema. It will be easier once we are out of beta, and https://github.com/realm/realm-dart/issues/70 is completed.

**Comment by ChangJoo-Park** [comment]
Thanks @nielsenko  :)
