### ISSUE TITLE
Infinite scroll / pagination implémentation 

### ISSUE THREAD

**Issue by elhe26** [realm/realm-dart#733]
Hi, 

Is there any documentation regarding how to implement either infinite scrolling or pagination using realm?

Is there a roadmap stating when live query will be implemented?

**Comment by nielsenko** [comment]
For infinite scrolling, just open a `RealmResult` and start iterating. You don't need to paginate as the iterator is lazy.
Live queries already exists today - you can subscribe for changes using the `RealmResult.changes` stream.
Look here: https://github.com/mongodb-university/realm-template-apps/tree/main/flutter for a sample of how to handle a list view of a live query with potentially many ("infinite") elements.

**Comment by elhe26** [comment]
Thanks! Closing issue.
