### ISSUE TITLE
Is there a way to determine historical subscriptions?

### ISSUE THREAD

**Issue by n-doton** [realm/realm-dart#734]
From my understanding, you shouldn't resubscribe to collections if a user re-opens an app that's already been subscribed.

The documentation states ``` Any changes to the subscription set will be persisted locally and be available the next time the application starts up ```.

Do we just make new subscriptions each time the app is opened, with Realm handling the rest, or do we need our own business logic to prevent resubscriptions?

Thanks in advance for the help.

**Comment by nielsenko** [comment]
Adding the exact same subscription again is an idempotent operation, so re-subscription is okay. For named subscription you need to set the update flag, even though they query and name is identical. Adding the same unnamed query twice without requesting an update will just de-duplicate.

So no, you don't need to do anything fancy in most cases.

**Comment by nirinchev** [comment]
One thing to note though is that updating subscriptions will create a write transaction, which is cheap but not free. You can access existing subscriptions by examining the `realm.subscriptions` property. By adding some boilerplate, you can avoid the cost of the write transaction - like:

```dart
final tasks = realm.all<Task>();
if (realm.subscriptions.find(tasks) == null) {
  realm.subscriptions.update(() {
    realm.subscriptions.add(tasks);
  });
}
```

Obviously that will get more complex if you have many subscriptions, but depending on your performance requirements, it may be worth it.
