### ISSUE TITLE
Querying data using nested models

### ISSUE THREAD

**Issue by elhe26** [realm/realm-dart#737]
Hi,

I have the following implementation:

**polls.dart**

```dart
@RealmModel()
class $Polls {
  @PrimaryKey()
  @MapTo("_id")
  late ObjectId id;

  bool active = true;

  int chooseFirst = 0;

  int chooseSecond = 0;

  String firstAnswer = "";

  String secondAnswer = "";

  String question = "";

  @MapTo("createdAtSearch")
  late num createdAtSearch;

  @MapTo("updatedAtSearch")
  late num updatedAtSearch;

  String postId = "";

 @MapTo("profileUser")
  late $ProfileUser profileUser;
}

```

**profile_user.dart**

```dart
@RealmModel()
class $ProfileUser {
  @PrimaryKey()
  @MapTo("_id")
  late ObjectId id;

  String userName = ""; .

  String userLastName = "";

  String userAge = "";

  String userUniqueId = "";
}
```

How can I query `Polls` collection using profileUser? 
Is this possible: ie. `final polls = realm.all<Polls>().query(r'profileUser.userUniqueId  == $0', [uniqueUserId]);` ?

**Comment by nielsenko** [comment]
You can use backlinks. Support for backlinks are somewhat lacking in the Dart SDK currently, as you cannot name them, but you can still use them without a name by fully describing the forward relationship using the `@links.ClassName.PropertyName` syntax. In your case that would be:
```dart
realm.all<Polls>(r'@links.ProfileUser.userUniqueId == $0', [uniqueUserId]);
```
if I recall correctly (didn't test). You can see some examples of backlinks and RQL here: https://www.mongodb.com/docs/realm-sdks/js/latest/tutorial-query-language.html

**Comment by nielsenko** [comment]
You could consider having a `late List<$Polls> polls` on `$ProfileUser` instead. This will allow you to point to the same poll from different profile users, and you can directly access the polls of a user in code as `user.polls`.

BTW, you have some unneeded `@MapTo` annotations in the above example.

**Comment by elhe26** [comment]
Thanks, @nielsenko ! Sorry for all the questions, hehe. 

While we are it, Is there a way to use [update operators](https://www.mongodb.com/docs/manual/reference/operator/update/#std-label-update-operators-processing-order) such as `$inc` or `$currentDate`?

**Comment by nielsenko** [comment]
RQL differs from MongoDB QL proper in many ways, and a `$inc` like operator is not supported in RQL. For `$currentDate` you can just use `DateTime.now` (if you trust the local clock).

Realm does have a special `RealmInteger` class that can correctly handle addition and subtractions across disconnected devices, and ensure eventual consistency, but it is not supported in the Dart SDK yet :-/. You can read about it in the docs for the other SDKs, fx here: https://www.mongodb.com/docs/realm/sdk/dotnet/data-types/realm-integer/.

You could simulate it with a `List<int>` and append add- or sub-ops to this list. Then each client can evaluate the value, by summing the list, and be assured eventual consistency.

Eventually we will also support working directly with MongoDB queries and functions, and hence support `$inc`, but only when online.

**Comment by elhe26** [comment]
Thanks, @nielsenko. Closing this issue.
