### ISSUE TITLE
Selectively enable 'Device Sync' (App Services) for Realm local DB models/collections

### ISSUE THREAD

**Issue by dotjon0** [realm/realm-dart#748]
**Describe your problem or use case**
Selectively enable 'Device Sync' (App Services) for Realm local DB models/collections. For example, you may want to queue API requests when 'offline' which is stored in a Realm local DB model/collection and then have 20 x other Realm local DB models/collections which are hooked up to 'Device Sync' (App Services).

**Describe the solution you'd like**
Selectively configure which collections hook up with 'Device Sync' (App Services). This could perhaps go into the Configuration which is then passed into a Realm instance.

**Comment by nielsenko** [comment]
Could you open two different realms, one that is local only and another that is synced?

**Comment by dotjon0** [comment]
Hi @nielsenko yes could do. Would it not be more resource efficient on the device if there was 1 x realm which supports both? I yes, then 2 x realms in the mean time is a good workaround so we shall look into this.

**Comment by nielsenko** [comment]
The only issue I see with having a separate realm, is that you loose the ability to do transactions across. This may or may not be a problem for you. Performance wise I would not be worried.

**Comment by dotjon0** [comment]
Ok perfect @nielsenko - no need for transactions for our use case. Thank you as always!
