### ISSUE TITLE
Support list comparison in RQL

### ISSUE THREAD

**Issue by nielsenko** [realm/realm-dart#755]
As of realm-core v12.5.0 RQL supports list comparisons, but the Dart SDK does not handle list arguments. Example:

```dart
realm.query('list = $0', [[1,2,3]]);
```

**Comment by thipokch** [comment]
@nielsenko Are there any workaround for this?

**Comment by nielsenko** [comment]
What predicate are you trying to use?

**Comment by thipokch** [comment]
I've tried this `id IN { 1, 2, 3 }` using string concat, but I'm unsure whether if this a way to go.

**Comment by nielsenko** [comment]
@thipokch I just accidentally revisited this issue, and saw I didn't respond to your reply. I'm very sorry about this oversight. 

First, `IN` is different from `=`. The first checks for inclusion, the second for equality. But you hit a similar problem.

Yes string concatenation is the needed for now, but it is important that you do it on the query string itself, and not in the args, ie:
```dart
final list = [1,2,3];
realm.query(id IN {${list.join(',')}};
```
**not**
```dart
realm.query('id IN {$0}', [list]); // <-- won't work
realm.query('id IN {$0}', [list.join(',')]); // <-- won't work either
```

**Comment by desistefanova** [comment]
Query list arguments are now supported in [Realm SDK 1.4.0](https://pub.dev/packages/realm)
