### ISSUE TITLE
Use official Dart docker image where possible instead of subosito/flutter-action@v2

### ISSUE THREAD

**Issue by nielsenko** [realm/realm-dart#758]

**Comment by nirinchev** [comment]
What is the motivation behind it? I guess we can only use the docker image for the linux tests, which hardly seems worth it.

**Comment by nielsenko** [comment]
> What is the motivation behind it? I guess we can only use the docker image for the linux tests, which hardly seems worth it.
Speed! I was a bit frustrated with time it takes to run the generator tests is completely dominated by setting up flutter. But you are right, I close this again.
