### ISSUE TITLE
Error: The non-abstract class 'PseudoType' is missing implementations for these members

### ISSUE THREAD

**Issue by cheuhyakuroku** [realm/realm-dart#760]
[INFO] Generating build script...
[INFO] Generating build script completed, took 324ms

[INFO] Precompiling build script......
[WARNING] ../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/realm_generator-0.3.1+beta/lib/src/pseudo_type.dart:12:7: Error: The non-abstract class 'PseudoType' is missing implementations for these members:
 - DartType.element2
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class PseudoType extends TypeImpl {
      ^^^^^^^^^^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-4.6.0/lib/dart/element/type.dart:52:16: Context: 'DartType.element2' is defined here.
  Element? get element2;
               ^^^^^^^^
[INFO] Precompiling build script... completed, took 5.4s

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.

**Comment by nielsenko** [comment]
Hi @cheuhyakuroku 

Thank you for reporting this. For now avoid using `analyzer` package version **4.6.0**, by adding a constraint to your `pubsepc.yaml`:
```yaml
dependencies: 
  analyzer: '>=4.0.0 <4.6.0'
```

**Comment by nielsenko** [comment]
A fix is released with [0.3.2+beta](https://pub.dev/packages/realm/versions/0.3.2+beta)
