### ISSUE TITLE
Support connect to remote database

### ISSUE THREAD

**Issue by RedFox64** [realm/realm-dart#874]
Hello!

Can I use this package to connect to the MongoDB Atlas database?

**Comment by nielsenko** [comment]
Yes you can. Check out https://www.mongodb.com/docs/realm/introduction/

**Comment by nirinchev** [comment]
Actually, it depends on what exactly you're looking to do. If you want to use it as a driver to connect to MongoDB directly, then no - it's not possible with this package.

In the future, we'll expose an API to query MongoDB via Atlas App Services (similar to what is [available in the .NET SDK](https://www.mongodb.com/docs/realm/sdk/dotnet/examples/mongodb-remote-access/)), but that will still be going over http and not using the MongoDB protocol.
