### ISSUE TITLE
[Bug]: `List.removeAt` doesn't work

### ISSUE THREAD

**Issue by Comanx** [realm/realm-dart#883]
### What happened?

when use list.remove data cannot be deleted
data  should be deleted.

### Repro steps

```
FutureOr<void> removeCoordinatesImage(CoordPoint point, int index) async {
    var image = File(point.imagePaths[index]);
    if (image.existsSync()) image.delete();
    point.realm.write(() {
      point.imagePaths.removeAt(index);
    });
  }
```
imagePaths.length will not change
imagePaths type is `List<String>`

### Version

0.4.0-beta

### What Realm SDK flavor are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

Android 10

**Comment by nielsenko** [comment]
@Comanx The fix was just released with [0.5.0+beta](https://pub.dev/packages/realm/versions/0.5.0+beta)
