### ISSUE TITLE
[Bug]:  Realm SDK doesn't work by default on the MacOS emulator

### ISSUE THREAD

**Issue by mongodben** [realm/realm-dart#889]
### What happened?

When using the Realm Flutter SDK on the MacOS emulator, network requests do not work unless i add the following code to the files `DebugProfile.entitlements` and `Release.entitlements`:

```xml
<key>com.apple.security.network.client</key>
<true/>
```

when i tried to log in a user without adding the above code, i got the following error message: 

```
Realm Exception : non-zero custom status code considered fatal
```

potential fix ideas: 

- realm flutter sdk can inject this code into these files on build (not sure if possible)
- more descriptive error message
- document that need to add this code

### Repro steps

1. write code to log user in to Realm
2. open with mac emulator

### Version

Flutter 3.0.5, Dart 2.17.6

### What Realm SDK flavor are you using?

MongoDB Atlas (i.e. Sync, auth, functions)

### What type of application is this?

Flutter Application

### Client OS and version

macOS 12.5.1

### Code snippets

this error was found when running the Realm Flutter template app https://github.com/mongodb-university/realm-template-apps/tree/main/flutter 

### Stacktrace of the exception/crash you're getting

```shell
Realm Exception : non-zero custom status code considered fatal
```

### Relevant log output

```shell
none
```

**Comment by nielsenko** [comment]
I think we should consider making a [mason](https://pub.dev/packages/mason_cli) _realm_starter_ brick. This could ask for permission to setup entitlements for the user.
