### ISSUE TITLE
[Bug]: DateTime & TimeZone, invalid date returned

### ISSUE THREAD

**Issue by tanukijs** [realm/realm-dart#901]
### What happened?

Since i migrated to Realm, i saw a problem with my dates everywhere. It seems that all the date have been shifted to another TimeZone.

My phone has TimeZone set to Paris, it's 07:30 AM and realm return me 05:30 AM.

I found out that i can convert the date `.toUtc()` before inserting it to realm & convert it back to `.toLocal()` but as i didn't see any informations anywhere else than https://github.com/realm/realm-dart/pull/569 i didn't expect DateTime field to work like that.

### Repro steps

1. Define an entity that contain a `DateTime` field
2. Insert an entity with a DateTime
3. Compare the value of `DateTime.now()` & the value returned by our newly created entity

### Version

3.3.0

### What Realm SDK flavor are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

Realm Dart 0.4.0+beta

### Code snippets

Here is a snippet, we only need an entity with a `DateTime` field to reproduce the problem.
```dart
final createdAt = DateTime.now(); // 07:30 AM
realm.write(() {
  entity.createdAt = createdAt;
  print('1 ${message.createdAt}');  // 05:30 AM
  print('2 $createdAt'); // 07:30 AM
});
```

### Relevant log output

```shell
[+16808 ms] flutter: 1 2022-09-14 05:51:00.831907Z
[   +1 ms] flutter: 2 2022-09-14 07:51:00.831907
```

**Comment by blagoev** [comment]
Hi, 
DateTimes are persisted as UTC DateTimes in Realm. You need to convert it back to what timezone you need or the timezone of the device when you read the values.

**Comment by desistefanova** [comment]
Hi @tanukijs,
thanks for noticing this!
We will check the documentation.

**Comment by nielsenko** [comment]
Here is an example of how you can handle timezone data:
```dart
import 'package:realm_dart/realm.dart';
import 'package:timezone/timezone.dart' as tz;
import 'package:timezone/data/latest.dart' as tz;

part 'realm_datetime_with_timezone.g.dart';

@RealmModel()
class _Data {
  late DateTime dateTimeUtc;
  late String locationName; // tz database/Olson name

  tz.TZDateTime get dateTime => tz.TZDateTime.from(
        dateTimeUtc,
        tz.getLocation(locationName),
      );
}

Data createData(tz.TZDateTime value) => Data(
      DateTime.fromMillisecondsSinceEpoch(value.millisecondsSinceEpoch), // value.toUtc() won't work
      value.location.name,
    );

void main(List<String> arguments) {
  tz.initializeTimeZones();

  final paris = tz.getLocation('Europe/Paris');
  var year = 1789;

  final r = Realm(Configuration.inMemory([Data.schema]));
  r.write(() {
    while (year < 2023) {
      final bastilleDay = tz.TZDateTime(paris, year++, 7, 14);
      r.add(createData(bastilleDay));
    }
  });

  for (final data in r.all<Data>()) {
    final x = data.dateTime;
    print(
      'iso6801: ${x.toIso8601String()}, '
      'weekday: ${x.weekday}, ' // 1 based, ie. 1 is monday
      'location: ${x.location}, '
      'timezone: ${x.timeZone}, '
      'timezoneOffset: ${x.timeZoneOffset}',
    );
  }

  Realm.shutdown();
}
```

**Comment by desistefanova** [comment]
Hi @tanukijs,
We will add a note to our documentation about storing dates in UTC.
This issue will be resolved once the documentation is ready.
Thank you for your contribution!

**Comment by tanukijs** [comment]
Hello, this is way clearer to me. Thank you for your fast replies !

**Comment by desistefanova** [comment]
Hi @tanukijs ,
Here is the section of the updated document in relation to storing UTC DateTame to Realm.
https://www.mongodb.com/docs/realm/sdk/flutter/realm-database/data-types/#datetime
Thanks! I'm closing the issue.
