### ISSUE TITLE
Request for Realm instance in write transaction block

### ISSUE THREAD

**Issue by topperspal** [realm/realm-dart#994]
## Description

Suppose we are using some dependency injector and we need to perform a write transaction, this is how I do
```dart
// Inject dependency
final pvRealm = Provider<Realm>((_) {
  var config = Configuration.local([...]);
  return Realm(config);
});

// Usages
ref.read(pvRealm).write(() {
   ref.read(pvRealm).add(...);
   ...
});

// Or 

final realm = ref.read(pvRealm);

realm.write(() {
  realm.add(...);
  ...
});

// But the simplest way of performing a write transaction, I think is
ref.read(pvRealm).write((realm) {
   realm.add(...);
   ...
});

// This way is also similar to sqlite and firestore transactions
```

**Comment by blagoev** [comment]
Hi, thanks for the suggestion. 
We see the value, but also we are striving to sync the API with the rest of the Realm SDKs while at the same time providing idiomatic API for the concrete language. So it is a balance act. 
We will keep your suggestion in mind for the future and see if others also request it.

Currently, you can easily achieve this with an extension method. So something like this:

```dart
extension RealmEx on Realm {
  T action<T>(T Function(Realm myRealm) callback) {
    return callback(this);
  }
}

var realm = Realm(config);
realm.action((myRealm) => myRealm.write(.....));
```

cheers

**Comment by topperspal** [comment]
🙏
