### ISSUE TITLE
[Bug]: LIKE realm query string operator returning no results

### ISSUE THREAD

**Issue by dotjon0** [realm/realm-dart#995]
### What happened?
Evening, hope you are all well.

We attempted a query using the LIKE string operator (https://www.mongodb.com/docs/realm/realm-query-language/#string-operators) and no results were returned. A query with the CONTAINS string operator is working as expected. 

LIKE is particularity of interest due to the more fuzzy search nature of the query - if not supported yet can we raise a feature request please?

If only some of the query string operators are supported at https://www.mongodb.com/docs/realm/realm-query-language/#string-operators, is it possible to know which ones are not supported?

Thank you again in advance!

### Repro steps
These 2 examples return 0 x results (using LIKE):

```
realm.all<T>().query("name LIKE 'Dig'");
realm.all<T>().query("name LIKE[c] 'Dig'");
```

Yet the below 2 examples return many results (using CONTAINS):

```
realm.all<T>().query("name CONTAINS[c] 'Dog'");
realm.all<T>().query("name CONTAINS[c] 'D'");
```

### Version
0.6.0+beta

### What Realm SDK flavor are you using?
MongoDB Atlas (i.e. Sync, auth, functions)

### What type of application is this?
Flutter Application

### Client OS and version
macOS 12.6

### Stacktrace of the exception/crash you're getting
```shell
n/a
```

### Relevant log output
```shell
n/a
```

**Comment by nirinchev** [comment]
Hey, for `LIKE` to behave like `CONTAINS`, you need to add wildcards at the beginning and the end of the search phrase. For example, these two queries are equivalent:

```dart
realm.all<Person>("name CONTAINS[c] 'a'");
realm.all<Person>("name LIKE[c] '*a*'");
```

If you don't have wildcards, then `LIKE` will try to match exactly, meaning for your example, only objects where `name == 'Dig'` will be returned.

**Comment by dotjon0** [comment]
Thanks for the incredible fast help @nirinchev, very very appreciated and hope you are having a good week so far.

For the examples below, `Person.name` is "Dog".

This returns 0 x results:

`realm.all<Person>("name LIKE[c] '*dig*'");`

This returns 1 x results - so perhaps LIKE is 'exact matching' which sounds like something is not right?

`realm.all<Person>("name LIKE[c] '*dog*'");`

**Comment by dotjon0** [comment]
Seems I have misunderstood the documentation (https://www.mongodb.com/docs/realm/realm-query-language/#string-operators), apologies. 

I can now see that the wildcard string "d?g" matches "dog", "dig", and "dug", but not "ding", "dg", or "a dog". 

Please feel free to close this if the above is my mistake and thank you again for your help on this!

**Comment by nirinchev** [comment]
Ah, I see. Yes, unfortunately, `LIKE` doesn't do fuzzy matching like a true full text search would do. It's instead more similar to a very limited regex search, where you provide a pattern and we compare each entry against that pattern.

We do have some very early POCs of full text search, but it's not something we're actively working on right now and as such, we don't have a clear timeline for when it might land.
